starkware-libs/sequencer

Cargo.toml
crates/blockifier/src/lib.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs
crates/mempool_infra/src/component_client/local_component_client.rs
crates/native_blockifier/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/109)

fix: workaround for lint_groups_priority issue

---

crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/errors.rs
crates/papyrus_monitoring_gateway/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/128)

fix(execution): forbid calling cairo0 contract with cairo1 only builtins

---

crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/161)

refactor: use TransactionContext::fee_token_address

---

.github/workflows/committer_ci.yml
crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/errors.rs
crates/papyrus_monitoring_gateway/src/lib.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/169)

Merge main-v0.13.2 into main

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/70)

feat(consensus): add advance_to_round

---

crates/mempool_infra/src/component_client/definitions.rs
crates/mempool_infra/src/component_client/remote_component_client.rs
crates/mempool_types/src/communication.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/173)

feat(mempool_infra): make ClientError cloneable

---

crates/papyrus_network/src/bin_utils/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/210)

fix: remove unusued dependency from papyrus network

---

crates/blockifier/src/context.rs

- Derive Serialize/Deserialize towards Papyrus config on these structs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/97)

chore: derive serialize and deserialize for chain info

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/context.rs

There is code duplication in the Chain info struct in the gateway. To solve this duplication, Chain info needs to implement serialize config.
- implement serialize config for blockifier chain info.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/98)

chore: impl serialize config for chain info

---

Cargo.lock
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_protobuf/src/consensus.rs
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/166)

feat(consensus): test receiver to mock network failures during simulations

---

crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/200)

refactor(consensus): create manager which encapsulates messages cached between heights

---

Cargo.lock
crates/batcher/Cargo.toml
crates/batcher/src/batcher.rs
crates/batcher/src/communication.rs
crates/batcher/src/lib.rs

feat: add batcher and com prep

---

crates/papyrus_protobuf/src/converters/mod.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/types.rs

1. Separate fn for handling cached messages per height
2. Return errors instead of panic when receiving messages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/208)

refactor(consensus): minor refactor of the manager

---

.github/workflows/main.yml
crates/papyrus_config/Cargo.toml
crates/papyrus_load_test/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

Having this just at the workspace level doesn't seem to suppress the warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/287)

fix(network): update package Cargo.toml's with lint configuration to ignore coverage_nightly

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point_execution.rs
crates/blockifier/src/execution/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/314)

chore: use BuiltinName enum in EntryPointV1 instead of string

---

Cargo.toml
crates/blockifier/Cargo.toml
crates/committer_cli/Cargo.toml
crates/gateway/Cargo.toml
crates/mempool/Cargo.toml
crates/mempool_node/Cargo.toml
crates/mempool_test_utils/Cargo.toml
crates/mempool_types/Cargo.toml
crates/native_blockifier/Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_common/Cargo.toml
crates/papyrus_config/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_proc_macros/Cargo.toml
crates/papyrus_protobuf/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/papyrus_test_utils/Cargo.toml
crates/sequencing/papyrus_block_builder/Cargo.toml
crates/sequencing/papyrus_consensus/Cargo.toml
crates/starknet_client/Cargo.toml
crates/starknet_sierra_compile/Cargo.toml
crates/tests-integration/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/312)

chore(ci): move local deps to root toml

---

.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/blockifier_coverage.yml
.github/workflows/blockifier_post-merge.yml
.github/workflows/clean_stale_prs.yml
.github/workflows/committer_ci.yml
.github/workflows/lock_closed_prs.yml
.github/workflows/main.yml
.github/workflows/merge_paths_ci.yml
.github/workflows/papyrus/helm-install.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_docker-publish.yml
.github/workflows/papyrus_nightly-tests.yml
.github/workflows/verify-deps.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/333)

chore(ci): use large-runners in order to increase concurrency

---

crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/340)

refactor(blockifier): rename function gas_price to l1_gas_price

---

crates/committer_cli/src/tests/utils/objects.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_protobuf/src/converters/receipt.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs
crates/papyrus_rpc/src/v0_7/transaction.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_hash/receipt_commitment.rs
crates/starknet_api/src/block_hash/test_utils.rs
crates/starknet_api/src/execution_resources.rs
crates/starknet_api/src/lib.rs
crates/starknet_api/src/transaction.rs
crates/starknet_client/src/reader/objects/test_utils.rs
crates/starknet_client/src/reader/objects/transaction.rs

As part of refactoring the file `transaction.rs`, I noticed this file is too big.
Let us split this file and move some objects into the file `execution_resources.rs`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/335)

chore: create execution_resources file to split the starknet api transaction file

---

crates/gateway/src/compilation.rs
crates/starknet_sierra_compile/src/compile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/318)

refactor: move the panic catch into the compile sierra to casm method

---

crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/starknet_sierra_compile/src/compile.rs
crates/starknet_sierra_compile/src/compile_test.rs
crates/starknet_sierra_compile/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/319)

refactor: define sierra to casm compiler trait

---

crates/sequencing/papyrus_consensus/src/state_machine_test.rs

Kept the assertions as is since it is nice for errors to show the exact line in the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/347)

refactor(consensus): add a test wrapper to avoid boilerplate with response events

---

Cargo.toml
crates/batcher/Cargo.toml
crates/batcher_types/Cargo.toml
crates/blockifier/Cargo.toml
crates/consensus_manager/Cargo.toml
crates/consensus_manager_types/Cargo.toml

build: move local deps to root toml

---

.github/actions/install_rust/action.yml
.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/blockifier_coverage.yml
.github/workflows/blockifier_post-merge.yml
.github/workflows/committer_ci.yml
.github/workflows/main.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_nightly-tests-call.yml
.github/workflows/papyrus_nightly-tests.yml
.github/workflows/verify-deps.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/294)

feat(ci): make rust version in ci configurable

---

crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/papyrus_execution/src/objects.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/113)

build(fee): add l2_gas field to gas vector

---

crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/manager.rs

this is in preparation for adding more functionality with the sync channel. I prefer not to
have functionality in the lib file as I see its purpose as cataloguing the modules and
public exports of the crate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/386)

refactor(consensus): move run_consensus out of lib.rs

---

crates/blockifier/src/test_utils/contracts.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/179)

chore(blockifier): refactor feature contract path getters for different paths

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/cairo_compile.rs
crates/blockifier/src/test_utils/contracts.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/180)

chore(blockifier): move contract compilation logic to separate module + contracts.rs

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/test_utils/cairo_compile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/181)

chore(blockifier): fetch compiler repo version

---

crates/blockifier/src/test_utils/cairo_compile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/182)

feat(blockifier): verify cairo-lang version before Cairo0 compilation

---

crates/blockifier/src/test_utils/cairo_compile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/183)

chore(blockifier): verify cairo compiler repo (with correct tag)

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/test_utils/cairo_compile.rs
crates/blockifier/src/test_utils/contracts.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/184)

feat(blockifier): support Cairo1 local recompilation

---

crates/blockifier/src/test_utils/cairo_compile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/194)

chore(blockifier): verify local cairo repo state before compiling

---

crates/blockifier/src/test_utils/cairo_compile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/195)

chore(blockifier): add text file with current compiler version for CI use

---

crates/blockifier/src/test_utils/contracts.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/196)

chore(blockifier): add is_legacy method

---

.github/workflows/blockifier_compiled_cairo.yml
crates/blockifier/src/test_utils/cairo_compile.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/197)

feat(blockifier): recompile Cairo1 in the CI

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions.rs
crates/starknet_api/src/contract_class.rs
crates/starknet_api/src/executable_transaction.rs
crates/starknet_api/src/lib.rs

This is a draft. A PR composed of multiple commits, which show the process handled one step at a time.
refactor: add casm contract class struct compatible for executable transaction
refactor: use casm contract class for executable transaction
refactor: add try from executable declare tx to account tx
chore: remove handle of impossible scenarios
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/357)

refactor: add casm contract class struct compatible for executable transaction

---

.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/blockifier_coverage.yml
.github/workflows/blockifier_post-merge.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/76)

chore: improve blockifier CI trigger and scope

---

Cargo.lock
crates/gateway/Cargo.toml
crates/gateway/src/compiler_version.rs
crates/gateway/src/stateless_transaction_validator_test.rs
crates/gateway/src/test_utils.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_sierra_compile/src/utils.rs

The validation for version ID is currently only validating the version is in range. It does not validate the compiler version is included in the contract.
- Use the Cairo lang deserializer to deserialize the version ID.
- The gateway now validates the compiler version is included in the program.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/84)

chore: use cairo lang util to extract sierra program version id

---

Cargo.lock
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs

This is how consensus updates the rest of the node when a new block has been decided.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/387)

feat(consensus): add decision fn to consensus context API

---

crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

This allows for the block propogation to tell consensus to move on if it's working on an
old height. Special was taken to make this cancel safe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/389)

feat(consensus): add sync receiver to consensus

---

crates/papyrus_common/src/metrics.rs
crates/sequencing/papyrus_consensus/run_consensus.py
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs

This will be more useful than stating the most recent decision when we are stuck on block 0.
Also moved out of Context::decision due to sync
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/404)

feat(consensus): redefine consensus height metric to working height

---

crates/starknet_api/src/contract_class.rs
crates/starknet_api/src/executable_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/426)

feat(starknet_api): derive serialize for executable transaction

---

Cargo.lock
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs

This is because the network registration logic will become more complex with test sync.
In practice this means that after the initial network config we hold off on spawning the task
until all tasks have been set up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/409)

refactor(consensus): consensus handles its network registrations on its own

---

config/papyrus/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/sequencing/papyrus_consensus/src/config.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/412)

feat(consensus): add sync_topic to test config

---

crates/papyrus_node/src/main.rs
crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs

This is optional since outside of testing mode sync should be its own component of the node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/413)

feat(consensus): add sync sender to context to broadcast on decision

---

crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/src/versioned_constants.rs
crates/papyrus_execution/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/464)

chore(blockifier): add versioned constant file for v0.13.2

---

crates/gateway/src/compiler_version.rs
crates/gateway/src/config.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs
crates/gateway/src/test_utils.rs

There is code duplication between Cairo-Lang's version ID and the gateway's version ID.
- Refactor the Gateway's version ID as a wrapper.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/83)

chore: wrap cairo lang version id for code dedup

---

crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/414)

feat(consensus): simulations with the test config will use the fake consensus sync

---

crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/465)

refactor(consensus): rename notify_decision to decision_reached

---

crates/papyrus_common/src/metrics.rs
crates/sequencing/papyrus_consensus/run_consensus.py
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/490)

feat(consensus): add metric for sync in consensus and update the simulation script

---

crates/blockifier/src/execution/contract_class.rs

In a previous PR: https://reviewable.io/reviews/starkware-libs/blockifier/452, there was a mixup with the docstring of the structs.
This PR fixes this issue.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/491)

chore: fix docstring of executable contract class structs

---

crates/papyrus_network/src/discovery/identify_impl.rs
crates/papyrus_network/src/discovery/kad_impl.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/468)

fix(network): filter out localhost when identify notifies kademlia

---

crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/utils.rs
crates/starknet_api/src/executable_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/360)

refactor(gateway): send internal tx instead of thin tx

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/437)

feat(mempool): add resource bounds to transaction reference type

---

crates/blockifier/src/blockifier/stateful_validator_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/execution/stack_trace_test.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/gateway/src/utils.rs
crates/starknet_api/src/executable_transaction.rs

For internal deploy account transaction, the data is inseparable from the implementation.
The data of `IntrnalDeployAccountTransaction` and of `DeployAccountTransaction` (on the blockifier) is duplicated.
- Refactor `DeployAccountTransaction` as a wrapper of `IntrnalDeployAccountTransaction` while keeping the implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/92)

chore: refactor deploy account as wrapper

---

crates/starknet_committer/src/block_committer/input.rs
crates/starknet_committer/src/block_committer/input_test.rs
crates/starknet_committer/src/forest/filled_forest.rs
crates/starknet_committer/src/forest/forest_errors.rs
crates/starknet_patricia/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/495)

feat(committer): use FilledTree::create() in filled forest

---

crates/blockifier/src/transaction/transactions.rs
crates/gateway/src/utils.rs
crates/starknet_api/src/executable_transaction.rs

For internal deploy account transaction, the data is inseparable from the implementation.
The data of `IntrnalInvokeTransaction` and of `InvokeTransaction` (on the blockifier) is duplicated.
- Refactor `InvokeTransaction` as a wrapper of `IntrnalInvokeTransaction` while keeping the implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/93)

chore: refactor invoke as wrapper

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/526)

chore: define try from snapi executable transaction for account tx

---

crates/mempool/src/mempool.rs

rearrange insert_tx func before refactoring code to share code functionality
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/470)

refactor(mempool): rearrange insert_tx before refactoring code

---

crates/mempool/src/mempool.rs
crates/mempool/src/transaction_queue.rs
crates/starknet_api/src/executable_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/439)

feat(mempool): add pending transaction type

---

crates/gateway/src/gateway_test.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/mempool/src/mempool_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/executable_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/544)

test(mempool): enable l2 gas resource for mempool-test

---

crates/gateway/src/gateway.rs
crates/mempool_node/src/components.rs
crates/starknet_sierra_compile/src/config.rs

Per @lev-starkware's suggestion.
We align the inputs of `create_gateway` so that it only gets configs.
This does not collide with our needs for creating the gateway with dependency injection as we can always use the gateway's `new` constructor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/545)

chore: align the inputs of create_gateway to get only configs

---

.github/workflows/main.yml
scripts/run_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/207)

fix(ci): remove redundant --concurrency test run in CI

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/503)

build(fee): define valid resources bounds enum

---

crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

During the function process_tx in the gateway, the compilation (sierra to casm) occurs.
In this PR, we change the compilation's return type from `blockifier::execution::contract_class::ClassInfo` to `starknet_api::contract_class::ClassInfo`.
In the following PRs, `MempoolInput` will (indirectly) use `starknet_api::..::ClassInfo`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/516)

refactor: use snapi class info in process declare tx

---

crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs
crates/gateway/src/rpc_objects.rs
crates/native_blockifier/src/py_state_diff.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/322)

build(blockifier): add l2_gas_price and refactor

---

crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_block_executor_test.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/561)

chore(native_blockifier): convert general config to os config

---

crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/native_blockifier/src/py_objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/559)

chore(blockifier, native_blockifier): update versioned constants

---

crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/gateway/src/rpc_objects.rs
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_state_diff.rs
crates/papyrus_execution/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/463)

build(blockifier): add l2_gas_price to blockinfo

---

crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/starknet_sierra_compile/Cargo.toml
crates/starknet_sierra_compile/src/cairo_lang_compiler.rs
crates/starknet_sierra_compile/src/compile_test.rs
crates/starknet_sierra_compile/src/errors.rs
crates/starknet_sierra_compile/src/lib.rs

The following PR in the stack concerns running the compiler in a process with a binary. I wanted to move some of the uninteresting upkeep to another PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/566)

chore: streamline the error types in starknet_sierra_compile crate

---

crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/482)

feat(mempool): add pending queue to tx queue

---

crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/papyrus_execution/src/lib.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/505)

build(fee): current tx_info holds validResourceBounds

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/context.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/506)

refactor(fee): transaction info creator may fail

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/context.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/507)

refactor(fee): block context creator may fail

---

crates/blockifier/Cargo.toml
crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/379)

chore(blockifier): derive serde for transaction_execution_info

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/stack_trace.rs
crates/blockifier/src/execution/stack_trace_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/624)

chore(blockifier): add with_attr error message

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/stack_trace.rs
crates/blockifier/src/execution/stack_trace_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/630)

test(blockifier): intermediate with_attr error message

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/642)

refactor(blockifier): versioned constant

---

Cargo.lock
crates/starknet_sierra_compile/Cargo.toml
crates/starknet_sierra_compile/build.rs
crates/starknet_sierra_compile/src/build_utils.rs
crates/starknet_sierra_compile/src/command_line_compiler.rs
crates/starknet_sierra_compile/src/compile_test.rs
crates/starknet_sierra_compile/src/errors.rs
crates/starknet_sierra_compile/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/598)

feat: use the starknet-sierra-compile downloaded binary to compile

---

crates/gateway/build.rs
crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/tests-integration/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/599)

feat: use the command line compiler in gateway

---

Cargo.toml
crates/blockifier/Cargo.toml
crates/committer_cli/Cargo.toml
crates/mempool_infra/Cargo.toml
crates/starknet_committer/Cargo.toml
crates/starknet_patricia/Cargo.toml
crates/task_executor/Cargo.toml
workspace_tests/toml_utils.rs
workspace_tests/version_integrity_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/647)

chore: feature activation in crate Cargo.toml files, not workspace

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/692)

chore: update resources for OS with revert log

---

crates/blockifier/src/blockifier/stateful_validator_test.rs
crates/blockifier/src/concurrency/fee_utils_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/execution/stack_trace_test.rs
crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/declare.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/invoke.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/537)

refactor(fee): use valid resource bounds in blockifier

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/context.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/538)

build(fee): tx_context and create_tx_info cannot_fail

---

crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/native_blockifier/src/py_transaction.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/Cargo.toml
crates/starknet_api/src/rpc_transaction.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/547)

refactor(fee): remove more occurnces of resource mapping

---

crates/blockifier/src/test_utils/declare.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/invoke.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/660)

chore: split the inner tx creator in blockifier test utils

---

crates/batcher/src/fee_market.rs
crates/batcher/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/203)

feat(mempool): impl calculate-gas-price according to EIP 1559

---

crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/utils.rs

In this PR we create the `executable_tx`. This will be a member of `MempoolInput`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/517)

refactor: create executable tx in the gateway process_tx

---

crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/776)

test(blockifier): estimate_minimal_gas_vector depends on GasVectorComputationMode

---

crates/blockifier/src/transaction/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/796)

fix(blockifier): remove the gas word following the resource name in errors

---

crates/tests-integration/tests/end_to_end_test.rs

Test is unstable, the funding of deploy txs isn't working properly, and the test is only passing "by chance".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/840)

fix(tests-integration): disable e2e

---

crates/papyrus_node/src/main.rs
crates/papyrus_node/src/main_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/860)

refactor(node): convert storage metrics handle to the desired task type

---

crates/papyrus_protobuf/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/842)

chore(protobuf): provide an indicative message on protoc prebuilt error

---

crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/bouncer_test.rs
crates/blockifier/src/concurrency/flow_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/760)

test: move nonce storage_key and compiled_class_hash macros to starknet api test utils

---

crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/861)

refactor(node): move building the sync client to its own function

---

crates/gateway/src/config.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/gateway/src/utils.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

In this PR we change the inputs for the `run_validate` method of the stateful validator. This also streamlines `process+tx`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/519)

refactor: refactor the stateful tx validator to get executable tx as input

---

crates/papyrus_protobuf/src/converters/event_test.rs

This fixes a couple of lines in `papyrus_protobuf/src/converters/event_test.rs` that I accidentally changed in a previous PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/847)

fix: revert event test

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/lib.rs

commit-id:19ed8b4a
---
**Stack**:
- #869
- #856
- #855
- #849 ⬅

refactor(base_layer): remove unnecessary option + dep

---

crates/papyrus_node/src/main.rs

This fairly generic return type should allow for flexibility with test overrides.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/870)

refactor(node): spawned tasks should all return anyhow result

---

crates/papyrus_monitoring_gateway/src/lib.rs
crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/871)

refactor(node): refactor how monitoring server is spawned

---

crates/papyrus_node/src/main.rs
crates/papyrus_node/src/main_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/885)

refactor(node): introduce PapyrusTaskHandles to hold task overrides

---

crates/papyrus_node/src/main.rs

Also moved build_network_manager function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/873)

refactor(node): split run from main, as it will be used by many binaries

---

Cargo.lock
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs

- implement the TODO for adding types to the Config, rather than working
with raw strings.
- using `Url` for url and **re-exporting** `alloy`'s `Address` type in order
to not externalize this implementation detail type unnecessarily.
- Remove 2 errors that are now no longer the responsibility of this
module, the callsite will have to handle the casting into the correct
types.
commit-id:0a043060
---
**Stack**:
- #869
- #856
- #855 ⬅

feat(base_layer): add types to config

---

crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs

commit-id:a4bb6349
---
**Stack**:
- #869
- #856 ⬅

feat(base_layer): add safe conversion to felt

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/889)

refactor(mempool): add tx! macro

---

crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/starknet_api/src/executable_transaction.rs

The struct `ValidateInfo` holds all the information relevant to the rest of the transaction's lifecycle from the run of the validate. Most of its members are no longer needed as they can be obtained from the `ExecutableTransaction`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/521)

refactor: remove most fields from statful validator output

---

crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/822)

refactor: add account nonce as input of run_validate and remove validation output

---

crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/lib.rs
crates/papyrus_sync/src/sources/base_layer.rs

No finality is equivalent to passing finality 0.
commit-id:2f82d223

refactor(base_layer): remove optional finality

---

Cargo.lock

I think the merge conflict originated from this commit @yair-starkware 
commit e428a6b2db743ad801e11df8063ef25ee78f0c82 (HEAD)
Author: Yair Bakalchuk <yair@starkware.co>
Date:   Mon Sep 9 12:51:53 2024 +0300
feat(batcher): batcher client trait
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/942)

fix: fix cargo.lock after merge conflict

---

crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/733)

feat(consensus): add locked_value to sm

---

crates/batcher/src/proposals_manager.rs
crates/batcher/src/proposals_manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/790)

refactor(batcher): refactor proposal manager

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/966)

refactor(mempool): rename MempoolContent methods to use tx abbreviation

---

crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/800)

chore(concurrency): store the state diff instead of the writes

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/resources/versioned_constants_13_0.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/versioned_constants.rs
crates/native_blockifier/src/py_state_diff.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/846)

fix(blockifier): enforce fee for allresourcebounds when l1 gas is 0

---

crates/sequencing/papyrus_consensus/src/bin/run_simulation.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/880)

refactor(consensus): minor refactor for how the log and db dirs are created and passed

---

crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/710)

chore(blockifier): check max price of l1_data_gas and l2_gas

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/999)

chore: reinstall stable rust toolchain

---

crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs
crates/mempool_types/src/mempool_types.rs

Part of a larger refactor.
**Starting point:** 
Two separate structs:
- AccountState (contains a nonce field)
- Account (contains sender_address and AccountState)
**Target:**
Merge into one struct, AccountState, containing two fields: sender_address and account_nonce.
**Current state:**
- AccountNonce (contains a nonce field)
- Account (contains sender_address and AccountState)
_**Please start by reviewing the mempool_types.rs file first.**_
**Stack of PRs:**
1. refactor(mempool): rename account state to account nonce #957 **<-- you're here**
2. refactor(mempool): rename account to account state #959
3. refactor(mempool): merge AccountNonce into AccountState #963
4. refactor(mempool): remove AccountNonce struct #965
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

refactor(mempool): rename account state to account nonce

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

Hashmap with int keys, where keys are not removed, is better described as a vector and has better performance.
In other words, a hashmap was simply an incorrect DS here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1006)

refactor(tests-integration): switch hashmap to vec

---

crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs
crates/mempool_types/src/mempool_types.rs

Part of a larger refactor.
**Starting point:**
Two separate structs:
- AccountState (contains a nonce field)
- Account (contains sender_address and AccountState)
**Target:**
Merge into one struct, AccountState, containing two fields: sender_address and account_nonce.
**Current state:**
- AccountState (contains sender_address and nonce)
- AccountNonce (contains nonce)
_**Please start by reviewing the mempool_types.rs file first.**_
**Stack of PRs:**
1. refactor(mempool): rename account state to account nonce #957
2. refactor(mempool): rename account to account state #959 
3. refactor(mempool): merge AccountNonce into AccountState #963 **<-- you're here**
4. refactor(mempool): remove AccountNonce struct #965
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

refactor(mempool): merge AccountNonce into AccountState

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_block_executor_test.rs
crates/papyrus_execution/src/state_reader_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/910)

chore: create try from referance of casm contract class method

---

Cargo.lock
crates/mempool_test_utils/Cargo.toml
crates/mempool_test_utils/src/starknet_api_test_utils.rs

Account variants need to keep track of their own address, so that future txs can use that address to generate new txs.
Currently unused, will replace `FeatureContract` in all tests-integration usages, instead of current usage of `get_instance_address`, which generates incorrect addresses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1010)

feat: add state to FeatureContract via wrapper

---

crates/blockifier/src/transaction/execution_flavors_test.rs

feat(starknet_api): chain gas prices hash (#962)
feat: add publish crates script (#893)
feat: implement unpublished crates verification (#894)
test(mempool): add TransactionQueueContent[Builder] (#967)
refactor(blockifier): unavailable contract address error (#970)
feat(blockifier): replace TryFrom<&Path> for VC with ad-hoc function (#973)
feat(consensus): add active_proposals to context
chore(concurrency): store the state diff instead of the writes (#800)
feat(consensus): shc handle sm proposal
feat(batcher): mock BlockBuilder for tests
feat(mempool_infra): add serde utils
commit-id:93bc459d
chore(mempool_infra): wrap serde operations with generic custom struct towards binary serde
commit-id:325d0501
chore(ci): tune boostraping cache (#949) …

feat(starknet_api): chain gas prices hash (#962)

---

Cargo.lock
crates/tests-integration/Cargo.toml
crates/tests-integration/src/state_reader.rs

Changes:
- use papyrus test util to create storage
- hoist cairo0 var definition away from the storage stuff
style:
- use annotation instead of fish in the cairo0 var
- deref coercion over `as_slice`, more succinct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1014)

refactor(tests-integration): refactor state reader

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool_types/src/mempool_types.rs

Part of a larger refactor.
**Starting point:**
Two separate structs:
- AccountState (contains a nonce field)
- Account (contains sender_address and AccountState)
**Target:**
Merge into one struct, AccountState, containing two fields: sender_address and account_nonce.
**Current state:**
- AccountState (contains sender_address and nonce)
_**Please start by reviewing the mempool_types.rs file first.**_
**Stack of PRs:**
1. refactor(mempool): rename account state to account nonce #957
2. refactor(mempool): rename account to account state #959 
3. refactor(mempool): merge AccountNonce into AccountState #963 
4. refactor(mempool): remove AccountNonce struct #965 **<-- you're here**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

refactor(mempool): remove AccountNonce struct

---

crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/997)

test(blockifier): max gas price for new resource bounds

---

crates/tests-integration/src/state_reader.rs

This seems to be stale, as funding this account doesn't seem to be necessary.
Rationale: the address this outputs is one generated by FeatureContract, which we now know is not really used by subsequent invokes. This functionality is now ensured through the FeatureAccount mechanism.
Note: the e2e test is currently disabled so this can't be verified yet, but in the next few commits it will be enabled and it can be verified that indeed this is unnecessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1015)

refactor(tests-integration): remove uneeded arg

---

crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/994)

refactor(blockifier): split pre validate test by charge fee

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

Revert Transaction Generator Changes in `invoke_tx` Function
This PR reverts changes made to the one-shot `invoke_tx` function in commit 09efafe449e23f8c5c8b0fbd240bce6d29e4190b.
Reason for Reversion:
The `invoke_tx` function is currently only used in `gateway_test`, which relies on a local state setup with a specific funding scheme. This scheme is incompatible with the `MultiAccountTransactionGenerator`.
Technical Details:
1. The current implementation in `gateway_test` depends on each transaction using a generated address through `FeatureContract`.
2. This address is specifically funded for each transaction.
3. The `MultiAccountTransactionGenerator` requires multiple transactions from the same account to have a consistent address.
4. The `FeatureContract` addressing system does not …

fix: undo invoke_tx usage of transaction generator

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/229)

refactor(transaction): add common getters to transaction

---

crates/blockifier_regression_test/src/test_state_reader.rs
crates/gateway/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/946)

build: blockifier regression test add block info

---

crates/tests-integration/tests/end_to_end_test.rs

Not supported yet, we need to be able to execute in batcher and close blocks before we can do anything interesting here.
Specifically, invokes won't pass the GW until an account is deployed, so until we can expicitely close blocks we can't use deploys and invokes inside the same test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1050)

fix(tests-integration): remove deploy from e2e

---

crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/996)

refactor(blockifier): remove constant from pre validate test

---

crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_rpc/src/v0_8/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/644)

feat(execution): add l2_gas_price to FeeEstimation

---

Cargo.lock
crates/blockifier_regression_test/Cargo.toml
crates/blockifier_regression_test/src/lib.rs
crates/blockifier_regression_test/src/test_utils.rs
crates/papyrus_execution/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/948)

build: blockifier regression test add get fee token addresses

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

- `DeployAccountTransaction`s cannot possibly be constructed through the `AccountTransactionGenerator`, since the generator will soon needs a deploy account tx in its constructor, to ensure consistent sender ad dresses for the account.
- Added salt, will also be needed later.
- Removed unused `deploy_account_tx` function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1052)

fix(tests-integration): deploy tx constructors

---

crates/gateway/src/rpc_objects.rs
crates/gateway/src/rpc_state_reader_test.rs
crates/papyrus_rpc/resources/V0_8/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_8/api/api_impl.rs
crates/papyrus_rpc/src/v0_8/api/test.rs
crates/papyrus_rpc/src/v0_8/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/652)

feat(mempool): add l2_gas_price support in BlockHeader

---

crates/papyrus_node/src/bin/run_consensus.rs
crates/papyrus_node/src/bin_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/925)

refactor(node): users pass the prefix for splitting config args

---

crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/918)

chore(blockifier): added tests for StarknetResources::to_gas_vector

---

Cargo.lock
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/state_reader.rs

Use `FeatureAccount` in the flow test state reader. This fixes the longstanding bug of relying on
`FeatureContract::get_instance_address`, which generates mocked addresses for accounts, rather than ones derived from deploy account txs, which is how addresses are determined in Feature Acconuts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1061)

fix(tests-integration): feature account in state

---

crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/927)

chore(blockifier): added tests for get_vm_resources_cost

---

Cargo.lock
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/src/state_reader.rs

Separate **accounts** defined inside the flow test, **test contracts** that are assumed to exist on the network, and a single ERC20 contract assumed to also exist.
Each of these contract types is treated slightly differently, hence they should not be mixed together.
Note: this commit is only about splitting the contracts, with as little code changes as possible.
An upcoming abstraction will make this a bit more maintainable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1062)

refactor(tests-integration): split contracts

---

crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1070)

refactor(blockifier): remove constant from mid execution test

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/test_utils/transfers_generator.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1106)

style(blockifier): avoid repetition in Transaction variant names

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1104)

fix(blockifier): remove &self arg from AccountTransaction::handle_fee

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/878)

chore(mempool): move account nonces update check to add tx test

---

crates/tests-integration/src/state_reader.rs

Extract deploy/declare/fund into dedicated builder.
Different contracts/accounts each need different handling in terms of
those three actions, and a logical split allows for easier debugging
during testing (from experience...).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1063)

refactor(tests-integration): state diff builder

---

crates/tests-integration/src/state_reader.rs

When injecting a deployed account into the state, its nonce must be > 0, since this injection simulates a deploy-account being added to the state, which must therefore bump the nonce to 1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1064)

fix(tests-integration): bump nonces in state

---

crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1093)

feat(blockifier): impl From AccountTransaction variants for Transaction

---

crates/mempool_node/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1126)

chore: add build file to mempool_node to allow usage of starknet_sierra_compile crate

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1118)

feat(blockifier): update assert_actual_fee_in_bounds and add test

---

crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/mempool/src/communication.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool_types/src/communication.rs
crates/mempool_types/src/mempool_types.rs

For consistency with CommitBlockArgs;
MempoolInput is a stale name (was given back when it was the single input to the mempool).
This PR is a rename only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1147)

refactor(mempool): rename MempoolInput to AddTransactionArgs

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

This constructor name hints better that its only useful for accounts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1123)

refactor(mempool_test_utils): rename constructor

---

crates/mempool/Cargo.toml
crates/mempool/src/mempool_test.rs
crates/mempool/tests/flow_test.rs

Also renamed "hole[s]" to "nonce_gap[s]".
Code move only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1189)

test(mempool): move flow tests to tests/flow_test.rs

---

crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/integration_test_utils.rs
crates/tests-integration/src/state_reader.rs

HACK: until we setup state sync between storages, we're going to take the storage generated by the storage_reader generator, copy the file, and feed it to the batcher config.
This is an ugly way of initializing the batcher and GW with the same state.
TODO: Once we have state sync, remove this stuff and replace with initializing the batcher with the updated state, then having the gw state sync from it.
NOTE: also added tempdir file handler to `IntegrationTestSetup` while i'm at it, it's required by papyrus_storage to prevent deallocation of the file (this should be fixed inside papyrus_storage so that this issue is hidden from the users).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix(tests-integration): copy gateway storage

---

crates/mempool_node/src/main.rs
crates/mempool_node/src/servers.rs

Also minor refactor of get_server_future
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1141)

fix(mempool_node): don't drop component clients when running servers

---

crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/811)

test(blockifier): insufficient amount new resource bounds

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/tests/end_to_end_test.rs

We'll always want to specify the tip for invokes, even if it's initialized with default fields.
Also hoist up `nonce` and `tip` fields in constructor, they are more important than the others initialized with test values.
Currently still using trivial values in the e2e test, will soon make it interesting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1203)

feat(tests-integration): add tip to invoke gen

---

crates/mempool/src/mempool_test.rs

Will move to `/tests/flow_test.rs` next PR, for an easy diff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1218)

test(mempool): convert a test into a proper flow test

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1198)

feat(consensus): make the fields of BroadcastTopicClient public, used for test construction

---

Cargo.lock
crates/batcher/Cargo.toml
crates/batcher/src/batcher.rs
crates/batcher/src/block_builder.rs
crates/batcher/src/lib.rs
crates/batcher/src/papyrus_state.rs
crates/batcher/src/proposal_manager.rs
crates/batcher/src/proposal_manager_test.rs
crates/batcher_types/Cargo.toml
crates/batcher_types/src/batcher_types.rs
crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/745)

feat: adding block_builder object

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/utils.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1174)

refactor(blockifier): resource cost ratio type changed to u64 ratio from u128 ratio

---

crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/968)

chore(blockifier): added regression test for gas computation

---

config/mempool/default_config.json
crates/gateway/src/config.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/tests-integration/src/integration_test_utils.rs

The `ChainInfo` is a part of the config that is relevant not only to the stateful validator but also to the conversion `RpcTransaction` -> `ExecutableTransaction`. In this PR we move this config to be a part of the `GatewayConfig`. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/520)

refactor: share the chain info as a config for the gateway

---

crates/mempool/src/transaction_pool.rs

To be used in `commit_block` to restore non-included transactions in queue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1257)

feat(mempool): add account_txs API to TransactionPool

---

crates/committer_cli/src/tests/utils/objects.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_protobuf/src/converters/receipt.rs
crates/papyrus_rpc/src/v0_8/transaction.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/src/block_hash/test_utils.rs
crates/starknet_api/src/execution_resources.rs
crates/starknet_client/src/reader/objects/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1176)

refactor(starknet_api): gas vector to contain fields of type GasAmount

---

crates/blockifier/src/execution/stack_trace.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1269)

feat(blockifier): make ErrorStack fields public

---

config/mempool/default_config.json
crates/mempool_node/src/config/mod.rs

commit-id:24ddd75d
---
**Stack**:
- #1265
- #1285 ⬅

fix(mempool_node): fix gateway config to point to chain_id

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1289)

feat(blockifier): saturate block step bound in max_steps

---

.github/workflows/main.yml
crates/blockifier/src/execution/native.rs
crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/native/utils.rs
crates/blockifier/src/execution/native/utils_test.rs

Recration of #1157 targeting Main
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1240)

feat(blockifier): add `NativeSyscallHandler`

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/test_utils.rs
crates/mempool/tests/flow_test.rs

This Pr simplifies the calls the macros, by hiding the imports inside the macro. The question is: Does this change hurt performance? Do repeated imports processed separately each time?
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1317)

chore: use the imports inside the macro in mempool test utils

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/blockifier/transaction_executor.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/execution/stack_trace_test.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/793)

chore(blockifier): have charge_fee flag represent enforce_fee return value

---

Cargo.lock
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/resources.rs
crates/starknet_api/Cargo.toml
crates/starknet_api/src/execution_resources.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1280)

feat(blockifier): panic on GasVector arithmetic overflow

---

crates/consensus_manager/src/consensus_manager.rs
crates/mempool_p2p/src/receiver/test.rs
crates/mempool_p2p/src/sender/test.rs
crates/mempool_p2p_types/src/communication.rs
crates/mempool_types/src/communication.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/network_manager/test_utils.rs
crates/papyrus_network_types/src/network_types.rs
crates/papyrus_network_types/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs
crates/sequencing/papyrus_consensus/src/stream_handler.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1144)

refactor(network): rename BroadcastedMessageManager to BroadcastedMessageMetadata

---

Cargo.lock
crates/tests-integration/Cargo.toml
crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/tests/end_to_end_test.rs

This PR conflicts with #1296.
In this PR we do not create a mock consensus manager but add the least amount of code to allow us to add the batcher to the flow test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1352)

test: add batcher client to sequencer end_to_end_test

---

Cargo.lock
crates/gateway_types/Cargo.toml
crates/gateway_types/src/gateway_types.rs

- refactor(network): rename BroadcastedMessageManager to BroadcastedMessageMetadata
- fix(gateway): change gateway types to use the correct message metadata struct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1357)

fix(gateway): change gateway types to use the correct message metadata struct

---

crates/mempool/src/mempool.rs
crates/mempool/src/suspended_transaction_pool.rs
crates/mempool/src/transaction_pool.rs
crates/mempool/src/transaction_queue.rs
crates/mempool/src/transaction_queue_test_utils.rs

Shorter name is preferable, and equivalently understandable; rename only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1413)

refactor(mempool): rename TransactionReference field sender_address -> address

---

crates/blockifier/src/blockifier/stateful_validator_test.rs
crates/blockifier/src/concurrency/fee_utils_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/execution/stack_trace_test.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1306)

refactor(blockifier): refactor default testing resource bounds

---

crates/blockifier/src/blockifier/stateful_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1307)

test(blockifier): add all resource bounds to stateful validator test

---

crates/sequencing/papyrus_consensus/src/stream_handler.rs

Change the text in the warnings in StreamHandler to use the key `(peer_id, stream_id)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1421)

feat: use key in text of warning message of StreamHandler

---

crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/991)

feat(network): blacklist peers after a threshold of malicious activities has been reached

---

crates/blockifier/src/concurrency/versioned_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1308)

test(blockifier): l1 bounds -> all bounds in versioned state test

---

crates/blockifier/src/concurrency/worker_logic_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1309)

test(blockifier): l1 bounds -> all bounds in worker logic test

---

crates/sequencing/papyrus_consensus/src/stream_handler.rs

We change the loop in the `run()` function to use a `select` instead of an `await` so that we can later add the outbound flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1417)

feat: add select to StreamHandler::run() function

---

crates/blockifier/src/execution/stack_trace_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1310)

test(blockifier): l1 bounds -> all bounds in stack trace test

---

crates/gateway/src/communication.rs
crates/gateway/src/gateway_test.rs
crates/gateway_types/src/errors.rs
crates/papyrus_network_types/src/network_types.rs

- **feat(gateway): gateway passes p2p metadata in add_tx**
- **feat(gateway): gateway returns p2p metadata inside error in add_tx**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1404)

feat(gateway): gateway returns p2p metadata inside error in add_tx

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/papyrus_execution/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/833)

chore(blockifier): have limit_steps_by_resources flag rep charge_fee flag and enforce_fee ret val

---

crates/papyrus_rpc/src/v0_8/api/test.rs
crates/papyrus_storage/src/header_test.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/src/block.rs
crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_test.rs
crates/starknet_api/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1376)

feat(starknet_api): the StarknetVersion type is now an enum

---

crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/blockifier_reexecution/src/state_reader/errors.rs
crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs
crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
crates/native_blockifier/src/lib.rs
crates/papyrus_execution/src/lib.rs
crates/starknet_api/src/block.rs
crates/starknet_api/src/block_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1378)

refactor(blockifier, starknet_api): delete blockifier's StarknetVersion

---

crates/mempool/src/mempool_test.rs

Removing a redundant test.
`test_get_txs_replenishes_queue_only_between_chunks` cover the tested scenario.

refactor(mempool): remove a redundant get-txs test

---

.github/workflows/main.yml
Cargo.lock
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/native.rs
crates/blockifier/src/execution/native/entry_point_execution.rs
crates/blockifier/src/execution/native/utils.rs
crates/blockifier/src/execution/native/utils_test.rs

This is a newer version of #622 (which was a copy of #551) with addressed comments and updated git history.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1158)

feat(blockifier): add entry point execution logic for native

---

crates/gateway_types/src/errors.rs
crates/monitoring_endpoint/src/config.rs
crates/papyrus_config/src/validators.rs
crates/papyrus_monitoring_gateway/src/lib.rs
crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/v0_8/transaction.rs
crates/papyrus_rpc/src/version_config.rs
crates/papyrus_storage/src/version.rs
crates/starknet_api/src/block.rs
crates/starknet_api/src/crypto/utils.rs
crates/starknet_api/src/transaction.rs
crates/starknet_client/src/starknet_error.rs
crates/starknet_patricia/src/felt.rs

To disambiguate from derive_more::Display.

refactor: use fully-qualified std::fmt::Display trait

---

.cargo/config.toml
.github/workflows/committer_ci.yml
scripts/dependencies.sh

We've recently taken to limit parallelism during builds due to Out Of Memory errors we got while running `cargo test` on 16-core machine, or 8-core machines running with `-j16`.
We hit OOM due to two reasons:
1. Commit fae5aed7bc94a60f1e01e0a6ceb4c1035ecdadbc introduced `llvm` dependencies to the blockifier, which notably increased compilation and linking time.
2. Before fae5aed7bc94a60f1e01e0a6ceb4c1035ecdadbc, we already had a quite memory-heavy linking stage, specifically ~7-8 `ld` instances running in parallel, each with ~2-3GB of memory, which was just enough not to hit OOM on most 16core machines.
This was primarily due to a combination of factors:
2.1 the blockifier being a large lib that needs a 2-3GB `ld` process
to link in isolation.
2.2 many crates have the blockifier as a …

fix: switch `ld` with `lld` on linux, fixes OOM

---

.cargo/config.toml
Cargo.lock
Cargo.toml
scripts/dependencies.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1241)

feat(blockifier): update cairo native to 0.2.0-alpha.2

---

Cargo.lock
crates/mempool/Cargo.toml
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool_types/src/mempool_types.rs
crates/starknet_api/src/core.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1428)

chore(mempool): add logs to mempool logic

---

crates/mempool_infra/src/component_server/definitions.rs
crates/mempool_infra/src/component_server/local_component_server.rs

commit-id:1ade9262
---
**Stack**:
- #1502
- #1501
- #1499
- #1492 ⬅

chore(mempool_infra): server tracing

---

crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/invoke.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1073)

chore: align the tx_hash parameter in the account tx creator test util

---

config/mempool/default_config.json
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/native_blockifier/src/py_objects.rs

I plan to make PyVersionedConstantsOverrides fields optional as well.

refactor(blockifier): make VersionedConstantsOverrides fields optional

---

scripts/dependencies.sh

It is essential for our linux env, otherwise linking won't work.

fix: move `lld` installation

---

config/mempool/default_config.json
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/native_blockifier/src/py_objects.rs

This reverts commit 451a444896985a655f81037b6f413ae56cf16307.

refactor(blockifier): revert change to VersionedConstantsOverrides

---

scripts/clippy.sh

- `unwrap_used` is already allowed by default and not denied explicitly in any crate.
- the tracing bug in question has been fixed last month.

chore(ci): delete unused lints

---

crates/blockifier/src/execution/native/entry_point_execution.rs
crates/blockifier/src/execution/native/syscall_handler.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1380)

refactor(blockifier): native syscall handler  `new` method params

---

crates/mempool/src/communication.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/tests/flow_test.rs

Also, remove `Mempool::empty` c-tor; so that constructing a default mempool is explicit.

chore(mempool): implement explicit `Default` for mempool

---

Cargo.toml

Unused is `warn` by default so the subsequent `warnings = "deny"` covers this case.

chore: remove unnucessary lint

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1311)

test(blockifier): test enforce_fee flag with new resource bounds

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1312)

test(blockifier): l1 bounds -> all bounds (or parametrize) in account transaction test

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

Moving `fee_escalation_percentage` into `MempoolConfig` and adding an `enable_fee_escalation` field to control when escalation applies. Updating test util's config to be non-optional, with fee escalation disabled by default.

feat(mempool): impl MempoolConfig

---

crates/mempool/src/mempool.rs
crates/mempool/src/transaction_pool.rs
crates/mempool_types/src/errors.rs

More direct error type.
Also removed TODOs, we don't need all of SNAPI error if only this error is possible.
Side-note: we are assuming that try_increment only fails due to addition overflow, but in the future that might not be the case, though i doubt this edge case will occur and is worth `match`ing the actual error variant we get from SNAPI.

chore(mempool): add nonce increment error

---

crates/mempool/src/lib.rs
crates/mempool/src/mempool.rs
crates/mempool/src/transaction_pool.rs
crates/mempool/src/utils.rs
crates/mempool/tests/flow_test.rs
crates/mempool_types/src/errors.rs

`mempool_state` had off-by-one error, where the current state was saved instead of the next nonce state. That is, we are eagerly assuming all txs sent to the batcher have been accepted.
Also added util for cast nonce errors and used everywhere (the use everywhere part can be split off to new PR if you prefer).

fix(mempool): bump nonce before saving in state

---

crates/blockifier_reexecution/resources/raw_rpc_json_objects/transactions.json
crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs
crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs
crates/blockifier_reexecution/src/state_reader/serde_utils.rs

test: blockifier reececution test getting deploy account tx with rpc
build: blockifier reexecution add support for declare tx

test(blockifier_reexecution): add support for declare and deploy account tx with rpc

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1313)

test(blockifier): update test_insufficient_max_fee_reverts to include new resource bounds

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/stack_trace_test.rs
crates/blockifier/src/transaction/post_execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1314)

test(blockifier): update test_revert_on_resource_overuse to include new resource bounds

---

crates/blockifier/src/concurrency/fee_utils.rs
crates/blockifier/src/fee/receipt.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/835)

refactor(blockifier): remove enforce fee from actual fee

---

crates/mempool_p2p/src/runner/mod.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs

The name "broadcasted message manager" has changed to "broadcasted message metadata". I've updated a few places where the variable names were not updated to reflect this.

chore: rename broadcasted_message_manager to _metadata

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/execution_resources.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/764)

test(blockifier): max fee exceeds balance errors on new resource bounds

---

config/papyrus/default_config.json
crates/mempool_node/src/config/node_config.rs
crates/papyrus_config/src/config_test.rs
crates/papyrus_config/src/dumping.rs
crates/papyrus_config/src/lib.rs
crates/papyrus_node/src/config/pointers.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/run_test.rs
crates/papyrus_sync/src/sources/central.rs
crates/papyrus_sync/src/sources/pending.rs

chore(config): rename central url field
chore(config): add explicit usage of field separator
chore(config): set pointer targets based on target name
chore(config): clear explicit pointer vectors
commit-id:1e620e99
---
**Stack**:
- #1701
- #1692 ⬅

chore(config): rename pointer test params according to new convention

---

crates/mempool/src/mempool_test.rs

The test is already covered `test_add_tx_delete_tx_with_lower_nonce_than_account_nonce` test.

refactor(mempool): remove redundant add-tx test

---

crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1321)

test(blockifier): parametrize test_invoke_tx by resource bounds types

---

crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1322)

test(blockifier): parametrize test_max_fee_exceeds_balance by resource bounds types

---

crates/mempool_node/src/config/config_test.rs
crates/mempool_node/src/config/node_config.rs
crates/papyrus_proc_macros/src/lib.rs

commit-id:901f3b1a
---
**Stack**:
- #1725
- #1710
- #1709
- #1708
- #1707
- #1706 ⬅
- #1701

feat: add macro to derive struct field names

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1382)

refactor(execution): delete starknet version string constants and usages

---

crates/mempool/src/mempool_test.rs
crates/mempool/tests/flow_test.rs

This test is flow-specific, hence must be tested in a flow test. Specifically, this tests behavior when the mempool is in "validate mode" which isn't supported yet.
Note: removed from the test the behavior where commit block decreased the known account nonce, which had two bugs:
1. commit_block from a different leader reduced the account nonce, this is a reorg and isnt unsupported yet, and when it is, it would use a dedicated API test.
2. it decreased the nonce back to 0, which doesn't make sense because at least one tx must have been accepted in a block --- also fixed a similar issue in a separate flow.
Will add an assert in commit_block on minimum nonce being 1 in subseuqent commits.
There will also be a subsequent commit that decreases the nonces in …

chore(mempool): convert unit to flow test

---

crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1330)

test(blockifier): parametrize test_actual_fee_gt_resource_bounds by resource bounds types

---

crates/mempool/src/mempool_test.rs

This test is already covered by `test_add_tx_multi_nonce_success`. Both tests verify that adding sequential nonces includes the latter transaction in the pool.

refactor(mempool): remove test_add_tx_sequential_nonces redudant test

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test_utils.rs

- **feat(common): move find_free_port to papyrus_common and add find_n_free_ports**
- **test(network): add test utility to create network config connected to broadcast channels**

test(network): add test utility to create network config connected to broadcast channels

---

crates/papyrus_network/src/lib.rs
crates/sequencing/papyrus_consensus/src/stream_handler.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs

This adds the other communications direction, e.g., from the Consensus into the network.
The StreamHandler gets a receiver of receivers (well, actually it gets a tuple with stream_id and a receiver).
Each new receiver corresponds to a new stream_id (in the Consensus case it would be a new height).
Then, messages that come in the form of generic T (can be any protobuf-able message) are packaged into StreamMessage and sent out to the network.
When the Fin message comes, the receiver channel is dropped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1402)

feat: add broadcasting to StreamHandler

---

crates/mempool/src/mempool_test.rs

- I updated `with_fee_escalation_percentage` to set config directly, making it more idiomatic by creating a new `MempoolConfig` with only necessary overrides, keeping others unchanged (we can add `..self.config` if more fields are added).
- Adding a `MempoolConfigBuilder` feels unnecessary for now since the config is being updated only in `with_fee_escalation_percentage.` We can revisit a builder if more unrelated functions are added later.

refactor(mempool): update MempoolConfig test util

---

crates/blockifier/src/concurrency/fee_utils_test.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1342)

test(blockifier): migrate remaining tests to all resource bounds (except execution flavors test)

---

crates/batcher_types/Cargo.toml
crates/consensus_manager/Cargo.toml
crates/mempool_test_utils/Cargo.toml
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_config/Cargo.toml
crates/papyrus_load_test/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network_types/Cargo.toml
crates/papyrus_proc_macros/Cargo.toml
crates/sequencing/papyrus_consensus_orchestrator/Cargo.toml
crates/starknet_client/Cargo.toml

All crates not inheriting from workspace lints fail the workspace lints and will be handled separately.
Motivation: consistent linting across project and in the CI.

chore: add free inherit lints in crates

---

crates/batcher_types/Cargo.toml
crates/consensus_manager/Cargo.toml
crates/mempool_test_utils/Cargo.toml
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_common/Cargo.toml
crates/papyrus_common/src/python_json.rs
crates/papyrus_config/Cargo.toml
crates/papyrus_load_test/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network_types/Cargo.toml
crates/papyrus_proc_macros/Cargo.toml
crates/sequencing/papyrus_consensus_orchestrator/Cargo.toml
crates/starknet_client/Cargo.toml

Nearly all `as` uses can be replaced with `[Try]From` which doesn't have implicit coercions like `as` (we encountered several bugs due to these coersions).

chore: add lints to papyrus_common

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/test_utils.rs

I've clustered the arguments by subjects: tx_hash which identifies the transaction, then address which identifies the user, then all that has to do with nonces tx_nonce, account_nonce, then bid-related tip, max_l2_gas_price, etc.

refactor(mempool): cluster add tx input macro inputs by subjects

---

crates/gateway/src/stateless_transaction_validator_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

I removed the function and used default directly, as it no longer adds value beyond calling the default implementation.

refactor(gateway): remove wrapper function

---

crates/papyrus_config/src/config_test.rs
crates/papyrus_config/src/dumping.rs
crates/papyrus_config/src/lib.rs
crates/papyrus_node/src/bin/papyrus_dump_config.rs
crates/papyrus_node/src/config/config_test.rs
crates/papyrus_node/src/config/pointers.rs
crates/sequencer_node/src/bin/sequencer_dump_config.rs
crates/sequencer_node/src/config/config_test.rs
crates/sequencer_node/src/config/node_config.rs

commit-id:73b9f196
---
**Stack**:
- #1786
- #1776 ⬅
- #1775

chore(config): avoid using macro to enable formatter

---

.cargo/config.toml
.github/workflows/blockifier_ci.yml
.github/workflows/main.yml
.gitignore
.gitmodules
Cargo.toml
crates/blockifier/build.rs
scripts/dependencies.sh
scripts/sequencer-ci.Dockerfile
taplo.toml

Add the Cairo Native runtime binary to the root after executing `./scripts/dependencies.sh`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1242)

feat(blockifier): compile cairo native runtime

---

crates/papyrus_execution/Cargo.toml
crates/papyrus_execution/src/objects.rs

chore(execution): add workspace lints

---

crates/papyrus_config/src/dumping.rs
crates/papyrus_node/src/config/pointers.rs
crates/sequencer_node/src/config/node_config.rs

chore(config): ensure no duplicated config pointer params

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue_test_utils.rs

This PR implements a test that checks that get_txs does not return pending transactions, transactions with gas price below the gas price threshold.

test(mempool): imp test-get-txs-returns-only-priority-txs

---

crates/mempool/src/mempool_test.rs

Since we implemented with_pending and with_priority, this code is now unused. 
The insertion logic here is unclear, as the gas price threshold may be uninitialized.

refactor(mempool): mempool content remove unused code

---

crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/network_manager/mod.rs

Note: i left the `as f64` since `gauge!` expects f64, even though the metrics themselves are integers. This is probably fixable by using `counter!` instead of `gauge!`, but i haven't found anyone who knows how to test these metrics so i'm leaving it for now.
I left the "clippy ignore" at the statement level intentionaly, instead of the module level, so that it won't be forgotten.

chore(network): add workspace lints to network

---

crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_node/Cargo.toml
crates/papyrus_node/examples/get_transaction_hash.rs
crates/papyrus_node/src/config/pointers.rs

chore(node): add workspace lints

---

crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_p2p_sync/src/server/test.rs

Changes:
1. header/state_diff: added clippy ignore to `gauge!` metric usage which requires f64. This is probably unnecessary since metrics used are int values, but fixing this is out of scope, and there are no other sensible conversions from unsigned to floats.
2. test.rs: most usages of these two vars were for usize, and only a couple needed u64, so i flipped the usages.

chore: add lint to p2p_sync

---

crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_p2p_sync/src/server/utils.rs

Add workspace lints, which in particular ban `as` usage.
Changes:
1. switch `as` into `From` when applicable.
2. replace the conditional+cast with [equivalent](https://github.com/rust-lang/rust/blob/master/library/core/src/convert/num.rs#L277) logic `u64::try_from`.

chore: add lints to p2p-sync

---

crates/papyrus_test_utils/Cargo.toml
crates/papyrus_test_utils/src/lib.rs

chore: add lints to papyrus_test_utils

---

crates/papyrus_rpc/Cargo.toml
crates/papyrus_rpc/src/v0_8/api/test.rs
crates/papyrus_rpc/src/v0_8/execution_test.rs
crates/papyrus_rpc/src/v0_8/transaction.rs

Nearly all as uses can be replaced with [Try]From which doesn't have implicit 
coercions like as (we encountered several bugs due to these coercions).
Motivation: we are standardizing lints across the repo and CI, instead of each 
crate having separate sets of lints.

chore: add lints to rpc

---

crates/starknet_api/Cargo.toml
crates/starknet_api/src/core.rs
crates/starknet_api/src/deprecated_contract_class.rs

chore: starknet API add lints

---

crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/bin/run_simulation.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs

chore(consensus): add lints to consensus

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/test_instances.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs

Currently there is a `ProposalInit` struct in both `papyrus_protobuf` and in the `papyrus_consensus` crates. I've killed the latter and kept the former.

chore: unify the two types of ProposalInit structs

---

crates/papyrus_storage/Cargo.toml
crates/papyrus_storage/src/bin/storage_benchmark.rs
crates/papyrus_storage/src/db/db_stats.rs
crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
crates/papyrus_storage/src/mmap_file/mod.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/state/state_test.rs
crates/papyrus_storage/src/utils.rs
crates/papyrus_storage/src/utils_test.rs

Notable changes, the rest is either `From` or usize->u64 casts:
1. storage_benchmark: all usages are usize, not u128, so switching.
2. db_stats: to usages needed `as f64` so added exception, last usage used f64 pow, no need to pass through i32.
3. serializers: multi-type use macro, added exception.
4. utils.rs: metrics need as f64.

chore: add lints to papyrus_storage

---

crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/stream_builder.rs

moves non-fatal state diff related errors to BadPeerError to allow retrying the query with a different peer. previously state diff related tests checked these non-fatal errors as assertions to certain scenarios. we now just check that these scenarios cause peer reporting.

refactor(sync): move state diff related errors to BadPeerError

---

crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/stream_builder.rs
crates/papyrus_p2p_sync/src/client/transaction.rs

Create err types BadPeerError,ParseDataError. later on the errors from P2PSyncClientError will be sorted to fatal and non-fatal(BadPeer). this will allow to retry on non fatal errors during parsing of data blocks.

feat: allow DataStreamBuilder to retry queries if non fatal err

---

crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions.rs
crates/starknet_api/src/executable_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1279)

chore(blockifier): impl traits Executable & TxInfoCreator for api_executabe_txs

---

crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/invoke.rs
crates/blockifier/src/test_utils/transfers_generator.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

refactor(blockifier): change return type of invoke_tx deploy_account_tx to account_transaction

---

crates/blockifier/src/test_utils/declare.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/invoke.rs
crates/blockifier/src/transaction/account_transactions_test.rs

refactor(blockifier): impl .into() from api executable tx to blockifier AccountTransaction

---

crates/blockifier/src/fee/eth_gas_constants.rs
crates/starknet_api/src/contract_class.rs
crates/starknet_api/src/core.rs
crates/starknet_api/src/lib.rs

chore(blockifier): implement staknet_api class_info to match blockifier class_info

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/storage_read_write.rs

Add the read and write syscalls to the `NativeSyscallHandler`.
Open for you to see and react. Notice that Cairo Native dependency has changed, this is because I had to update that relative paths are solved in order for it to detect the Runtime based on the `.cargo/config.toml` file. 
Looking forward to your feedback.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1305)

feat(blockifier): add read and write cairo native syscalls

---

crates/papyrus_config/src/dumping.rs
crates/papyrus_node/src/config/pointers.rs
crates/sequencer_node/src/config/node_config.rs

chore(config): use sub types for config pointers

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs

This PR adds support for the sha256_process_block syscall for cairo native's syscall handler.

feat(blockifier): add support for sha256_process_block syscall

---

.github/workflows/main.yml
Cargo.toml
scripts/clippy.sh
scripts/run_tests.py

- Only one source of truth for lints, main Cargo.toml, making clippy.sh unnecessary.
- Warnings no longer denied, only in the CI. To preserve existing behaviors users can add `-Dwarnings` to local RUSTFLAGS.
We still need to enforce in workspace tests that all crates inherit workspace lints.

chore(ci): remove clippy.sh

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_gateway/src/stateless_transaction_validator_test.rs
crates/starknet_gateway/src/test_utils.rs

Moved test utils specific to gateway's tests that probably won’t be used in other crates. 
The use of `declare_tx_args`, `rpc_declare_tx`, `rpc_deploy_account_tx`, `rpc_invoke_tx` from `mempool_test_utils` is temporary, discussions are ongoing about moving them, likely to SN API.
instead of `NON_EMPTY_RESOURCE_BOUNDS` we can use:
1. use this startnet_api's [func](https://github.com/starkware-libs/sequencer/blob/228488fe25742451b3337c6dfe61f4f303a196d0/crates/starknet_api/src/rpc_transaction_test.rs#L32): `create_resource_bounds_for_testing`. I prefer this option if possible.
2. move this blockifier's [func](https://github.com/starkware-libs/sequencer/blob/bd3fad882c3419ad51bc9466abd146f63a859776/crates/blockifier/src/transaction/test_utils.rs#L360): `create_all_resource_bounds`
3. move …

refactor(gateway): move test utils to gateway

---

crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/starknet_api/src/executable_transaction.rs
crates/starknet_api/src/lib.rs

chore(blockifier): remove redundant blockifier transactions and related fns

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/send_message_to_l1.rs

Implements the `send_message_to_l1` syscall for native cairo syscall handler.

feat(blockifier): add send_message_to_l1 cairo native syscall

---

crates/starknet_mempool/src/mempool.rs
crates/starknet_mempool/src/transaction_pool.rs

It's `Copy`, less boilerplate in callsites.

refactor(mempool): return `TransactionReference` by value from pool

---

crates/starknet_mempool/src/mempool_test.rs

In mempool tests we pass sorted txs explicitly.
This PR removes the usage of `sort_by_key` in the tests.

refactor(mempool): pass sorted txs explicitly

---

crates/starknet_mempool/src/mempool_test.rs

- This is prep. for nonce abstraction feature; setup should be done in a complete manner, so all nonce layers will be updated properly.
- Removed the case of rejecting transactions with nonce that is queued; this is okay. Will be separately tested, both in nonce abstraction tests and in fee escalation tests.

test(mempool): fix `test_add_tx_lower_than_queued_nonce` setup

---

crates/starknet_api/src/test_utils.rs
crates/starknet_api/src/test_utils/l1_handler.rs

Example use case: l1_provider.
Logic and naming is consistent with similar macros for invoke/deployaccount/declare

feat(starknet_api): add L1Handler args macro

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs

This PR adds support for keccak syscall for the native syscall handler.

feat(blockifier): add support for keccak syscall

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs

Implements `library_call` in the `NativeSyscallHandler`.

feat(blockifier): add library_call cairo native syscall

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/emit_event.rs

Implements the `emit_event` syscall for native cairo syscall handler.

feat(blockifier): add emit_event cairo native syscall

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/replace_class.rs

Implements the`replace_class` syscall for native cairo syscall handler.

feat(blockifier): add replace_class cairo native syscall

---

crates/starknet_mempool/src/mempool.rs
crates/starknet_mempool/src/test_utils.rs
crates/starknet_mempool/src/transaction_queue.rs
crates/starknet_mempool/tests/flow_test.rs

I've made `update_gas_price_threshold` API to be public, so I can use it flow test.

test(mempool): impl update gas price threshold flow test

---

crates/blockifier/src/abi/sierra_types.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/state.rs

The TODO was added on [this PR](https://github.com/starkware-libs/blockifier/pull/857) from the blockifier repo.

chore(blockifier): share the utility next_storage_key to starknet api

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs

Implements the `get_block_hash` syscall for native cairo syscall handler.

feat(blockifier): add get_block_hash cairo native syscall

---

crates/starknet_batcher_types/src/communication.rs
crates/starknet_gateway_types/src/communication.rs
crates/starknet_mempool_p2p_types/src/communication.rs
crates/starknet_mempool_types/src/communication.rs
crates/starknet_sequencer_infra/src/component_client/local_component_client.rs
crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs
crates/starknet_sequencer_infra/src/tests/local_component_client_server_test.rs

commit-id:90fa2e32
---
**Stack**:
- #2090
- #2089
- #2088
- #2087
- #2086
- #2085
- #2084
- #2083 ⬅
- #2082

chore(sequencer_infra): local client send returns client result

---

crates/papyrus_proc_macros/src/lib.rs
crates/starknet_batcher_types/src/communication.rs
crates/starknet_gateway_types/src/communication.rs
crates/starknet_mempool_p2p_types/src/communication.rs
crates/starknet_mempool_types/src/communication.rs
crates/starknet_sequencer_infra/src/component_client/local_component_client.rs
crates/starknet_sequencer_infra/src/component_definitions.rs
crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs
crates/starknet_sequencer_infra/src/tests/local_component_client_server_test.rs
crates/starknet_state_sync_types/src/communication.rs

**Stack**:
- #2090
- #2089
- #2088
- #2087
- #2086
- #2085
- #2084 ⬅

chore(sequencer_infra): add component client trait for local client

---

crates/starknet_batcher_types/src/communication.rs
crates/starknet_gateway_types/src/communication.rs
crates/starknet_mempool_p2p_types/src/communication.rs
crates/starknet_mempool_types/src/communication.rs
crates/starknet_sequencer_infra/src/component_client/remote_component_client.rs
crates/starknet_sequencer_infra/src/component_server/local_component_server.rs
crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs
crates/starknet_sequencer_infra/src/tests/mod.rs
crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs

commit-id:8a20078e
---
**Stack**:
- #2119 ⬅
- #2115
- #2090
- #2089
- #2088
- #2087
- #2086
- #2085

chore(sequencer_infra): remove redundant clones

---

crates/blockifier/src/execution.rs
crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/secp.rs
crates/blockifier/src/execution/syscalls/secp.rs

This PR adds the logic for secp in preparation of the native syscalls. 
The code has been refactored such that the implementation is shared between the native and non-native syscalls.

feat(blockifier): add secp logic

---

crates/blockifier/src/test_utils/invoke.rs
crates/starknet_api/src/test_utils/invoke.rs

This PR replaces #1930. Thanks to the PRs this is on top of, it is much simpler now.

chore(starknet_api): streamline the base invoke tx creator to include v0 towards code dedup

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/test_utils/declare.rs
crates/starknet_gateway/src/stateful_transaction_validator_test.rs
crates/starknet_gateway/src/stateless_transaction_validator_test.rs
crates/starknet_gateway/src/test_utils.rs

The `DeclareTxArgs` in the mempool contained a `ContractClass` field which does not exist in the appropriate struct in StarknetAPI. The field is required for RPCs from the gateway. Two possible solutions were to either add it as a new field in the struct in the StarknetAPI or add it as an additional argument in the RPC.
Since the struct is used both in internal cases (e.g., by the blockifier) and external cases (the gateway) we've decided not to add the field (which is external in type) to the struct but rather supply it as additional input in the RPC.
Another difference between the two structs is that the default `resource_bound` type in the mempool is `AllResources` while in the StarknetAPI it is `L1Gas`. After refactoring we've supplied all invocations of the macro with a default …

refactor(mempool): call declare_tx_args from StarknetAPI

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/transaction/constants.rs

Created to address a thought on: #2104.

chore(blockifier): compute valid retdata directly

---

crates/starknet_integration_tests/src/utils.rs

**Stack**:
- #2071
- #2070
- #2056 ⬅

chore(tests_integration): return tx sender address

---

crates/blockifier/src/execution/native/entry_point_execution.rs
crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_class_hash_at.rs

Re-openning https://github.com/starkware-libs/sequencer/pull/2077 since it was not included in the latest version of #2076

feat(blockifier): implement get_clash_at syscall for native

---

crates/starknet_sequencer_node/src/servers.rs
crates/starknet_sequencer_node/src/utils.rs

commit-id:02b017c7
---
**Stack**:
- #2125
- #2124
- #2047 ⬅

feat: support remote servers execution

---

Cargo.lock
config/sequencer/default_config.json
crates/starknet_integration_tests/Cargo.toml
crates/starknet_integration_tests/src/config_utils.rs
crates/starknet_integration_tests/src/utils.rs
crates/starknet_integration_tests/tests/end_to_end_integration_test.rs
crates/starknet_sequencer_node/src/config/node_config.rs
crates/starknet_sequencer_node/src/config/test_utils.rs

commit-id:ab21c59b
---
**Stack**:
- #2071 ⬅
- #2070

chore(tests_integration): add nonce verification

---

Cargo.lock
crates/starknet_gateway_types/Cargo.toml
crates/starknet_gateway_types/src/communication.rs

chore: add testing feature, use automock only as test

---

crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs
crates/starknet_l1_provider/src/test_utils.rs

Follows the same pattern and API style as `MempoolContent`.

feat(l1_provider): add `L1ProviderContent`

---

commitlint.config.js

- 50 is too small, especially with large `chore(<big_scope_name>)`
- For example, Linux kernel uses 72.
- why 72? that's already the length of the commit body, and having
a larger title is weird.

chore(ci): increase max length of commit message from 50 to 72 inclusive

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs

Currently waiting for other changes before proceeding with this.
This is currently a Draft. It requires some other Secp logic that will come in another issue. Then, this branch will be rebased on top of it and the overlapping logic will be removed.

feat(blockifier): add Secp256r1 cairo native syscalls

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs

Should go after #1675 , #1813 , #1546 , #1545 
Commit history will be changed in the future, so "feat: add support for keccak syscall" will be removed

feat(blockifier): add support for secp256k1 syscall for native

---

crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/transaction/objects_test.rs

Warning: this expression creates a reference which is immediately dereferenced by the compiler

chore(blockifier): remove warning about versioned constants

---

Cargo.lock
crates/infra_utils/Cargo.toml
crates/infra_utils/src/command.rs
crates/infra_utils/src/command_test.rs
crates/infra_utils/src/lib.rs
crates/infra_utils/src/path.rs
crates/infra_utils/src/path_test.rs
crates/papyrus_config/src/lib.rs

commit-id:96859c27
---
**Stack**:
- #2270
- #2266
- #2265
- #2264 ⬅
- #2255
- #2254

chore: add shell command builder

---

crates/starknet_sequencer_node/src/test_utils/compilation.rs
crates/starknet_sequencer_node/src/test_utils/compilation_test.rs

commit-id:7f25ebe8
---
**Stack**:
- #2270
- #2266
- #2265 ⬅

chore(sequencer_node): compile the node, not the entire project

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/test_instances.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/starknet_api/src/transaction.rs

This is a temporary hack (as is evident from the many TODO items), that allows passing in the ProposalPart, specifically in the TransactionBatch, not only a vector of Transactions but also a vector of TransactionHashes. 
This is useful as it lets us convert a regular transaction into an ExecutableTransaction. 
In the future, we will either make the hash part of the transaction we broadcast (whatever we end up naming it) or we will have a tool that calculates this hash at the same time that we also do other calculation needed for executable transactions (e.g., compiling code).

feat: add TransactionHash to TransactionBatch

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs
crates/papyrus_rpc/src/v0_8/api/test.rs
crates/papyrus_rpc/src/v0_8/execution_test.rs
crates/papyrus_rpc/src/v0_8/write_api_result_test.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/src/block_hash/block_hash_calculator_test.rs
crates/starknet_api/src/block_hash/event_commitment_test.rs
crates/starknet_api/src/block_hash/receipt_commitment_test.rs
crates/starknet_api/src/block_hash/transaction_commitment_test.rs
crates/starknet_api/src/transaction.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_batcher/src/block_builder_test.rs
crates/starknet_batcher/src/test_utils.rs
crates/starknet_batcher/src/transaction_provider_test.rs
crates/starknet_client/src/reader/objects/block_test.rs
crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_mempool/src/test_utils.rs

Move `tx_hash!` macro constructor to `core.rs` in SN API and use macro throughout codebase.

refactor(starknet_api): use tx_hash constructor macro

---

Cargo.lock
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/run.rs
crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_consensus_manager/src/consensus_manager.rs

This is part of a series of PRs to integrate streaming of consensus proposals. 
It adds the streaming channels but does not connect them to block building or validation, yet.

feat(sequencing): allow a streamed proposal channel on top of existing

---

crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_api/src/transaction.rs
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_integration_tests/src/flow_test_setup.rs
crates/starknet_integration_tests/src/utils.rs
crates/starknet_integration_tests/tests/end_to_end_flow_test.rs

This PR adds the ability to broadcast a new proposal from Consensus, using the streamed channel.

feat(sequencing): broadcast proposal in a stream

---

crates/papyrus_node/src/run.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs

This PR adds the ability of the Consensus/Context to accept streamed proposals and validate them.

feat(sequencing): validate streamed proposals

---

crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs

This is to comply with upcoming integration with infra, which separates instantiation with initialization. In particular, `Pending` state should be already post-syncing with L1, whereas `Uninitialized` is unsynced and unusable.
Using panicking here because trying to call this service while uninitialized is a serious bug.

feat(starknet_l1_provider): add uninitiailized state and make it the default

---

crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs

- **refactor(papyrus_p2p_sync): add common run_test with a new header test**
- **refactor(papyrus_p2p_sync): add random_header utility function**

refactor(papyrus_p2p_sync): add random_header utility function

---

crates/blockifier/resources/versioned_constants_0_13_0.json
crates/blockifier/resources/versioned_constants_0_13_1.json
crates/blockifier/resources/versioned_constants_0_13_1_1.json
crates/blockifier/resources/versioned_constants_0_13_2.json
crates/blockifier/resources/versioned_constants_0_13_2_1.json
crates/blockifier/resources/versioned_constants_0_13_3.json
crates/blockifier/resources/versioned_constants_0_13_4.json
crates/blockifier/src/versioned_constants.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs

If a proposal is received by Consensus that has height bigger than the current height, cache it into a hash map that saves it for later. 
When starting a new height, will first look to see if any cached proposals exist before listening to messages from the network.

feat(sequencing): cache proposals from bigger heights

---

crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs

- **refactor(papyrus_p2p_sync): add common run_test with a new header test**
- **refactor(papyrus_p2p_sync): add_test receives query size instead of constant**

refactor(papyrus_p2p_sync): add_test receives query size instead of constant

---

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_integration_tests/src/utils.rs

This cleans up some of the leftover code from before we added streamed proposals. 
In this specific PR I remove the channels that used to pass the proposals into context.

fix(sequencing): remove old proposal pipes

---

Cargo.lock
crates/starknet_integration_tests/src/config_utils.rs
crates/starknet_sequencer_infra/Cargo.toml
crates/starknet_sequencer_infra/src/component_client/definitions.rs
crates/starknet_sequencer_infra/src/component_client/remote_component_client.rs
crates/starknet_sequencer_infra/src/serde_utils.rs
crates/starknet_sequencer_infra/src/serde_utils_test.rs
crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs

commit-id:e9855990
---
**Stack**:
- #2506 ⬅
- #2463
- #2462
- #2461

feat: add config functions for remote flow test

---

Cargo.lock
crates/starknet_l1_provider/Cargo.toml
crates/starknet_l1_provider/src/errors.rs
crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs

- don't expose internal module `ProviderState`
- add serde
- extract scraping error, it will be added to a separate interface.

chore(starknet_l1_provider): get errors ready for infra

---

crates/starknet_integration_tests/src/config_utils.rs
crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs
crates/starknet_sequencer_node/src/clients.rs
crates/starknet_sequencer_node/src/components.rs
crates/starknet_sequencer_node/src/config/component_config.rs
crates/starknet_sequencer_node/src/config/component_execution_config.rs
crates/starknet_sequencer_node/src/config/config_test.rs
crates/starknet_sequencer_node/src/servers.rs

commit-id:794b2125
---
**Stack**:
- #2578
- #2577
- #2576
- #2575 ⬅
- #2574
- #2573
- #2544

chore(starknet_sequencer_node): add active component execution config

---

Cargo.lock
Cargo.toml
commitlint.config.js
crates/starknet_l1_provider/Cargo.toml
crates/starknet_l1_provider/src/errors.rs
crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs
crates/starknet_l1_provider_types/Cargo.toml
crates/starknet_l1_provider_types/src/errors.rs
crates/starknet_l1_provider_types/src/lib.rs

Only move, no logic changes, this is a setup for upcoming infra support.

chore(starknet_l1_provider_types): add crate

---

.github/workflows/sequencer_integration_tests.yml
crates/starknet_integration_tests/src/utils.rs
crates/starknet_integration_tests/tests/end_to_end_integration_test.rs

commit-id:55e84a9b
---
**Stack**:
- #2509
- #2508 ⬅

chore(ci): create sequencer integration test workflow

---

crates/papyrus_p2p_sync/src/client/class_test.rs
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/papyrus_p2p_sync/src/client/transaction_test.rs

- **refactor(papyrus_p2p_sync): add_test receives query size instead of constant**
- **refactor(papyrus_p2p_sync): run_test supports all data types**

refactor(papyrus_p2p_sync): run_test supports all data types

---

crates/starknet_integration_tests/tests/end_to_end_integration_test.rs
crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs

- chore: derive Hash on RpcTransaction
- chore: changing closure Fn requirements on integration test utils
- test(mempool_p2p): test received rpc transactions are being broadcasted
- test(mempool_p2p): test tx received from p2p reach mempool

test(starknet_mempool_p2p): test tx received from p2p reach mempool

---

crates/starknet_integration_tests/tests/end_to_end_flow_test.rs
crates/starknet_integration_tests/tests/end_to_end_integration_test.rs
crates/starknet_sequencer_infra/src/trace_util.rs
crates/starknet_sequencer_node/src/main.rs

chore: configure tracing only once

---

.cargo/config.toml

x86_64-unknown-linux-gnu is run locally and also ran in the CI until we added inherit_toolchain, which seems to prepend `stable-` to the target-string.

fix(ci): add a CI type to `lld` whitelist

---

crates/sequencing/papyrus_consensus/src/stream_handler.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs

I've wanted to remove the BTreeMap from StreamHandler for a while. 
It functions the same as HashMap but has the ordered keys feature, which we no longer use. 
It seems simpler to just work with one kind of map.

chore(sequencing): replace BTreeMap with HashMap in StreamHandler

---

.cargo/config.toml
.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/blockifier_reexecution_ci.yml
.github/workflows/committer_ci.yml
.github/workflows/committer_cli_push.yml
.github/workflows/main.yml
.github/workflows/main_pr.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_docker-publish.yml
.github/workflows/papyrus_nightly-tests-call.yml
.github/workflows/papyrus_nightly-tests.yml
.github/workflows/sequencer_integration_tests.yml
.github/workflows/upload_artifacts_workflow.yml
.github/workflows/verify-deps.yml

Previous fix added stable- target, didn't work.
This one is truly agnostic to rust version and should work on all linux targets.

fix(ci): fix the linker fix

---

Cargo.lock
crates/starknet_l1_provider/Cargo.toml
crates/starknet_l1_provider/src/communication.rs
crates/starknet_l1_provider/src/lib.rs

Adding provider-side boilerplate for provider-batcher communication

chore(starknet_l1_provider): getting things ready for the client

---

crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/manager_test.rs

The old values led to long tests. The new value revealed we had a poor expectation which was fixed.

refactor(consensus): lower test timeouts and fix test

---

crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs

The goal is to remove the nested selects to make cancellation logic simpler.

refactor(consensus): move the sync check into run_height

---

crates/sequencing/papyrus_consensus/src/stream_handler_test.rs

This solves a clippy error on the test `stream_handler_test` which uses a helper function. Accepting arrays instead of vector refs is a good idea in general.

fix(sequencing): replace vectors with arrays as test function inputs

---

.github/actions/install_rust/action.yml
.github/workflows/main.yml

Looks like cargo-install action isn't picking up the `lld` rustflags inside main.yml.
Anyhow, installing through moonrepo is probably better anyway, since it
is already installing rust.

fix(ci): install taplo through moonrepo

---

crates/papyrus_protobuf/src/consensus.rs

This todo item seems more like something Matan would know how to do. 
Need to either move it to him or remove the comment.

chore(consensus): move the todo on ProposalFin to Matan

---

crates/blockifier_reexecution/src/main.rs
crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs
crates/blockifier_reexecution/src/state_reader/utils.rs
crates/papyrus_load_test/Cargo.toml
crates/starknet_gateway/src/config.rs
crates/starknet_integration_tests/src/config_utils.rs
crates/starknet_integration_tests/src/utils.rs

commit-id:bfb3bef3
---
**Stack**:
- #2611 ⬅
- #2610
- #2609
- #2608

chore(starknet_integration_tests): remove const for json rpc version

---

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_api/src/transaction.rs
crates/starknet_api/src/transaction_test.rs
crates/starknet_consensus_manager/src/consensus_manager.rs

chore(starknet_consensus_manager): add chain_id to config
feat(consensus): calculate the executable_transaction in consensus_context

fix(consensus): calculate the executable_transaction in consensus_context

---

Cargo.lock
crates/starknet_integration_tests/src/end_to_end_integration.rs
crates/starknet_sequencer_node/Cargo.toml
crates/starknet_sequencer_node/src/test_utils/compilation_test.rs
crates/starknet_sequencer_node/src/test_utils/mod.rs
crates/starknet_sequencer_node/src/test_utils/node_runner.rs

chore(starknet_integration_tests): removing node compilation

---

crates/blockifier/src/state.rs
crates/blockifier/src/state/stateful_compression.rs
crates/blockifier/src/state/stateful_compression_test.rs

fix(blockifier): fix test_write_at_validate_and_execute (#2529)
feat(blockifier): aliases updater struct

feat(blockifier): aliases updater struct

---

crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs

test(blockifier): max validate\execute gas less than max possible sierra gas

---

crates/starknet_mempool/src/mempool_test.rs

Secondary priority is currently determined by the transaction's hash, ensuring consistent tie-breaking behavior.

test(starknet_mempool): impl test to verify get_txs returns txs sorted by secondary priority on tie

---

crates/sequencing/papyrus_consensus/src/stream_handler.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs

In the StreamHandler inbound case (listening to the network and sending internal messages into Consensus) there's a case where the Consensus drops the receiver. 
This is a receiver that the StreamHandler sends whenever it sees a new stream, and the receiver should stay open for as long as that stream is not done. 
However, the Consensus may choose to drop it (e.g., when moving to a new height) and that leaves the StreamHandler with a broken pipe, and also some messages that should go into that pipe. 
As a first step, I'm making this no longer a panic, but if the receiver is dropped, then the sender inside StreamHandler is dropped, too (along with the remaining StreamData, which includes the message id, cached messages, etc). 
This still doesn't address what happens to all the other …

fix(consensus): dont fail when stream handler inbound receiver drops

---

config/sequencer/default_config.json
crates/blockifier/src/state.rs
crates/blockifier/src/state/contract_class_manager.rs
crates/blockifier/src/state/global_cache.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_block_executor_test.rs
crates/papyrus_state_reader/src/papyrus_state.rs
crates/papyrus_state_reader/src/papyrus_state_test.rs
crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/block_builder.rs
crates/starknet_batcher/src/config.rs

- **feat(cairo_native): use contract class manager in papyrus reader**

feat(cairo_native): use contract class manager in papyrus reader

---

.github/actions/install_rust/action.yml
.github/workflows/main.yml

Benchmark: installation is cached, now 7 seconds down from 45.
Verify that machete still fails builds with this setting: https://github.com/starkware-libs/sequencer/actions/runs/12399068544/job/34613195214?pr=2783

fix(ci): cache machete install

---

crates/papyrus_execution/src/execution_utils.rs
crates/papyrus_execution/src/state_reader.rs
crates/papyrus_execution/src/state_reader_test.rs

Who should I add as a reviewer responsible for `papyrus_execution`?

chore(papyrus_execution):  get versioned contract class

---

crates/blockifier/Cargo.toml
crates/blockifier/src/state/stateful_compression_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
scripts/run_tests.py

Without --all-targets they don't run on tests and benchmarks.

fix(ci): fix warnings

---

Cargo.lock
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/resources/Starknet-0.10.3.4.json
crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_node/src/run.rs

Use alloy to generate a `Starknet` instance, which can interact with contract on L1.
Using `Starknet::new` assumes the contract _has already been deployed_ at the given address, and will delegate calls to that address.
Note: since errors are not possible during construction, the error handling was removed.

feat(starknet_l1_provider): add Starknet contract

---

crates/starknet_mempool/src/mempool_test.rs

I considered wrapping `builder_with_queue` to include adjustment of `fee_escalation_percentage` and `gas_price_threshold`, but since it's used only twice, I kept it simple to avoid complexity.

refactor(starknet_mempool): share test code of builder init of queued tx

---

crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs

I've removed the MockTestContext from manager_test.rs and instead mved it to depend on the mock context in test_utils.rs.

chore(sequencing): remove mock context from manager_test.rs

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/consensus_test.rs
crates/papyrus_protobuf/src/converters/test_instances.rs

I'm starting to remove the ConsensusMessage from where ever I can find it. It will come out in pieces. When done, I'll make another PR to remove it from the proto.

chore(sequencing): remove ConsensusMessage from converter test

---

crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/lib.rs
crates/papyrus_sync/src/sources/base_layer.rs

- add l1 latest block getter to base layer trait (will be used in later commits).
- use `BlockHashAndNumber` instead of tuple.

refactor(papyrus_base_layer): extract last l1 number

---

crates/sequencing/papyrus_consensus/src/stream_handler.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs

I found that having `Clone` on `StreamData` is not necessary. I need to remove it so I can add a receiver to the data, and receiver doens't implement `Clone`. The need for this receiver will be made clear in the next PR.

fix(consensus): remove the Clone trait bound from StreamData

---

crates/starknet_integration_tests/src/config_utils.rs
crates/starknet_integration_tests/src/end_to_end_integration.rs
crates/starknet_sequencer_node/src/config/component_config.rs
crates/starknet_sequencer_node/src/config/component_execution_config.rs

commit-id:9673c1ca
---
**Stack**:
- #2867 ⬅
- #2866

chore: add disabled function to ComponentConfig

---

Cargo.lock
crates/infra_utils/Cargo.toml
crates/infra_utils/src/lib.rs
crates/infra_utils/src/metrics.rs

**Stack**:
- #2888
- #2885
- #2884
- #2881 ⬅
- #2915

chore(infra_utils): add parse_numeric_metric

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_batcher/src/block_builder.rs
crates/starknet_batcher/src/utils.rs

Use BlockExecutionArtifacts instead.
The final goal is to support EIP-1559 for better fee estimation with a dynamic base fee. 
This PR is the first step: I replaced `ProposalOutput` with `BlockExecutionArtifacts`, which includes `l2_gas_used`. 
Next, I'll pass `l2_gas_used` to `SequencerConsensusContext` and then calculate base gas price.

refactor(starknet_batcher): delete ProposalOutput struct

---

crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

I've had to simplify the test in this file (`simulation_network_receiver_test.rs`) so it now only works with Vote type messages. 
I'm not sure what would be a good way to also check the proposal channel, or if it is even necessary to add that check.

chore(sequencing): remove ConsensusMessage from simulation network

---

crates/papyrus_node/src/bin/run_consensus.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_consensus_manager/src/consensus_manager.rs

This is the big one. 
I removed the ConsensusMessage from context and single height consensus and a bunch of other places, that were all related to each other. 
I don't think there's a way to chop it up into smaller pieces...

chore(sequencing): remove ConsensusMessage from context

---

crates/papyrus_protobuf/Cargo.toml
crates/papyrus_protobuf/src/consensus.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs

A few TODOs that I found that are no longer relevant and are removed.

chore(consensus): remove irrelevant TODO items

---

Cargo.lock
crates/starknet_gateway/Cargo.toml
crates/starknet_gateway/bench/gateway_bench.rs
crates/starknet_gateway/src/gateway.rs
crates/starknet_gateway/src/stateful_transaction_validator_test.rs

We can later discuss the details of the test cases we want to benchmark exactly.
Running the benchmarking action:
`cargo bench --bench gateway_bench`
Prints:
```
declares                time:   [0.0000 ps 0.0000 ps 0.0000 ps]
change: [-62.446% -29.235% +34.904%] (p = 0.33 > 0.05)
No change in performance detected.
Found 13 outliers among 100 measurements (13.00%)
4 (4.00%) high mild
9 (9.00%) high severe
deploy_accounts         time:   [0.0000 ps 0.0000 ps 0.0000 ps]
change: [-54.552% -11.417% +70.199%] (p = 0.73 > 0.05)
No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
4 (4.00%) high mild
8 (8.00%) high severe
invokes                 time:   [0.0000 ps 0.0000 ps 0.0000 ps]
change: [-46.424% -0.1889% +83.908%] (p = 1.00 > 0.05)
No change in performance …
```

chore(starknet_gateway): create bench file for benchmark test

---

crates/sequencing/papyrus_consensus_orchestrator/src/fee_market/mod.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs

Calculate next base gas price and store it in the `SequencerConsensusContext` field for later use in `build_proposal`.

feat(consensus): calculate base gas price

---

crates/starknet_integration_tests/src/flow_test_setup.rs
crates/starknet_integration_tests/src/integration_test_setup.rs
crates/starknet_integration_tests/src/utils.rs

chore(starknet_integration_tests): pass relevant ports to mempool p2p config gen fn

---

.github/workflows/main.yml
crates/blockifier/src/execution/syscalls/mod.rs
crates/starknet_api/src/state.rs
crates/starknet_sequencer_node/src/clients.rs
scripts/run_tests.py

- No reason to run cargo on release in the ci, and this busts cache
- Cargo doc doesn't pick up the usual place we pass -Dwarnings, which is
RUSTFLAGS, it needs a special flag RUSTDOCFLAGS (it cannot reference
the usual RUSTFLAGS so we have to duplicate)

fix(ci): compile rust docs in release and deny warnings

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test_utils.rs

- **fix(papyrus_network): revert "avoid panicking if the messages to broadcast sender was dropped"**
- **fix(papyrus_network): add NetworkError::BroadcastChannelsDrop and ignore it in test utils**

fix(papyrus_network): add NetworkError::BroadcastChannelsDrop and ignore it in test utils

---

crates/sequencing/papyrus_consensus/src/stream_handler.rs

Sometimes we get this error: 
`2024-12-24T15:31:05.495525Z ERROR starknet_consensus_manager::consensus_manager: Error running component ConsensusManager: InternalNetworkError("Stream handler must fill the first message before sending the stream")`
From this [test run](https://github.com/starkware-libs/sequencer/actions/runs/12483489296/job/34839351984).
This is probably because of the way `StreamHandler.inbound_send()` works. It first checks if there's a need to send the receiver and then puts a message inside it. I've flipped the order, I hope this solves the problem.

fix(consensus): send init before starting work on proposal content

---

Cargo.lock
crates/starknet_mempool_p2p/Cargo.toml
crates/starknet_mempool_p2p/src/runner/test.rs

- test(mempool_p2p): change p2p runner test to use automock for gateway client
- test(mempool_p2p): test gateway client error on adding tx from p2p

test(starknet_mempool_p2p): test gateway client error on adding tx from p2p

---

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs

Previously this was called at the beginning of the next height which
lead to errors, where the spawned task attempted to work after the
batcher had stopped working.

fix(consensus): interrupt_active_proposal at the end of the height

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_batcher/src/block_builder.rs
crates/starknet_batcher/src/block_builder_test.rs
crates/starknet_batcher/src/test_utils.rs
crates/starknet_mempool/src/mempool.rs
crates/starknet_mempool/src/mempool_test.rs
crates/starknet_mempool/src/test_utils.rs
crates/starknet_mempool/tests/flow_test.rs
crates/starknet_mempool_types/src/mempool_types.rs

Deleted tx_hashes from the commit_block input because they are removed from the pool when calling remove_up_to_nonce on the address-nonce input.
Added rejected_tx_hashes to explicitly delete them from the pool.

feat(starknet_mempool): in CommitBlockArgs delete tx_hashes and add rejected_tx_hashes

---

Cargo.lock
crates/papyrus_base_layer/src/constants.rs
crates/papyrus_base_layer/src/lib.rs
crates/starknet_l1_provider/Cargo.toml
crates/starknet_l1_provider/src/l1_scraper.rs
crates/starknet_l1_provider/src/lib.rs

- base layer constant file will hold the identifiers of Starknet Events.
- fetch_events will get events from base layer and send to provider

feat(starknet_l1_provider): add scraper

---

Cargo.lock
crates/sequencing/papyrus_consensus_orchestrator/Cargo.toml
crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs

Cende source was written to send a success signal over a channel and panic on failure.
Cende usage is meant to check once for completion and drop the receiver if incomplete.
This leads to panic if cende finishes late and sends after the receiver is dropped.
Also use AbortOnDropHandle to shut down the cende task once we no longer wait for it.

fix(sequencing): cende panics if late

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/transaction_provider.rs
crates/starknet_batcher/src/transaction_provider_test.rs
crates/starknet_l1_provider/src/communication.rs
crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs
crates/starknet_l1_provider/src/test_utils.rs
crates/starknet_l1_provider_types/src/errors.rs
crates/starknet_l1_provider_types/src/lib.rs

To ensure soundness. Otherwise bugs in batcher/consensus that try to calculate blocks with future heights may cause double-proposing of a tx, which causes a reorg for l1handler txs.

feat(starknet_l1_provider): add `height` arg

---

crates/starknet_gateway/src/stateful_transaction_validator.rs

The todo message was already covered the moment the stateful validator got an executable transaction as part of the input.

chore(starknet_gateway): remove todo massage that was already covered

---

crates/starknet_integration_tests/src/end_to_end_integration.rs
crates/starknet_integration_tests/src/integration_test_setup.rs
crates/starknet_integration_tests/src/sequencer_manager.rs
crates/starknet_integration_tests/src/test_identifiers.rs
crates/starknet_sequencer_infra/src/test_utils.rs
crates/starknet_sequencer_node/src/test_utils/node_runner.rs

chore(starknet_integration_tests): prepend sequencer part to test output
chore(starknet_integration_tests): awaiting aliveness concurrently
refactor(starknet_integration_tests): move fns to sequencer manager mod
refactor(starknet_integration_tests): move more fns to sequencer manager mod

chore(starknet_integration_tests): use iterator instead of vec push

---

Cargo.lock
crates/papyrus_node/src/run.rs
crates/papyrus_protobuf/Cargo.toml
crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/consensus_test.rs
crates/papyrus_protobuf/src/converters/test_instances.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/stream_handler.rs
crates/sequencing/papyrus_consensus/src/stream_handler_test.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_integration_tests/src/flow_test_setup.rs
crates/starknet_integration_tests/tests/end_to_end_flow_test.rs

The stream ID is used to uniquely separate streams coming from the same peer. In the use case of consensus, this can be the `(height, round)` we are in. 
In general, the `stream_id` should be convertible into a `Vec<u8>>` and should have some other traits like `Display` and `Clone`, etc.

feat: allow StreamHandler to use a generic StreamId

---

crates/papyrus_network/src/network_manager/test_utils.rs
crates/starknet_integration_tests/src/flow_test_setup.rs

- **revert(starknet_integration_tests): remove mempool p2p flow test**
- **feat(papyrus_network): split network config creation and conversion to broadcast channels**

feat(papyrus_network): split network config creation and conversion to broadcast channels

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs

I've replaced some repeated instances of `Into<Vec<u8> + TryFrom<Vec<u8>...` with a single trait named `Protoable`. 
We can argue about the name. 
So far it is only used in the papyrus_protobuf crate, for consensus related things: the StreamMessage is the only thing that can't automatically generate those conversions, as it has a generic type.

chore(consensus): unify into/try_from Vec<u8> traits

---

Cargo.lock
Cargo.toml
commitlint.config.js
crates/starknet_sierra_compile_types/Cargo.toml
crates/starknet_sierra_compile_types/src/lib.rs

This is the `_types` crate for the compiler component that the class manager will use (a thin functional wrapper will wrap the existing compiler code in `starknet_sierra_compile` crate, thus will be added there. This is the reason the non-`_types` crate already exists.

feat(starknet_sierra_compile_types): add crate

---

.gitconfig

- **test(blockifier): fix broken revert-recurse fee check in test (#3133)**
- **fix(cairo_native): fix cairo native submdoule commit hash (#3199)**
- **chore(blockifier): prepare consuming finalize (#3188)**
- **refactor(starknet_api,blockifier): to_discounted_gas_amount (#2874)**
- **test(blockifier_reexecution): get_block_numbers_for_reexecution (#3211)**
- **test(cairo_native): test papyrus state reader get compiled class (#2949)**
- **test(blockifier): refactor account_transaction_test (#3250)**
- **test(blockifier): add old cairo 1 to test_initial_gas (#3262)**
- **test(cairo_native): add native to transactions test (#3041)**
- **chore: add gitconfig that ignores cairo native**

chore: add gitconfig that ignores cairo native

---

Cargo.lock
crates/starknet_sierra_compile/Cargo.toml
crates/starknet_sierra_compile/src/compile_test.rs
crates/starknet_sierra_compile/src/lib.rs

A wrapper around the CLI compiler that also takes care of class serde. It will serve as the compilation CPU unit of the `ClassManager`.

feat(starknet_sierra_compile): add `SierraCompiler`

---

Cargo.lock
crates/blockifier/src/state/global_cache.rs
crates/starknet_api/Cargo.toml
crates/starknet_api/src/class_cache.rs
crates/starknet_api/src/lib.rs

To be used by `ClassManager`, which should not depend on `blockifier`. Also, it's standalone.
Code move only, no changes.

refactor(starknet_api): move `GlobalContractCache` from `blockifier`

---

crates/blockifier/Cargo.toml
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/starknet_api/src/lib.rs
crates/starknet_api/src/versioned_constants_logic.rs

Refactoring the general versioned constants logic to make it reusable for Consensus in the next PR.

refactor: move VersionedConstants macro, errors from Blockifier to StarknetAPI

---

crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs
crates/starknet_l1_provider/src/soft_delete_index_map.rs
crates/starknet_l1_provider/src/test_utils.rs
crates/starknet_l1_provider/src/transaction_manager.rs
crates/starknet_l1_provider_types/src/lib.rs

Previous implementation inside transaction manager didn't account for
validate, the current implementation is more general, and can in the
past perhaps be reused elsewhere after some changes are made.

feat(starknet_l1_provider): add `SoftDeleteIndexMap`

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs

- **chore(papyrus_network): remove PeerTrait which is leftover of mock peer**
- **fix(papyrus_network): track connection id for peers before identify event**

fix(papyrus_network): track connection id for peers before identify event

---

crates/starknet_gateway/src/gateway_test.rs

Modified `expect_add_tx` to take a `MempoolClientResult<()>`, letting tests set expected outcomes instead of always returning `Ok(())`.

refactor(starknet_gateway): make expect_add_tx configurable with custom results

---

.github/actions/bootstrap/action.yml
.github/workflows/blockifier_ci.yml

Installing `taplo` binary is done inside `install_rust` action through moonrepo, this hits OOM sporadically, which we fix by using `lld`, which is installed in `setup_native_deps`.

fix(ci): install deps before rust, fixes taplo sporadic OOM

---

.github/workflows/main.yml

FIXME: This adds 3min to CI, we need to figure out how to cache it.
Initially, Anvil installed only when base layer and l1 provider were changed,
but this is naive, since the l1 provider tests are triggered also when
its dependecies are changed, for example infra crates.

fix(ci): always install Anvil

---

Cargo.lock
crates/starknet_l1_provider/Cargo.toml
crates/starknet_l1_provider/src/l1_provider.rs
crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/lib.rs
crates/starknet_l1_provider/src/soft_delete_index_map.rs
crates/starknet_l1_provider/src/transaction_manager.rs
crates/starknet_l1_provider_types/src/lib.rs

- replace preivous API with the agreed upon `start_block`.
- added state setter for use of start_block; commit_block will have a different setter.

feat(starknet_l1_provider): add `start_block`

---

crates/papyrus_protobuf/build.rs
crates/papyrus_protobuf/src/proto/p2p/proto/sync/event.proto

- **refactor(papyrus_protobuf): move state.proto to sync folder**
- **refactor(papryus_protobuf): move event,proto to the sync folder**

refactor(papyrus_protobuf): move event.proto to the sync folder

---

crates/papyrus_p2p_sync/src/client/class.rs
crates/papyrus_p2p_sync/src/client/class_test.rs
crates/starknet_class_manager_types/Cargo.toml
crates/starknet_class_manager_types/src/lib.rs

In untrusted flows each node needs to calculate class hash by itself. Originally, I wanted the GW to first run
`__validate_declare__(class_hash)` and if successful - request compilation; but it isn't worth optimizing on (`Declare`s are quite rare).

refactor(starknet_class_manager_types): make class hash output of `add_class`

---

Cargo.lock
crates/starknet_sierra_multicompile_types/Cargo.toml
crates/starknet_sierra_multicompile_types/src/lib.rs

Requirement was to compile to `cairo` compiler output format, and be human-readable.

fix(starknet_sierra_multicompile_types): change raw class to JSON

---

config/papyrus/default_config.json
crates/papyrus_node/src/config/mod.rs
crates/papyrus_node/src/config/pointers.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/run.rs
crates/starknet_consensus/src/config.rs
crates/starknet_consensus/src/types.rs
crates/starknet_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/starknet_consensus_orchestrator/src/papyrus_consensus_context_test.rs

Adds a ContextConfig struct that is used by the two context structs.

feat(consensus): add config to Context

---

config/sequencer/default_config.json
crates/papyrus_node/src/run.rs
crates/starknet_consensus_manager/src/config.rs
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_integration_tests/src/utils.rs
crates/starknet_sequencer_node/src/config/node_config.rs

This adds the ContextConfig struct from the previous PR unto the SequencerConsensusContext struct.

chore(consensus): add ContextConfig to SequencerConcensusContext

---

Cargo.lock
crates/starknet_class_manager/Cargo.toml
crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs
crates/starknet_sierra_multicompile_types/src/lib.rs

The `ClassHashStorage` (mapping of `class_hash ->
executable_class_hash`) is local for now; will move to over-`mdbx` soon.

feat(starknet_class_manager): implement FS-based class storage

---

crates/papyrus_storage/src/class_hash.rs
crates/papyrus_storage/src/class_hash_test.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/lib.rs

Will act as the atomic marker of a class, indicating its existence in the class manager.

feat(papyrus_storage): add class hash to executable class hash table

---

crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/entry_point.rs

**Stack**:
- #3657
- #3647
- #3646
- #3644
- #3643 ⬅

feat(blockifier): version bound accounts: add class_hash to DeprecatedSyscallHintProcessor

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_l1_provider/src/l1_provider.rs

- Every propose/validate session has to begin with a `start_block` call that sets the l1 provider inner state for proposition/validation.
- Whenever a block is committed, `commit_block` must be called in order to remove all txs that were committed from the buffers.
TODOS:
1. commit_block: send to L1 provider the _committed_ l1_handler tx hashes.
2. Error handling for start_blocks.

feat(starknet_batcher): support l1 provider {commit,start}_block

---

crates/papyrus_protobuf/build.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus/consensus.proto
crates/papyrus_protobuf/src/proto/p2p/proto/mempool/transaction.proto
crates/papyrus_protobuf/src/proto/p2p/proto/sync/transaction.proto

- **refactor(papyrus_protobuf): add converters for new transaction messages**
- **refactor(papyrus_protobuf): move consensus.proto to a different folder and added ConsensusTransaction**

refactor(papyrus_protobuf): mv consensus.proto to new folder and add ConsensusTransaction

---

Cargo.lock
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/lib.rs
crates/starknet_l1_provider/Cargo.toml

Will be used soon in the l1 scraper, which compares block hashes of specific block numbers in order to detect L1 reorgs.

feat(papyrus_base_layer): add `l1_block_at`

---

crates/papyrus_protobuf/src/converters/transaction.rs
crates/papyrus_protobuf/src/lib.rs
crates/papyrus_protobuf/src/transaction.rs
crates/starknet_api/src/transaction.rs

- **refactor(papyrus_protobuf): add converters for new transaction messages**
- **chore(papyrus_protobuf): fix CR comments**
- **chore(papyrus_protobuf): fix CR comments round 2**
- **refactor(papyrus_protobuf): move to-be-deleted converters to a different module**
- **refactor(papyrus_protobuf, starknet_api): move DeclareTransactionV3Common to starknet_api**

refactor(papyrus_protobuf, starknet_api): move DeclareTransactionV3Common to starknet_api

---

crates/starknet_l1_provider/src/l1_scraper.rs

While equivalent, the last processed is not + 1, it is only the scraping that should _start_ from + 1 of the previous value.

refactor(starknet_l1_provider): cleanup last processed counter

---

crates/papyrus_base_layer/src/lib.rs
crates/starknet_l1_provider/src/l1_scraper.rs
crates/starknet_sequencer_node/src/components.rs

Make scraper track also the last processed block hash, in addition to number.
Whenever the scraper is about to start scraping again, check if the last processed block number:
1. Still exists.
2. Fetch it's current block_hash on L1, and compare to the block_hash saved after the last scraping ended. If either of the above checks fail, then this means an L1 reorg has occured, so the infra should crash the provider and initiate the provider/scraper startup flow.

chore(starknet_l1_provider): add l1-reorg error

---

crates/papyrus_rpc/src/v0_8/api/mod.rs
crates/papyrus_rpc/src/v0_8/broadcasted_transaction_test.rs
crates/papyrus_rpc/src/v0_8/transaction.rs

according to spec
https://github.com/starkware-libs/starknet-specs/blob/28ad3f56c147967b63ecfc78db5f4ba1df993e05/api/starknet_api_openrpc.json#L3484

refactor(papyrus_rpc): add l1_data_gas to ResourceBoundsMapping according to V08

---

crates/starknet_integration_tests/tests/end_to_end_flow_test.rs

This adds a HashMap to cache messages coming in as the proposal in the end to end flow test. It replaces the need to have a StreamHandler, but still prevents the situation that sometimes fails the test because the first message isn't the first to arrive through the network.

fix(consensus): add message cache to end to end test

---

crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs

chore(blockifier): rename execution_tast_output feild 'writes' to state_diff'

---

scripts/named_todos.py

I used a try/catch with a generic Exception because I am re-raising it. I just want to know which file caused the error. 
One case that I found was when I accidentally had a binary file in the PR. It could not be parsed so the script crashed and I had to guess which file caused it.

chore(ci): print filename in case of error in todo_checker

---

config/papyrus/default_config.json
config/sequencer/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_p2p_sync/src/client/block_data_stream_builder.rs
crates/papyrus_p2p_sync/src/client/class_test.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/papyrus_p2p_sync/src/client/transaction_test.rs

split wait period for new data into 2 configs.
when p2p_sync waits for a dependency protocol to advance, it waits for
wait_period_for_other_protocol duration.
fixes the client tests using this config accordingly.

refactor(papyrus_p2p_sync): add wait period for other protocol

---

crates/blockifier/src/bouncer_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transaction_execution.rs

chore(blockifier): remove fn into_keys, fn keys is used instead, created in PR #3580

---

config/papyrus/default_config.json
config/sequencer/default_config.json
crates/papyrus_node/src/config/pointers.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/starknet_consensus/src/config.rs
crates/starknet_consensus_manager/src/config.rs
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_integration_tests/src/utils.rs
crates/starknet_sequencer_node/src/config/node_config.rs

Remove some fields that were on ConsensusConfig that were no longer needed.

chore(consensus): remove some fields from ConsensusConfig

---

crates/starknet_class_manager/src/class_manager.rs
crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/lib.rs

This is required to allow it to act as a concurrent component, according to the current design.
To avoid requiring `Clone` on all future implementations, I manually implemented it for `FsClassStorage`. If we decide to stick to this design longterm, it can be demanded and derived. I believe `Clone` is a stonger requirement than needed for concurrency, so made the minimal easy-to-refactor change possible.

feat(starknet_class_manager): make class manager `Clone`able

---

config/papyrus/default_config.json
config/sequencer/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/starknet_consensus/src/config.rs
crates/starknet_consensus_manager/src/config.rs
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_integration_tests/src/flow_test_setup.rs

Remove some constants that were used as network parameters and use the config fields instead. 
Adds one parameter, `broadcast_buffer_size` to `ConsensusManagerConfig`.

chore(consensus): move some network parameter consts into config

---

crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs

Ayelet is working on removing NonzerGasPrice, a lot of things gonna change..
so these changes are temporary.

feat(consensus): send BlockInfo from proposer

---

Cargo.lock
crates/papyrus_state_reader/Cargo.toml
crates/papyrus_state_reader/src/papyrus_state.rs
crates/starknet_class_manager_types/src/lib.rs

Chose this simpler option to implement, instead of making Papyrus state generic by `CR: CasmReader` trait, since it would require cloning `mdbx` resources, which is flaky working with PyO3.
After `native_blockifier` is deprecated, the client should become non-`Option` and Papyrus state (in the new Batcher) should always be initialized with a concrete instance.

feat(blockifier): integrate Casm read from class manager client

---

crates/starknet_class_manager/src/class_manager_test.rs
crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs

Temp. dirs. should outlive test storage objects (without them implicitly creating those dirs.), and removed once tests are finished. Used `tempfile::TempDir`'s `Drop` trait implementation to achieve this.

refactor(starknet_class_manager): use `tempfile::TempDir` drop quality properly

---

crates/starknet_integration_tests/src/state_reader.rs

First steo towards extracting all the classes outside `initialize_papyrus_test_state` so we can write them to the class manager storage.

refactor(starknet_integration_tests): extract test contracts

---

crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs

Still unused.
This is prep. for Cairo0 and Cairo1 API separation (in addition to a unified `get_executable`, as today). This separation will allow more natural use of the class manager throughout its clients: in most cases we know if the given class hash originates from a Cairo0/1 class.

feat(starknet_class_manager): add `get_deprecated_class` to `ClassStorage` trait

---

crates/starknet_mempool_p2p/src/runner/test.rs

- **fix(papyrus_test_utils): generate random values for resource bounds test instance**
- **fix(starknet_mempool_p2p): use random tx in runner tests**

fix(starknet_mempool_p2p): use random tx in runner tests

---

crates/papyrus_p2p_sync/src/server/mod.rs
crates/papyrus_p2p_sync/src/server/test.rs
crates/papyrus_state_reader/src/papyrus_state.rs
crates/starknet_api/src/transaction_hash_test.rs
crates/starknet_batcher/src/reader_with_class_manager.rs
crates/starknet_batcher/src/reader_with_class_manager_test.rs
crates/starknet_class_manager/src/class_manager.rs
crates/starknet_class_manager/src/class_manager_test.rs
crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs
crates/starknet_class_manager/src/communication.rs
crates/starknet_class_manager_types/src/lib.rs
crates/starknet_class_manager_types/src/transaction_converter.rs
crates/starknet_consensus_orchestrator/src/cende/central_objects.rs
crates/starknet_consensus_orchestrator/src/cende/central_objects_test.rs
crates/starknet_consensus_orchestrator/src/cende/mod.rs
crates/starknet_gateway/src/sync_state_reader.rs
crates/starknet_gateway/src/sync_state_reader_test.rs

Instead of an error variant. For two reasons:
1. `Option` is easier to streamline through abstraction layers; there are quire a few of those in the class manager E2E flow.
2. A class not found flow might be expected at times, it's more idiomatic to leave the decision of how to handle this to the caller, who has more context.

fix(starknet_class_manager): embed class-not-found flow in `Option` return type

---

crates/starknet_l1_provider/src/l1_provider.rs

L1 reorg handled by scraper triggering a reset via the infra. L2 reorg not supported yet, but will likely be similar.

chore(starknet_l1_provider): remove stale API

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/constants.rs
crates/papyrus_base_layer/src/eth_events.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/test_utils.rs
crates/starknet_l1_provider/Cargo.toml
crates/starknet_l1_provider/src/l1_scraper_tests.rs

Use alloy + features instead of individual crates to consolidate
versioning.
There are no logic changes, only import changes.
Warning: Alloy has tons of features; don't activate features greedily; otherwise, our compilation time will suffer.

refactor(papyrus_base_layer): consolidate alloy crates

---

crates/papyrus_network/src/network_manager/metrics.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/starknet_consensus_manager/Cargo.toml
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_mempool_p2p/src/lib.rs
crates/starknet_sequencer_metrics/src/metric_definitions.rs
crates/starknet_state_sync/src/runner/mod.rs

- **refactor(papyrus_network): require network mamanger metrics when constructing nm**
- **refactor(papyrus_network): clean up metrics tracking**
- **feat(papyrus_network): add broadcast and sqmr metrics structs**

feat(papyrus_network): add broadcast and sqmr metrics structs

---

crates/starknet_class_manager/src/class_manager_test.rs
crates/starknet_class_manager/src/class_storage.rs

Added a test that failed before the fix.

fix(starknet_class_manager): fix `get_executable` to fallback to deprecated

---

crates/starknet_integration_tests/src/bin/sequencer_node_end_to_end_integration_tests/positive_flow_integration_test.rs
crates/starknet_integration_tests/src/integration_test_setup.rs
crates/starknet_integration_tests/src/node_setup.rs
crates/starknet_integration_tests/src/sequencer_manager.rs

**Stack**:
- #4140
- #4078
- #4064
- #4062 ⬅

chore(starknet_integration_tests): add support for specifying a costum config dir path

---

Cargo.lock
crates/starknet_consensus_orchestrator/Cargo.toml

Seems the standard is to use rtest to create cases

chore(starknet_consensus_orchestrator): remove unused test-case dependency

---

Cargo.lock
crates/starknet_class_manager/Cargo.toml
crates/starknet_class_manager/src/class_manager_test.rs
crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs
crates/starknet_class_manager/src/communication.rs
crates/starknet_integration_tests/src/state_reader.rs
crates/starknet_sierra_multicompile_types/src/lib.rs

Particularly, only allow creating a raw class through serializing a Sierra/Casm object; raw new isn't allowed.
Also, removed overloading of `TryFrom` trait for deprecated class.

refactor(starknet_class_manager): encapsulate serde logic in `RawClassData<T>`

---

crates/starknet_batcher/Cargo.toml
crates/starknet_batcher/src/block_builder.rs
crates/starknet_batcher/src/block_builder_test.rs

Avoid deadlock that is caused by waiting server to respond while blocking the executor

fix(starknet_batcher): run execution inside spawn_blocking

---

Cargo.lock
crates/starknet_integration_tests/Cargo.toml
crates/starknet_integration_tests/src/bin/sequencer_simulator.rs
crates/starknet_integration_tests/src/lib.rs
crates/starknet_integration_tests/src/sequencer_simulator_utils.rs

commit-id:9e5db078
---
**Stack**:
- #4145
- #4032 ⬅

feat(starknet_integration_tests): sequencer simulator binary

---

crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs

Only atomic marker is set, no class files exist; class should be considered nonexistent (`Ok(None)`, no error).

test(starknet_class_manager): test partial write

---

crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/class_storage_test.rs

Class files are fully written, no atomic marker (meaning, class is considered as nonexistent).

test(starknet_class_manager): test class partial write

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_batcher/src/block_builder.rs
crates/starknet_batcher/src/block_builder_test.rs
crates/starknet_batcher/src/test_utils.rs

Will soon add `accepted_l1_tx_hashes` into this struct, for use in `l1_provider.commit_block`
Only EXTRACT + getter, otherwise no logic changes.

refactor(starknet_batcher): pack metadata in exec artifacts

---

crates/starknet_batcher/src/transaction_provider.rs
crates/starknet_batcher/src/transaction_provider_test.rs
crates/starknet_l1_provider_types/src/lib.rs

The new error message prints as:
```
L1Handler transaction validation failed for tx with hash 0x11faf080dfd62a9505a328e1f86c7e9e60e9752d9e18ddea5af46f8debf5205 status ConsumedOnL1OrUnknown
```

chore(starknet_batcher): fix error message on transaction provider error on l1 validation

---

crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs

This was leftover for testing purposes. Since blockinfo is an external input it can be invalid.

fix(starknet_consensus_orchestrator): remove panic if block info invalid

---

Cargo.lock
crates/starknet_sequencer_metrics/Cargo.toml
crates/starknet_sequencer_metrics/src/bin/sequencer_dashboard_generator.rs
crates/starknet_sequencer_metrics/src/dashboard_definitions.rs

**Stack**:
- chore(starknet_sequencer_metrics): add dashboard dump test #4285
- chore(starknet_sequencer_metrics): update dashboard serde #4284
- chore(starknet_sequencer_metrics): update dashboard dump binary #4283 ⬅

chore(starknet_sequencer_metrics): update dashboard dump binary

---

Cargo.lock
crates/papyrus_state_reader/Cargo.toml
crates/papyrus_state_reader/src/papyrus_state.rs

This is the proper way to call async code from sync code, that runs on a `tokio` runtime to begin with.

fix(blockifier): read classes through `tokio::Runtime#block_on`

---

config/sequencer/default_config.json
crates/starknet_class_manager/src/config.rs
crates/starknet_integration_tests/src/state_reader.rs
crates/starknet_sierra_multicompile/src/lib.rs
crates/starknet_sierra_multicompile_types/src/lib.rs

Improved storage directory names
Used JSON writer with whitespaces for easy class (human) read; the JSON format is quite heavy as it is, I prefer for those files to be readable for debugging if necessary

fix(starknet_class_manager): small fixes to class manager

---

crates/papyrus_state_reader/src/papyrus_state.rs

Still requires a proper elegant fix, added a TODO.

fix(blockifier): fix deprecated Casm read to optional

---

Cargo.lock
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/config/mod.rs
crates/starknet_consensus/src/types.rs
crates/starknet_consensus_manager/src/config.rs
crates/starknet_consensus_orchestrator/Cargo.toml
crates/starknet_consensus_orchestrator/src/config.rs
crates/starknet_consensus_orchestrator/src/lib.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_integration_tests/src/utils.rs

It was previously in `starknet_consensus/src/types.rs` which is where the ConsensusContext definition lives. But it is a specific implementation and should go in the orchestrator crate.

feat(starknet_consensus_orchestrator): move ContextConfig to config module

---

crates/starknet_l1_provider/Cargo.toml

We activated starkent_api's testing flag under dev-dependencies which takes effect
for test, but was not activated under the testing flag

fix(starknet_l1_provider): fix dependencies for l1 handler

---

crates/starknet_batcher/src/block_builder_test.rs

- single source of truth for failures, which also helps with
duplication.
- no unnecessary clones and allocations.
- use invoke_tx_args macro, which does the same thing as previous code
with less code.

refactor(starknet_batcher): improve failed tx handling in test

---

crates/starknet_batcher/src/block_builder_test.rs
crates/starknet_batcher/src/test_utils.rs

- Extends existing logic, by adding one successful and one failed l1
handler tx to the list of txs.
- Add `Default` for tests that only need that.

chore(starknet_batcher): add l1 handlers to block builder test

---

crates/starknet_mempool/src/mempool.rs

When iterating the vector, it's preferable to calculate the cutoff time once for better performance and determinism (time is fixed throughout the iteration).
Time condition was swapped to support style guidance (https://github.com/rust-lang/rust-analyzer/blob/master/docs/book/src/contributing/style.md#comparisons).

chore(starknet_mempool): calc cutoff time once when pruning transactions

---

crates/blockifier/resources/versioned_constants_0_13_5.json
crates/blockifier/src/versioned_constants.rs

feat(blockifier): add deploy call data factor to vc

---

crates/blockifier/src/execution/native/syscall_handler.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscall_base.rs
crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs
crates/blockifier/src/utils.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

fix(blockifier): cherry pick conflicts
feat(blockifier): gas cost enum

feat(blockifier): gas cost enum

---

crates/starknet_consensus_orchestrator/src/config.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context_test.rs

There are a few fields that get copied from the ContextConfig into the SequencerConsensusContext struct itself. 
Instead, context now keeps a copy of the config and when needed, it refers to the fields of the config. 
This is useful because I'm collecting more config items and copying all of them into the context itself is just bloat.

chore(consensus): context needs to have a copy of its own config

---

crates/blockifier/resources/blockifier_versioned_constants_0_13_0.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_1.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_1_1.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_2.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_2_1.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_3.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_4.json
crates/blockifier/resources/blockifier_versioned_constants_0_13_5.json
crates/blockifier/resources/blockifier_versioned_constants_0_14_0.json
crates/blockifier/src/blockifier_versioned_constants.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/starknet_integration_tests/tests/end_to_end_flow_test.rs

All VC should take the deprecated resources, except 0.14.0

chore(blockifier): remove deprecated resources from VC

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_batcher/src/block_builder.rs
crates/starknet_batcher/src/block_builder_test.rs
crates/starknet_batcher/src/test_utils.rs

- Removed Eq because `TransactionExecutionInfo` doesn't support it
recursively into inner types for some reason.
- No longer passing the entire metadata object into `commit_proposal_and_block`
due to ownership issues since execinfo isn't used there and is used
afterwards.

refactor(starknet_batcher): move execution info into execution data

---

crates/starknet_consensus/src/stream_handler.rs
crates/starknet_consensus/src/stream_handler_test.rs

This will allow us to simplify the test setup.

refactor(consensus): make the outbound sender fully generic

---

crates/starknet_consensus/src/manager.rs
crates/starknet_consensus/src/manager_test.rs

Avoid wasting time when we are lagging and sync already knows the decision

refactor(consensus): check sync before running consensus

---

crates/starknet_consensus/src/stream_handler_test.rs

Goals:
1. Utilize new genericiy to just use simple channels instead of using mock_register_broadcast_topic
2. Tests should try to use only the public API (ie messages in and out)
- This may be broken later when testing how malicious cases are defended

refactor(consensus): begin rewriting tests for the stream handler

---

Cargo.lock
crates/papyrus_p2p_sync/src/client/test.rs
crates/starknet_api/Cargo.toml
crates/starknet_api/src/transaction.rs

This also allows me to remove the into/from Vec<u8> of TransactionHash (the next PR).

feat(starknet_api): allow randomly generated tx hashes for tests

---

crates/papyrus_network/src/network_manager/test_utils.rs

Should be large enough for tests. I want this smaller in order to fill it up for a test
(next PR)

refactor(papyrus_network): shrink test buffer size from 10k to 1k

---

crates/starknet_api/Cargo.toml

`starknet_infra_utils` should not be optional.
It was mistakenly marked as optional and only enabled via the `testing` feature, causing missing dependency issues. Now it's always included to prevent build failures.

fix(starknet_api): remove starknet_infra_utils from testing feature and optional dependencies

---

crates/starknet_consensus/src/manager.rs
crates/starknet_consensus/src/manager_test.rs

At the end of each height, make sure to check the inbound streams to avoid a backlog building up

fix(consensus): handle streams in a timely manner

---

crates/starknet_l1_gas_price/src/l1_gas_price_provider.rs
crates/starknet_l1_gas_price/src/l1_gas_price_provider_test.rs

Fix a bug where the provider would crash if the first block number it got was not zero.

fix(starknet_l1_gas_price): allow gas price provider to start at any height

---

crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central_sync_test.rs
crates/papyrus_sync/src/sync_test.rs

- **feat(papyrus_storage): add compiler backward compatibility marker**
- **fix(papyrus_sync): make first_block_to_compile_from persistent by using marker**

fix(papyrus_sync): make first_block_to_compile_from persistent by using marker

---

crates/papyrus_sync/src/lib.rs

- **feat(papyrus_storage): add compiler backward compatibility marker**
- **fix(papyrus_sync): make first_block_to_compile_from persistent by using marker**
- **fix(papyrus_sync): send to class manager before writing classes to storage**

fix(papyrus_sync): send to class manager before writing classes to storage

---

crates/starknet_sierra_multicompile/build.rs

This should be coupled (also by test) with bumping the version in `Cargo.toml`. Will come next; done separately to unblock integration efforts with centralized sequencer.

feat(starknet_sierra_multicompile): bump compiler binary version

---

Cargo.lock
crates/blockifier_test_utils/Cargo.toml
crates/blockifier_test_utils/src/cairo_compile.rs
crates/starknet_infra_utils/Cargo.toml
crates/starknet_infra_utils/src/cairo_compiler_version.rs
crates/starknet_infra_utils/src/lib.rs

Few remarks:
- No code change, only move.
- I put the new file under "testing" feature since `Cargo.toml`-parsing code should not be ran in production.
- This is prep. for testing compiler version alignment between `Cargo.toml` and `build.rs`; should also be done for `cairo-native`compiler.

refactor(starknet_infra_utils): move `cairo1_compiler_version` and its transitive closure

---

crates/starknet_batcher/src/batcher.rs
crates/starknet_batcher/src/batcher_test.rs
crates/starknet_l1_provider/src/l1_provider.rs
crates/starknet_l1_provider_types/src/errors.rs

Also ONE unpacking change in the definition of current_height var

refactor(starknet_l1_provider): rename for readability

---

crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central_sync_test.rs
crates/papyrus_sync/src/sync_test.rs

- **fix(papyrus_sync): send casm to class manager before writing casm to storage**
- **fix(papyrus_sync): write all casms including backward compatible to storage**
- **fix(papyrus_sync): perform storage writes in spawn blocking**

fix(papyrus_sync): perform storage writes in spawn blocking

---

Cargo.lock
crates/starknet_consensus_manager/src/consensus_manager.rs
crates/starknet_consensus_orchestrator/Cargo.toml
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/starknet_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/starknet_l1_gas_price_types/src/lib.rs

I added price_oracle_client as an Option in the context, to allow time for preparing e2e integration tests and flow tests using a fake HTTP server

feat(starknet_consensus_orchestrator): get eth->fri rate from price_oracle_client in block building

---

crates/starknet_class_manager/src/class_manager.rs
crates/starknet_class_manager/src/class_storage.rs
crates/starknet_class_manager/src/lib.rs
crates/starknet_class_manager/src/metrics.rs

refactor(starknet_class_manager): move metric code to its own module

---

crates/starknet_consensus/src/stream_handler_test.rs

I've expanded the new test versions to cover inbound messages to the stream handler. We can now safely delete the old tests.

feat(consensus): update stream handler tests

---

crates/starknet_consensus/src/types.rs

This will likely be relevant when the validator set can change and retrieving it is
an async process.

fix(consensus): add TODO to fn proposer in the context

---

crates/starknet_l1_provider/src/test_utils.rs
crates/starknet_l1_provider/src/transaction_manager.rs

No need to save the transaction itself
Note: insertion to this collection hasn't been added yet, will be added
in the next PR.

chore(starknet_l1_provider): make committed hashset

---

crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/test_utils.rs
crates/starknet_l1_provider/src/transaction_manager.rs

Saving the committed txs on commit was missing, added a test for the
race between a tx coming from another node before it was received from
the scraper.

chore(starknet_l1_provider): save committed txs

---

crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class/utils.rs
crates/starknet_os/src/hints/vars.rs

feat(starknet_os): copy get_deprecated_contract_class_struct from moonsong's repo
feat(starknet_os): implement LoadCairoObject trait for DeprecatedContractClass

feat(starknet_os): implement LoadCairoObject trait for DeprecatedContractClass

---

crates/starknet_os/src/hints/error.rs
crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class/implementation.rs
crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class/utils.rs
crates/starknet_os/src/hints/vars.rs

feat(starknet_os): copy load_deprecated_class_inner hint implementation from moonsong's repo
feat(starknet_os): implement load deprecated class inner hint

feat(starknet_os): implement load deprecated class inner hint

---

crates/blockifier/src/bouncer.rs

The fields were reordered to align with the struct definition

refactor(blockifier): reorder struct fields init

---

crates/starknet_l1_provider/tests/startup_flows.rs

Use the client, rather than direct l1_provider calls.
This is relevant here because the async task is already using the
(mock) client, and making the test use the provider directly while the
sync task is using the client will be too different from prod code.
Also fixed an incorrect copy-paste code remark.

fix(starknet_l1_provider): flow test consistency

---

crates/starknet_l1_provider/src/bootstrapper.rs
crates/starknet_l1_provider/src/test_utils.rs
crates/starknet_l1_provider/tests/startup_flows.rs

Also add util for flushing the fake l1 client: its currently just
buffering the calls it gets, and needs a manual flush.

chore(starknet_l1_provider): add lazy sync height test

---

crates/starknet_l1_provider/src/l1_scraper_tests.rs

Makes it easier to debug (tooltips show the value)

refactor(starknet_l1_provider): use consts

---

crates/starknet_l1_provider/src/l1_scraper_tests.rs

Right now we're duplicating this util, until we decide on a central
super-lean crate for sharing common stuff

chore(starknet_l1_provider): not related to mempool

---

Cargo.lock
crates/starknet_integration_tests/Cargo.toml
crates/starknet_integration_tests/src/flow_test_setup.rs
crates/starknet_integration_tests/src/utils.rs
crates/starknet_integration_tests/tests/end_to_end_flow_test.rs

Check success on aggregated txs instead of per height

feat(starknet_integration_tests): refactor e2e flow test

---

crates/starknet_l1_provider/src/l1_provider.rs
crates/starknet_l1_provider/src/l1_provider_tests.rs
crates/starknet_l1_provider/src/transaction_manager.rs

If the commit is likely a dup only log error: we're currently
dup-checking by testing if the given commit hashes have already
appeared, this conservatively implies a dup, but can also be a
commit-block with a subset of tx hashes than the previous one.
This is simpler than saving a commit history, which isn't warranted for
this feature alone.
If the commit is not a dup (if it contains new uncommitted tx_hashes):
return an error like before.

feat(starknet_l1_provider): bootstrap debug duplicated commit-block

---

crates/starknet_gateway/src/sync_state_reader.rs
crates/starknet_gateway/src/sync_state_reader_test.rs

- **feat(starknet_state_sync): add client functionality for is_class_declared_at without impl in server**
- **feat(starknet_state_sync): implement is_class_declared_at**
- **feat(starknet_gateway): in SyncStateReader::get_compiled_class check with sync if class is declared**

feat(starknet_gateway): in SyncStateReader::get_compiled_class check with sync if class is declared

---

crates/starknet_sequencer_infra/src/trace_util.rs

File comes instead of module name, which is less informative. Goal is to trivially find the line logging came from.
Changes from:
`2025-03-30T10:53:27.018Z  INFO starknet_sequencer_infra::trace_util: Tracing has been successfully initialized.`
To:
`2025-03-30T10:53:27.018Z  INFO crates/starknet_sequencer_infra/src/trace_util.rs:37: Tracing has been successfully initialized.`

feat(starknet_sequencer_infra): add file and line number to log format

---

crates/apollo_http_server/src/deprecated_gateway_transaction.rs
crates/apollo_http_server/src/errors.rs
crates/apollo_http_server/src/http_server.rs
crates/starknet_api/src/compression_utils.rs

Note:
The base branch for this PR was `yael/support_rest_api` when it was created.
Now it is over main
This PR no longer contains the code of #5325.

chore(apollo_http_server): try from deprecated gateway declare tx

---

crates/apollo_l1_gas_price/src/l1_gas_price_provider.rs
crates/apollo_sequencer_node/src/components.rs

This allows integration tests to pass until we add Anvil transactions that the scraper can use in the tests.

fix(apollo_integration_tests): allow L1 gas price provider to run without scraper in the tests

---

crates/apollo_consensus/src/single_height_consensus.rs
crates/apollo_consensus/src/state_machine.rs
crates/apollo_protobuf/src/consensus.rs

This will be used to dump the state of consensus due to the debug dump command.
Using Json serialization since it is readable, like Debug, but also can make
experimentation easier by loading in the state via deserialization.

chore(consensus): add Serialize and Deserialize traits to SHC and SM

---

crates/apollo_sierra_multicompile/src/command_line_compiler.rs

This reverts commit 9dec00c0377a8c02c235b9652065d729c6aaaa9f.

Revert "chore(blockifier): limit casm compilation memory usage (#5426)"

---

crates/apollo_l1_provider/src/bootstrapper.rs
crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/l1_scraper.rs
crates/apollo_l1_provider/src/lib.rs
crates/apollo_l1_provider_types/src/errors.rs

Incomplete, still needs infra to be able to respawn on fail.
Also needs infra to be able to process fatal errors, instead of
panicking.

feat(apollo_l1_provider): force provider/scraper mutual restart

---

scripts/sequencer_integration_test.sh

No longer necessary as of: 75705a572214e1712f28ac6b1b69d33edd6d2f5c,
since the exit only applies to node code, but not test code, which now
is dropped gracefully.
The anvil error was carried over due to the sequencer not terminating
(once it did, so did anvil which terminates on drop).
Note that the hook in the above commit still requires to be removed at
some point and replaced by explicit handling of `JoinHandle`s, since it
currently prevents destructors in the node from being run on panic
(which can leak resources).

chore(apollo_integration_tests): remove killall

---

crates/apollo_l1_provider/src/l1_scraper.rs

This is an incomplete solution, as it is possible for a query itself to be problematic
(e.g. too large)

fix(apollo_l1_provider): sleep and retry on BaseLayerError

---

.github/workflows/blockifier_compiled_cairo.yml

Ensure the compatibility test runs when the Cairo compiler is upgraded. A new lightweight file now holds the compiler version (along with a check for alignment with `Cargo.toml`). The workflow is updated to trigger on changes to this file instead of the full `Cargo.toml`.

fix(ci): trigger compatibility test on Cairo compiler version update

---

crates/apollo_l1_provider/src/l1_scraper.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/lib.rs

Add manual `PartialEq` + `to_string` for external non-`PartialEq` types.

chore(papyrus_base_layer): add "PartialEq" to base layer error

---

Monitoring/sequencer/dev_grafana.json
crates/apollo_dashboard/src/dashboard_definitions.rs
crates/apollo_state_reader/src/metrics.rs

clamp_min()
clamp_min(v instant-vector, min scalar) clamps the sample values of all elements in v to have a lower limit of min.
while max(v instant-vector)  returns the max value of v.
I noticed the problem in the Grafana Itai sent
[![???](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/default-memes/questionmarks.gif)](https://app.graphite.dev//settings/meme-library?org=starkware-libs)

fix(apollo_state_reader): fix the query definition

---

crates/apollo_l1_provider/src/lib.rs

Only `SendMessageToL2` is supported at the moment, no need to scrape it.

fix(apollo_l1_provider): don't scrape unsupported events

---

crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/l1_scraper.rs
crates/apollo_l1_provider_types/src/errors.rs

Currently the scraper only scraper `SendMessageToL2` events, so this
shouldn't occur until we start supporting them.
However, this constitutes an input error until then.
Using a constructor type because `Event` is a big obj and makes the
enum too fat

chore(apollo_l1_provider): add `UnsupportedL1Event` error

---

crates/apollo_l1_provider_types/src/errors.rs
crates/apollo_l1_provider_types/src/lib.rs
crates/papyrus_base_layer/src/lib.rs
crates/starknet_api/src/core.rs

Debug is spammy, especially in objects with dynamic fields like
`calldata` which is omitted from Display.

refactor(apollo_l1_provider): use Display instead of Debug in error

---

crates/apollo_batcher/Cargo.toml
crates/apollo_batcher/src/block_builder.rs
crates/apollo_infra_utils/src/tracing.rs
crates/blockifier/src/blockifier/transaction_executor.rs

Before:
three lines:
```
Transaction execution has failed:
0: Error in the called contract (contract address: 0x0000000000000000000000000000000000000000000000000000000000000000, class hash: 0x0000000000000000000000000000000000000000000000000000000000000000, selector: 0x0000000000000000000000000000000000000000000000000000000000000000):
Execution failed due to recursion depth exceeded.
```
After:
One line:
```
Transaction execution has failed:       0: Error in the called contract (contract address: 0x0000000000000000000000000000000000000000000000000000000000000000, class hash: 0x0000000000000000000000000000000000000000000000000000000000000000, selector: 0x0000000000000000000000000000000000000000000000000000000000000000):     Execution failed due to recursion depth exceeded.
```
Also, note …

chore(blockifier): create log compatible execution error display

---

crates/apollo_compile_to_casm/src/constants.rs
crates/apollo_compile_to_native/src/constants.rs

Deleted unnecessary comment (version is tested).
Made version constants `pub`lic; better than marking them as dead code. Both are used in build scripts and unit test, so to the compiler they seem unused.

fix(apollo_compile_to_casm,apollo_compile_to_native): small cleanup

---

crates/apollo_integration_tests/src/utils.rs
crates/apollo_integration_tests/tests/common/mod.rs
crates/apollo_integration_tests/tests/end_to_end_flow_test.rs
crates/apollo_integration_tests/tests/test_many.rs

Changes:
ONLY MOVE, no logic changes. Break up the rstest
parameterization into two separate files inside `tests/`, which
corresponds to two `cargo`-style integration tests.
Also moved a bunch of _single-use_ functions from utils.rs into the
corresponding test file.
Motivation:
* https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html#integration-testing.
Every file in `tests/` is run as a separate binary by cargo, without
parallelization.
However, multiple tests in the same file in `tests/` are still parallelized by cargo,
which is what `rstest` parametrization generates.
* This is the best way to run flow tests (and also integration) for
a bunch of reasons: we don't want stuff in one test contaminating the
other, we want to use fixed (configurable) ports for things …

refactor(apollo_integration_tests): only EXTRACT, to run flow tests sequentially

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs

Main motivation: adds the `Asserter` class that allows one to mock Anvil
in unit tests (will be used in future PRs).
Changes:
- using `default` instead of `new` since `new` now adds some extra stuff
to the provider we don't need.
- Type of the provider is simplified (unrelated to the previous bullet).
- Block query simplified --- the default of the query is `only_header` now,
and making it non-only-header is done with a builder rather than a bool arg.

chore(papyrus_base_layer): bump Anvil

---

crates/apollo_compile_to_casm/src/compile_test.rs
crates/apollo_compile_to_native/src/compile_test.rs
crates/apollo_infra_utils/src/dumping.rs
crates/apollo_node/src/config/config_test.rs
crates/papyrus_node/src/config/config_test.rs

No need to do this in the fied tests; or at all (it's a persistent change throughtout the program).
There are additional usages, which are less trivial to fix.

fix(apollo_compile_to_casm,papyrus_node): do not change current dir

---

crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs

Examples of both logs:
Node id 2 part 0: 2025-04-29T08:36:57.764Z  WARN run_consensus:run_height:consensus_build_proposal: crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs:1025: Built an empty proposal. validator_id=0x0000000000000000000000000000000000000000000000000000000000000066 height=2 proposal_id=1 round=0
Node id 1 part 0: 2025-04-29T08:36:57.775Z  WARN run_consensus:run_height:consensus_validate_proposal: crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs:1380: Validated empty proposal. validator_id=0x0000000000000000000000000000000000000000000000000000000000000065 height=2 proposal_id=1 round=0

feat(apollo_consensus_orchestrator): add logs for building / validating empty proposals

---

crates/papyrus_base_layer/src/test_utils.rs

A first step in the goal of getting rid of the constant: `DEFAULT_ANVIL_L1_ACCOUNT_ADDRESS`.

test(papyrus_base_layer): organize anvil account addresses

---

crates/apollo_l1_provider/src/l1_scraper_tests.rs

Scraper should not depend on mempool, the information can be retrieved
from anvil anyway.

chore(apollo_l1_provider): remove mempool dep

---

crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/test_utils.rs

* Use mocked anvil, no need to do IO here.
* Deprecate ganache through cargo to prevent future usage
Note: the existing test is basically testing that the configs are mapped
correctly to the correct computations, it's blurring the line between
testing the eip.

chore(papyrus_base_layer): remove ganache usage from test

---

crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs

Already handled for TXs, but wasn't changed for the Fin.

fix(apollo_consensus_orchestrator): dont abort a proposal if the Batcher returns Invalid

---

crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs

We already do this when proposing

chore(apollo_consensus_orchestrator): print the tx hashes for each batch when validating

---

crates/blockifier/src/transaction.rs
crates/blockifier/src/transaction/l1_handler_transaction.rs
crates/blockifier/src/transaction/transactions.rs

In this PR, we create a file called `l1_handler_transaction.rs`. This file should be parallel to `account_transaction.rs` in the same path.
In this PR we create the file and move some functions to that file.
This is towards a greater goal of creating a complete parallel between the files, and moving code out of `transactions.rs`, and later changing some business logic of L1 handler transactions.

chore(blockifier): create a file dedicated to l1 handler txs

---

crates/apollo_l1_provider/src/l1_scraper.rs
crates/papyrus_base_layer/src/eth_events.rs
crates/papyrus_base_layer/src/lib.rs

`MessageToL2CancellationStarted` is mapped to a corresponding
SendMessageToL2 transaction (L1HandlerTransaction) by calculating the tx
hash. This is done later down the pipeline when we convert the current
L1 type into an L2 type. For now lets convert the type to a Starknet API
L1HandlerTransaction, which represents an "external" transaction, and
add the tx_hash calculation when converting into an inner type later on.

chore(papyrus_base_layer): change `MessageToL2CancellationStarted` inner

---

crates/apollo_l1_provider/src/l1_scraper.rs
crates/apollo_l1_provider_types/src/lib.rs

Only MOVE, no logic changes.
Made into a function for testability later, also this is general enough
in order to be decoupled -- from the scraper itself.

refactor(apollo_l1_provider): convert method to function

---

crates/apollo_compilation_utils/src/resource_limits/resource_limits_unix.rs

This change was introduced because previously the message printing was corrupting the compilation process output, interfering with json deserialization.

fix(apollo_compilation_utils): redirect limit setting message to stderr

---

crates/blockifier/src/transaction/l1_handler_transaction.rs

I looked at the history. There is no reason not to clean this up a bit:
I got back into looking in the [blockfier repo](https://github.com/starkware-libs/blockifier/commit/99527a30202264556d100fd41589a1f22f4abdb4)

chore(blockifier): readablity refactor in receipt creation in l1 handler

---

crates/apollo_consensus/src/single_height_consensus.rs
crates/apollo_consensus/src/state_machine.rs

The SHC event logs were printed regardless of whether or not the timeout was ignored,
leading to confusion.

chore(apollo_consensus): improve logs related to timeout

---

crates/blockifier/src/blockifier/transaction_executor.rs
crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs

This will allow using it in threads that will live longer than the block.
---
**Stack**:
- #6569
- #6564
- #6603
- #6563
- #6562
- #6544 ⬅

feat(blockifier): remove lifetime from WorkerExecutor

---

crates/apollo_network/src/network_manager/mod.rs

Updates connection event handling to increment or decrement the connected peers metric only when the first connection is established or the last connection is closed with a peer.

fix(apollo_network): improve peer connection metrics accuracy

---

crates/blockifier/src/concurrency/scheduler.rs
crates/blockifier/src/concurrency/scheduler_test.rs
crates/blockifier/src/concurrency/worker_logic.rs

**Stack**:
- #6683
- #6682
- #6670
- #6654
- #6653 ⬅

refactor(blockifier): return an enum in commit_tx

---

crates/apollo_batcher/src/batcher.rs
crates/apollo_batcher/src/batcher_test.rs
crates/apollo_l1_provider/src/bootstrapper.rs
crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/l1_scraper_tests.rs
crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/src/transaction_manager.rs
crates/apollo_l1_provider_types/src/lib.rs

For consistency with rejected hashes.
Note: batcher treats both committed and rejected as a Set, whereas
SyncBlocks consider committed as a list (like committed used to be in
the provider/batcher).
Note: It no longer makes sense to pass this with a reference, since
there is no deref. Currently keeping it for consistency with rejected.
Will both have their refs removed soon.

chore(apollo_l1_provider): switch committed `HashSet`->`IndexSet`

---

crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/src/transaction_manager.rs

Whenever we see a tx hash in commit-block for a tx we already scraped,
save it in a side buffer instead of deleting it and only storing its
hash (the current behavior).
Initial support for this was added in previous commits, where the
commited-txs collection was changed from hashset of tx_hashes into a map,
that until now only had tx-hash keys without any values (through a
dedicated enum representing this state).
Next commit will add support for the flow in which we see a tx hash in
commit-block and only afterwards scrape the tx.

feat(apollo_l1_provider): save committed txs in sidebuffer

---

crates/apollo_l1_provider/src/soft_delete_index_map.rs

New snapshot code in the l1 provider is iterating over hashsets.
Not deterministic, switching to indexset.

fix(apollo_l1_provider): don't iterate hashset

---

crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/soft_delete_index_map.rs
crates/apollo_l1_provider/src/transaction_manager.rs

Add `is_committed`, which will:
1. Better encapsulate access to committed (will also assist the upcoming refactor).
2. reduce unnecessary allocation and iteration in the now removed `committed_tx_hashes()`.

chore(apollo_l1_provider): optimize commit-check

---

crates/apollo_batcher/src/block_builder.rs
crates/apollo_batcher/src/block_builder_test.rs
crates/apollo_batcher/src/transaction_executor.rs

Preparation for using one WorkerExecutor per block
---
**Stack**:
- #6872
- #6871
- #6825
- #6824 ⬅

feat(blockifier): add TransactionExecutorTrait::abort_block

---

crates/apollo_signature_manager_types/src/lib.rs
crates/starknet_api/src/crypto/utils.rs

Signature service will be generic by it:
- In prod. we'll use a remote cloud KMS
- In dev. we'll use a local key store

feat(apollo_signature_manager_types): define `KeyStore` trait

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscall_executor.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/vm_syscall_utils.rs
crates/starknet_os/src/hint_processor/snos_deprecated_syscall_executor.rs
crates/starknet_os/src/hints/error.rs

refactor(blockifier): invalid syscall selector depracted base error
feat(blockifier, starknet_os): associated basic deprecated syscall error type

refactor(blockifier): invalid syscall selector depracted base error

---

Cargo.lock
crates/apollo_signature_manager/src/lib.rs
crates/apollo_signature_manager_types/Cargo.toml
crates/apollo_signature_manager_types/src/lib.rs

To be used in the `SignatureManagerClient` trait, which appears in the
types crate.
Also:
- Rename to `PeerId` with a lowercase `d`.
- Add c-tor from inner value type `impl From<Vec<u8>>`.

refactor(apollo_signature_manager): move peer ID type to types create

---

crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/src/transaction_manager.rs

Unlikely that the batcher can do anything with "double commit" error
anyway besides panicking as well.

chore(apollo_l1_provider): panic on double commit

---

crates/apollo_l1_provider/src/transaction_manager.rs

Is easier to work with than &mut (borrow checker woes later on).

refactor(apollo_l1_provider): streamling inc/dec for epoch

---

crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/src/transaction_manager.rs

Soon will be moved out of file, thus preventing access of records
not through `Records#with_record()`.

fix(apollo_l1_provider): wrap records with dedicated type

---

Cargo.lock
crates/apollo_consensus_manager/Cargo.toml
crates/apollo_consensus_manager/src/consensus_manager.rs
crates/apollo_consensus_orchestrator/Cargo.toml
crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/apollo_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/apollo_time/Cargo.toml
crates/apollo_time/src/lib.rs
crates/apollo_time/src/time_keeper.rs

TODO(gilad): use everywhere (will be implemented after we finish the
milestone).
Also add `FakeClock` instead of mockall: impl is similar to
the mempool's clock, which will also be converted to use this clock
rather than instants.

apollo_consensus: extract consensus clock into `apollo_time`

---

Cargo.lock
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/eth_events.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
crates/papyrus_base_layer/src/lib.rs

Note that the log object has a block_timestamp field on alloy, but that
isn't guaranteed to be filled and isn't supported yet by infura and
others (it's a new feature on ethereum). Hence using the traditional way
of fetching the block header itself and grabbing the time from it, which
is guaranteed to exist.
Note that this does n_logs rpc calls to infura, one per log, but this is
probably unavoidable at the moment, and also isn't that large given the
small number of l1 handlers we get.

papyrus_base_layer: parse event block timestamps

---

Cargo.lock
crates/apollo_consensus_manager/src/consensus_manager.rs
crates/apollo_consensus_orchestrator/src/build_proposal.rs
crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs
crates/apollo_consensus_orchestrator/src/sequencer_consensus_context_test.rs
crates/apollo_time/Cargo.toml
crates/apollo_time/src/time_keeper.rs

Sleeper trait isn't useful + improve documentation for `sleep_until`.
Next pr will also rename time_keeper.rs -> time.rs

time: revert timekeeper struct

---

crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/src/transaction_manager.rs
crates/apollo_l1_provider/src/transaction_record.rs

- Will soon be used for timelocking new txs.
- Saving this on the payload rather than the record to account for
committed txs which don't have a timestamp if committed by another
node before our node managed to scrape them.

l1: save l1 handler created_at on the payload, still unused

---

.github/workflows/main_pr.yml

Not sure why this action is necessary, but its 2100 timeout is strictly smaller than our longest test.

ci: increase gatekeeper timeout to 1 hour

---

Cargo.lock
crates/apollo_l1_provider/Cargo.toml
crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/src/transaction_manager.rs
crates/apollo_l1_provider/src/transaction_record.rs
crates/apollo_l1_provider_types/src/lib.rs
crates/apollo_time/src/time.rs
crates/papyrus_base_layer/src/eth_events.rs
crates/papyrus_base_layer/src/lib.rs

Note that this is the timestamp of the cancellation-started event, not
the original l1 handler's timestamp

papyrus_base_layer: add timestamp to message cancellation raw events

---

crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_time/src/lib.rs
crates/apollo_time/src/test_utils.rs

Easier to work with than mockall, less boilerplate, also see the test
below that uses `advance`, saves having to override the clock instance.

time: add FakeClock

---

crates/apollo_signature_manager/src/signature_manager.rs
crates/apollo_signature_manager_types/src/lib.rs

For `KeyStore` and `SignatureManager`.
This is an infra. requirement to be able to serve requests concurrently.
It is okay for this service, since it is currently stateless and
lightweight.

feat(apollo_signature_manager): add derive `Clone`

---

crates/apollo_signature_manager/src/lib.rs
crates/apollo_signature_manager/src/signature_manager.rs

This is supposed to be used in all test types (unit through
system/integration), not in prod.
In the effort of prep.-ing the service as a node component, and since
design is still missing re how would this service be built with a remote
KMS (and also no adequate infra. support of dependency injection yet) --
I chose to temporarily use this (local KMS) variant across the node.

feat(apollo_signature_manager): define a local key store service variant

---

Monitoring/sequencer/dev_grafana_alerts.json
crates/apollo_dashboard/src/alert_definitions.rs

- **apollo_dashboard: set pedning duration and evaluation interval for all alerts to 10s**
- **apollo_dashboard: add l1 gas price failure once alert**

apollo_dashboard: add l1 gas price failure once alert

---

crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/test_utils.rs

Also allow `with_{timelocked_,}txs` to be used in tandem.

l1: add testutil for timelocked l1 handlers

---

crates/apollo_dashboard/src/panels/gateway.rs
crates/apollo_dashboard/src/panels/http_server.rs
crates/apollo_dashboard/src/panels/l1_gas_price.rs
crates/apollo_dashboard/src/panels/l1_provider.rs

apollo_dashboard: refactor consensus panels from consts to fns
apollo_dashboard: delete empty lines in consensus panels
apollo_dashboard: delete empty lines in mempool panels
apollo_dashboard: refactor mempool p2p panels from consts to fns
apollo_dashboard: refactor sierra compiler and state reader panels from consts to fns
apollo_dashboard: refactor state sync panels from consts to fns
apollo_dashboard: completion of panels const to fn refactor

apollo_dashboard: refactor consensus panels from consts to fns

---

Cargo.lock
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_base_layer/src/lib.rs
crates/papyrus_base_layer/src/monitored_base_layer.rs

This wrapper is intended to wrap `EthereumBaseLayer`, so that all of its
API calls will be preempted by a health check (`ensure_operational`) of the underlying L1 node
url, hot swapping the base_layer's L1 node if the `L1EndpointMonitor`
has decided to start using a separate L1 Endpoint (e.g. infra vs
alchemy).
Requirement 1: since this health check can modify
the inner L1 node, it must only be done once, at the onset of every API
call.
In particular, inner calls of the base layer API that the base-layer calls by
itself should not trigger the health check --- otherwise, we might have a
single base-layer API call using different L1 nodes internally in
different stages of the call.
This requirement implies a wrapper, since adhering to it internally
inside the `BaseLayerContract` will …

papyrus_base_layer: monitor baselayer health through wrapper

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/entry_point_execution.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/native/entry_point_execution.rs
crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs
crates/blockifier/src/execution/syscalls/syscall_tests/deploy.rs
crates/blockifier/src/execution/syscalls/syscall_tests/emit_event.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_class_hash_at.rs
crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs
crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs
crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs
crates/blockifier/src/execution/syscalls/syscall_tests/replace_class.rs
crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs
crates/blockifier/src/execution/syscalls/syscall_tests/send_message_to_l1.rs
crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs
crates/blockifier/src/execution/syscalls/syscall_tests/storage_read_write.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This commit adds a boolean flag "cairo_native" to call info. This flag is true for any entry
point executed with Cairo Native. Note that when the function `execute_entry_point_call` returns
an error there is currently no way to distinguish between Cairo VM execution and Cairo Native
execution, hence the function `execute_entry_point_call_wrapper` - which handles these cases -
applies the default value to the flag "cairo_native" setting it to false.

feat(blockifier): add a cairo native flag to call info

---

crates/apollo_signature_manager/src/communication.rs
crates/apollo_signature_manager/src/lib.rs

I intend integration to node to be done with the local veriant E2E (the
existing generic server was merged previous to this decision).
Additional thought is needed re using (at least) two types of server:
one with local key store for testing, and the other with a remote
(secure) one for production; or, in other words: for the server to be
generic in key store.

signature: use local signature manager as server

---

crates/papyrus_base_layer/src/monitored_base_layer.rs

This is the main API for this wrapper: it checks liveness of the l1
client and updates the inner "real" base layer with the result.
Subsequent commits will make this wrapper implement the base layer trait
through delegation to the inner base layer.

papyrus_base_layer: implement core of monitored base layer

---

crates/apollo_l1_endpoint_monitor/src/l1_endpoint_monitor_tests.rs
crates/apollo_l1_endpoint_monitor/src/monitor.rs
crates/apollo_l1_endpoint_monitor_types/src/lib.rs
crates/apollo_l1_provider/src/l1_scraper.rs
crates/papyrus_base_layer/src/lib.rs
crates/papyrus_base_layer/src/monitored_base_layer.rs

EXTRACT more of the scraper's startup logic for deciding which l1 block to start
scraping from into a function and rename it.
NO logic changes, just extract.
Motivation: soon the base layer queries will have to use the monitored base layer,
instead of the raw base layer, meaning they need the service to be
running in order to succeed. This hits the known issue of not being able
to depend on external services during construction in components.rs.
Hence, the next commit will make the callsite call this function and
pass the resulting start_block to the scarper's constructor.

l1: extract constructor into function

---

crates/apollo_l1_provider/src/l1_scraper.rs
crates/apollo_l1_provider/src/l1_scraper_tests.rs
crates/apollo_node/src/components.rs

This must be called outside of the scraper, since soon the scraper will
be initialized with a liveness-proxy over the baselayer (L1EndpointMonitor),
rather than the actual `EthereumBaseLayerContract`.
Due to a known limitation of components.rs, sending messages between
services is not possible during initailization, hence we need to do the
raw query using the baselayer at the callsite.
This will be clearer in upcoming commits.

l1: get l1 scraper starting height at callsite

---

crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/transaction_record.rs
crates/apollo_l1_provider/tests/end_to_end.rs

A committed record should never transition to cancelled.
This was caught by this flow test.

l1: add cancellation flow test + remove wrong state transition committed->cancelled

---

Cargo.lock
crates/apollo_mempool/Cargo.toml
crates/apollo_mempool/src/communication.rs
crates/apollo_mempool/src/mempool.rs
crates/apollo_mempool/src/mempool_flow_tests.rs
crates/apollo_mempool/src/mempool_test.rs
crates/apollo_mempool/src/test_utils.rs
crates/apollo_mempool/src/transaction_pool.rs
crates/apollo_mempool/src/transaction_pool_test.rs
crates/apollo_mempool/src/utils.rs

API is the same only using realclock instead of instant under the hood.
Realclock is sufficiently accurate (and monotone) for our usage, and
unlike `Instant` can be debugged in a human-readable way (Lior requested
we migrate to this type).
All changes are just changing the types to apollo_time.

apollo_mempool: migrate to apollo_time

---

crates/apollo_l1_gas_price/src/eth_to_strk_oracle.rs
crates/apollo_node/resources/config_schema.json

The config parameters `lag_interval_seconds`, `max_cache_size` and `query_timeout_sec` of the eth to strk rate oracle were private, but should be public.

apollo_l1_gas_price: make some config items public

---

crates/apollo_p2p_sync/src/client/block_data_stream_builder.rs
crates/apollo_p2p_sync/src/client/class.rs
crates/apollo_p2p_sync/src/client/header.rs
crates/apollo_p2p_sync/src/client/mod.rs
crates/apollo_p2p_sync/src/client/state_diff.rs
crates/apollo_p2p_sync/src/client/transaction.rs

This commit was added as a temporary fix to the bug found in the restart integration test.
During header sync at 50% hit-rate the restarted node would await endlessly for the peer to sync it up.
The problem probably originates from long session timeouts;
TODO: fix the network configs and make sure restart test passes consistently
after removing the changes introduced in this commit.

apollo_p2p_sync: add timeout when awaiting sync response

---

crates/apollo_network/src/mixed_behaviour.rs

- **apollo_deployments: fix l1 handler cooldown to be bigger than scraping interval (#7870)**
- **apollo_dashboard: fix consensus_round_above_zero_ratio alert (#7827) (#7865)**
- **apollo_dashboard: remove duplicate alert http_server idle (#7871)**
- **apollo_dashboard: fix alerts having no data (#7849)**
- **apollo_dashboard: fixed cende_latency alert and make block_number alert trigger (#7859) (#7867)**
- **apollo_consensus_orchestrator: move cende latency metric to correct function (#7854) (#7868)**
- **apollo_network: increase gossipsub max message size to 100mb**

apollo_network: increase gossipsub max message size to 100mb

---

crates/apollo_network/src/mixed_behaviour.rs

- **apollo_deployments: fix l1 handler cooldown to be bigger than scraping interval (#7870)**
- **apollo_dashboard: fix consensus_round_above_zero_ratio alert (#7827) (#7865)**
- **apollo_dashboard: remove duplicate alert http_server idle (#7871)**
- **apollo_dashboard: fix alerts having no data (#7849)**
- **apollo_dashboard: fixed cende_latency alert and make block_number alert trigger (#7859) (#7867)**
- **apollo_consensus_orchestrator: move cende latency metric to correct function (#7854) (#7868)**
- **apollo_network: increase gossipsub max message size to 100mb (#7900)**
- **apollo_deployments: increase gas price lag margin to 300 (#7901)**
- **apollo_network: increase gossipsub max message size to 10gb**

apollo_network: increase gossipsub max message size to 10gb

---

Cargo.lock
crates/apollo_signature_manager/Cargo.toml
crates/apollo_signature_manager/src/signature_manager.rs
crates/apollo_signature_manager/src/signature_manager_test.rs
crates/apollo_signature_manager_types/src/lib.rs

Verification is not part of the signature manager, it is provided as
library functions (will probably be wrapped by a verifier trait later);
those two flows are separate, hence their error enums ought to be too.

signature: add sig. verification error enum

---

crates/apollo_l1_provider/src/l1_provider.rs
crates/apollo_l1_provider/src/l1_provider_tests.rs
crates/apollo_l1_provider/src/test_utils.rs
crates/apollo_l1_provider/tests/reexecution_flow.rs

To accommodate state sync flow from genesis in the batcher, which will
send a bunch of historical blocks to the provider (but no
validate/get/start_block).

l1: return OK on commit-block for height < start_height

---

Cargo.lock
crates/apollo_l1_provider/src/l1_scraper.rs
crates/starknet_api/Cargo.toml
crates/starknet_api/src/block.rs
crates/starknet_api/src/block_test.rs

During the manual test for the `new_l1_handler_cooldown_seconds` feature, we found a gap in the information provided by the L1 provider's logs.

apollo_l1_provider: add timestamp to the got messages to l2 log

---

crates/apollo_consensus_orchestrator/src/validate_proposal.rs

Failures here can simply result in the proposal being treated as invalid.

apollo_consensus_orchestrator: remove some panics from the validate proposal flow

---

crates/apollo_integration_tests/src/integration_test_manager.rs

apollo_integration_tests: fix create simulator to always choose node 0

apollo_integration_tests: fix create simulator to always choose node 0

---

crates/blockifier/src/blockifier/concurrent_transaction_executor_test.rs
crates/blockifier/src/transaction/test_utils.rs

Encountered this test that had an issue with entering a busy loop, and had a few issues with readability.

blockifier: improve readability of test_concurrent_transaction_executor_stream_txs

---

Cargo.lock
Cargo.toml
crates/sizeof/sizeof_internal/Cargo.toml
crates/sizeof/sizeof_internal/src/lib.rs

Added a new `sizeof_internal` crate to compute the size of types in memory.
- Created a new crate `sizeof_internal` with a `SizeOf` trait that provides two methods:
- `dynamic_size()`: returns the heap size of a type in bytes
- `size_bytes()`: returns the total size (stack + heap) of a type in bytes
- Implemented the trait for primitive types, `String`, `Vec<T>`, and pointer types like `Box<T>`, `Rc<T>`, etc.
- Added macros `default_primitive_sizeof!` and `default_pointer_sizeof!` to simplify trait implementation
- Included tests to verify the functionality for basic types and `Felt`
Run the tests in the crate:
```bash
cargo test -p sizeof_internal
```
The tests verify size calculations for primitive types, strings, vectors, and Felt values.
This should replace the `size-of` crate …

starknet_api: using internal implementation of sizeof

---

crates/apollo_gateway/Cargo.toml
crates/apollo_gateway/src/stateful_transaction_validator.rs
crates/apollo_gateway/src/stateful_transaction_validator_test.rs
crates/blockifier/Cargo.toml
crates/blockifier/src/blockifier/stateful_validator.rs

Added a "mocks" feature to allow generating `MockStatefulValidatorTrait` for use in other crates during testing.

blockifier: move stateful validator trait to blockifier crate

---

crates/apollo_central_sync/src/sources/central.rs
crates/apollo_central_sync/src/sources/central_test.rs

- **apollo_starknet_client: add methods based on onlyHeader=true**
- **apollo_central_sync: use faster feeder method for getting latest block**

apollo_central_sync: use faster feeder method for getting latest block

---

crates/apollo_integration_tests/src/flow_test_setup.rs

Continue of: https://github.com/starkware-libs/sequencer/pull/8217
We stopped using TxCollector logic for flow tests, so now we are no longer listening to streamed txs.
But the code is still very efficient for debugging, so we will keep it until the tests are more stabilized.

apollo_integration_tests: Add todo to remove txs collector logic when flow tests are stable enough.

---

crates/apollo_integration_tests/src/flow_test_setup.rs

TODO: will soon make `send_message_to_l2` a method on `AnvilBaseLayer`,
as it interacts directly with L1, thus it will no longer be necessary to
interact with the internal starknet contract via
`anvil.ethereum_base_layer_contract.contract`.

apollo_integration_tests: use `AnvilBaseLayer`

---

Cargo.lock
crates/apollo_state_sync/src/lib.rs
crates/apollo_state_sync/src/test.rs
crates/apollo_state_sync_types/Cargo.toml
crates/apollo_state_sync_types/src/errors.rs

- **apollo_starknet_client: add methods based on onlyHeader=true**
- **apollo_state_sync: add starknet client to server**
- **apollo_state_sync: cherrypick #8089 from main (with conflicts)**
- **apollo_state_sync: cherrypick #8089 from main**
- **apollo_state_sync: if get_block_hash fails on block not found, try asking feeder directly**

apollo_state_sync: if get_block_hash fails on block not found, try asking feeder directly

---

crates/apollo_integration_tests/src/flow_test_setup.rs
crates/apollo_integration_tests/src/utils.rs
crates/apollo_integration_tests/tests/end_to_end_flow_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/papyrus_base_layer/src/base_layer_test.rs
crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs

Alloy can now auto-bump nonce automatically when using Anvil, via
`AnvilBaseLayer`.
Next commit will remove nonce tracking from starknet_api_test_utils.rs

l1: remove eth l1 nonce from `send_messages_to_l2`

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

Used to have l1 nonce tracking before we added nonce support to alloy
client. Now all that's needed is n_txs for assertions in the test.

l1: change nonce into n_txs in starknet_api_test_utils

---

crates/apollo_dashboard/resources/dev_grafana_alerts_mainnet.json
crates/apollo_dashboard/resources/dev_grafana_alerts_testnet.json
crates/apollo_dashboard/src/alert_scenarios/tps.rs

We do this since it can trigger by uneven loadbalancing which can trigger false alerts.

apollo_dashboard: Change idle threshold for http server to 30 minutes.

---

Cargo.lock
crates/apollo_l1_endpoint_monitor/Cargo.toml
crates/apollo_l1_endpoint_monitor/src/monitor.rs

I would have liked to have this log debugging an error with `monitored_base_layer`. This can help distinguish the cases when the L1 endpoint stopped working from those when it never started working.

apollo_l1_endpoint_monitor: log every n operational l1 endpoint

---

crates/apollo_integration_tests/src/utils.rs
crates/apollo_integration_tests/tests/end_to_end_flow_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

Simplify the creation of rpc invoke txs by creating generic rpc invoke txs function.
The functions which creates trivial invoke txs uses the generic one.

apollo_integration_tests: create genereic rpc invoke tx

---

crates/apollo_gateway/src/gateway.rs

Small refactor to fix a tiny bug in the gateway's metrics.

apollo_gateway: register blocked declares as transactions received

---

crates/apollo_batcher/src/block_builder.rs
crates/apollo_integration_tests/src/integration_test_manager.rs
crates/apollo_integration_tests/tests/end_to_end_flow_test.rs
crates/apollo_integration_tests/tests/test_many.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

Bug fix of invoke txs.
The invoke transactions were reverted due to wrong address of test_contract.

apollo_integration_tests: fix AccountTransactionGenerator invoke tx to call TestContract function

---

crates/apollo_infra_utils/src/test_utils.rs
crates/apollo_integration_tests/tests/common/mod.rs
crates/apollo_integration_tests/tests/test_custom_syscall_invoke_txs.rs

Create a new flow test - custom_invoke_tx.
The goal is to check many kinds of invoke transactions.
This PR build the structure of the test and create 3 basic invoke txs to test.

apollo_integration_tests: create custom invoke txs flow tests with direct test functions

---

crates/apollo_integration_tests/src/utils.rs
crates/apollo_integration_tests/tests/end_to_end_flow_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

Simplify the creation of rpc invoke txs by creating generic rpc invoke txs function.
The functions which creates trivial invoke txs uses the generic one.

apollo_integration_tests: create genereic rpc invoke tx (#8055)

---

crates/apollo_batcher/src/block_builder.rs
crates/apollo_integration_tests/src/integration_test_manager.rs
crates/apollo_integration_tests/tests/end_to_end_flow_test.rs
crates/apollo_integration_tests/tests/test_many.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

Bug fix of invoke txs.
The invoke transactions were reverted due to wrong address of test_contract.

apollo_integration_tests: fix AccountTxGenerator invoke_tx to call TestContract fn (#6838)

---

crates/apollo_infra_utils/src/test_utils.rs
crates/apollo_integration_tests/tests/common/mod.rs
crates/apollo_integration_tests/tests/test_custom_syscall_invoke_txs.rs

Create a new flow test - custom_invoke_tx.
The goal is to check many kinds of invoke transactions.
This PR builds the structure of the test and creates 3 basic invoke txs to test.

apollo_integration_tests: create custom invoke txs flow tests with direct test functions (#6939)

---

crates/apollo_dashboard/resources/dev_grafana.json
crates/apollo_dashboard/src/panels/state_sync.rs

- Add new header latency graph
- Add a new graph to show the diff from central block number
- Combine the marker graphs into one
- Rearrange the order of graphs, and change panel types when needed.

apollo_dashboard: state_sync dashboard improvements

---

crates/apollo_gateway/src/gateway.rs

Logging after add_tx is completed, to have a simple way to connect TX info with the add result.
(If split into 2 lines, it's almost impossible to do so)

apollo_gateway: log add_tx latency

---

crates/apollo_infra_utils/src/test_utils.rs
crates/apollo_integration_tests/tests/test_custom_cairo0_txs.rs

Create new flow test for cairo 0.
Account contract and test contract are both cairo 0.
Add three transactions direct call transaction to begin with.

apollo_integration_tests: add cairo 0 flow test

---

crates/apollo_integration_tests/tests/test_custom_cairo0_txs.rs
crates/apollo_integration_tests/tests/test_custom_cairo1_txs.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/test_utils/invoke.rs

Refactor in order to be able to generate invoke tx with more varied arguments.

apollo_integration_tests: add rpc invoke tx builder
