starkware-libs/sequencer

crates/blockifier/src/execution/contract_class.rs, crates/gateway/src/compilation.rs, crates/gateway/src/compilation_test.rs, crates/starknet_api/src/contract_class.rs, crates/starknet_api/src/deprecated_contract_class.rs, crates/starknet_api/src/executable_transaction.rs, crates/starknet_api/src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1117)
=> chore(execution): generalize contract class in executable txs

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/transaction_pool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1226)
=> feat(mempool): do not remove addresses from account nonces table - temporary

config/mempool/default_config.json, crates/batcher/src/batcher.rs, crates/batcher/src/communication.rs, crates/batcher/src/config.rs, crates/batcher/src/lib.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs, crates/batcher_types/src/batcher_types.rs, crates/batcher_types/src/errors.rs, crates/tests-integration/src/integration_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/565)
=> feat(batcher): generate proposal from a batcher server callback

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1229)
=> refactor(mempool): some cleanups and comments

crates/mempool/src/mempool_test.rs, crates/mempool/tests/flow_test.rs
Code move only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1230)
=> refactor(mempool): move a flow test to the appropriate file

crates/blockifier/src/execution/syscalls/hint_processor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1148)
=> chore(blockifier): remove cairo1 syscall_ptr security_check

crates/papyrus_network/src/network_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1236)
=> refactor(network): reorder broadcast structs for clarity

crates/mempool/src/mempool_test.rs, crates/mempool/tests/flow_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1232)
=> test(mempool): cleanup, move last existing flow test

commitlint.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1235)
=> feat(ci): add mempool p2p to commitlint

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1231)
=> fix(mempool): bug fix in mempool input validation

Cargo.lock, crates/mempool_p2p/Cargo.toml, crates/mempool_p2p/src/receiver/mod.rs, crates/mempool_p2p/src/sender/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1234)
=> feat(mempool_p2p): create init for receiver and sender

.github/workflows/committer_ci.yml, .github/workflows/committer_cli_push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1134)
=> feat(ci): no committer benchmarks in post-merge

crates/tests-integration/tests/gateway_mempool_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1251)
=> chore(tests-integration): gw-mp tests scaffolding

crates/committer_cli/src/block_hash.rs, crates/committer_cli/src/main.rs, crates/starknet_api/src/block_hash/block_hash_calculator.rs, crates/starknet_api/src/block_hash/block_hash_calculator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1201)
=> feat(starknet_api): backward compatibility for empty signatures

.github/workflows/committer_cli_push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1256)
=> fix(ci): committer CLI workflow concurrency error

crates/committer_cli/src/main.rs, crates/starknet_api/src/block_hash/block_hash_calculator.rs, crates/starknet_api/src/block_hash/block_hash_calculator_test.rs, crates/starknet_api/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1244)
=> feat(starknet_api): bump block hash constant prefix

crates/blockifier/src/context.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/resources.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/starknet_api/src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1114)
=> feat(blockifier): compute fee from new gas vector

Cargo.lock, crates/mempool_p2p/Cargo.toml, crates/mempool_p2p/src/receiver/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1258)
=> chore(mempool_p2p): add gateway client to receiver

crates/blockifier/Cargo.toml, crates/blockifier/src/execution/entry_point_execution.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1254)
=> feat(blockifier): fix testing feature passthrough to starknet_api

crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/transaction_execution.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1249)
=> feat(blockifier): more informative 'tx too large' error in the bouncer

.github/workflows/main.yml, .github/workflows/main_pr.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1260)
=> feat(ci): split some main CI jobs into PR-only workflow

crates/batcher/src/batcher.rs, crates/batcher/src/communication.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs, crates/batcher_types/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1041)
=> feat(batcher): start height

crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/batcher/src/lib.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1245)
=> feat(batcher): prepare proposal manager to be mocked in batcher tests

crates/blockifier/src/bouncer.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/fee/receipt_test.rs, crates/blockifier/src/fee/resources.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/utils.rs, crates/blockifier/src/versioned_constants.rs, crates/native_blockifier/src/py_block_executor.rs, crates/starknet_api/src/block.rs, crates/starknet_api/src/execution_resources.rs, crates/starknet_api/src/transaction.rs, crates/starknet_api/src/transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1175)
=> refactor(blockifier,starknet_api): gas amount is now a u64, not a u128

crates/blockifier/src/blockifier/block.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/transaction/account_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1177)
=> refactor(blockifier): indirection in GasPrices struct

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/test_utils.rs, crates/mempool/src/transaction_pool.rs, crates/mempool/tests/flow_test.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1238)
=> feat(mempool): move transaction deletions from get_txs to commit_block

crates/sequencing/papyrus_consensus/src/state_machine.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1204)
=> refactor(consensus): add past_round_upons as in the paper

crates/sequencing/papyrus_consensus/src/state_machine.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1205)
=> refactor(consensus): add future_round_upons as in the paper

crates/blockifier/src/context.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/fee/resources.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1178)
=> refactor(blockifier): refactor to_discounted_l1_gas

crates/mempool/src/mempool_test.rs
account_nonces testing will be covered in eviction flow tests when implemented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1267)
=> refactor(mempool): delete test support for account_nonces

crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs, crates/sequencing/papyrus_consensus/src/state_machine.rs, crates/sequencing/papyrus_consensus/src/state_machine_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1206)
=> refactor(consensus): add current_round_upons as in the paper

crates/blockifier/Cargo.toml, crates/blockifier/src/blockifier/config.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/blockifier/transfers_flow_test.rs, crates/blockifier/src/lib.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/test_utils/transfers_generator.rs, crates/native_blockifier/Cargo.toml, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1262)
=> chore(blockifier): remove concurrency feature

crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/fee/resources.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1250)
=> feat(blockifier): event fields converted from u128 to u64

crates/papyrus_network/src/network_manager/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1264)
=> chore(network): provide mock testing channels for prop and reporting

crates/blockifier/src/fee/fee_utils.rs, crates/starknet_api/src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1255)
=> feat(blockifier): safe addition of fee amounts in business logic

crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1272)
=> test(blockifier): track resources for old cairo1 contract

crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1284)
=> fix(blockifier): gas amounts / gas prices in error formatting

config/mempool/default_config.json, crates/mempool_infra/src/component_client/remote_component_client.rs, crates/mempool_infra/src/component_definitions.rs, crates/mempool_infra/src/component_server/remote_component_server.rs, crates/mempool_infra/src/tests/remote_component_client_server_test.rs, crates/mempool_node/src/config/config_test.rs, crates/mempool_node/src/config/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1207)
=> chore: extend remote communication config

crates/mempool_infra/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1287)
=> fix(mempool): move starknet-core-types to dev-dependencies

crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1196)
=> feat(consensus): add remaining API implementations to sequencer context

crates/gateway/src/stateless_transaction_validator_test.rs, crates/mempool_test_utils/src/starknet_api_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1299)
=> refactor(mempool_test_utils): remove create_resource_bounds_mapping

crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1293)
=> build(blockifier_reexecution): get all txs

.cargo/config.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1259)
=> fix(config): limit concurrency to prevent 'cargo test/build' crash due to excessive memory use

crates/mempool/Cargo.toml, crates/mempool/src/mempool_test.rs, crates/mempool/src/test_utils.rs, crates/mempool/tests/flow_test.rs
To be used in fee escalation tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1303)
=> test(mempool): add max_l2_gas_price to [add_]tx[_input] macros

crates/mempool/src/test_utils.rs, crates/mempool/tests/flow_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1316)
=> test(mempool): fix reource_bounds initalization in tx macro

crates/batcher/Cargo.toml, crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/batcher/src/block_builder.rs, crates/batcher/src/communication.rs, crates/batcher/src/lib.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs, crates/batcher/src/test_utils.rs, crates/batcher_types/src/batcher_types.rs, crates/batcher_types/src/errors.rs, crates/consensus_manager_types/src/consensus_manager_types.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1082)
=> feat(batcher): stream tx outside on build_proposal

crates/mempool/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1349)
=> chore: bug fix in tx macro in mempool test utils

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/test_utils.rs
Tests will be added next.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1304)
=> feat(mempool): implement fee escalation

crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1105)
=> refactor(batcher): error type per proposal manager function

Cargo.lock, config/mempool/default_config.json, crates/consensus_manager/Cargo.toml, crates/consensus_manager/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1197)
=> feat(consensus): add the actual consensus config to the consensus manager crate

Cargo.lock, crates/consensus_manager/Cargo.toml, crates/consensus_manager/src/consensus_manager.rs, crates/papyrus_protobuf/src/consensus.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1199)
=> feat(consensus): implement ComponentStarter for the consensus manager component

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1338)
=> test(mempool): add fee escalation unit test

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1271)
=> feat(consensus): call to the batcher when a decision is reached and to start the next height

crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1353)
=> test(blockifier): compute correct fee for regression tests

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1290)
=> feat(blockifier): implement and test max_steps computation for the L2 gas bound case

Cargo.lock, crates/mempool_p2p/Cargo.toml, crates/mempool_p2p/src/sender/mod.rs, crates/mempool_p2p/src/sender/test.rs, crates/mempool_p2p_types/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1237)
=> feat(mempool_p2p): impl handle request for sender

crates/mempool_node/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1320)
=> feat(mempool_node): add tracing for config loading and validation

crates/mempool_node/src/main.rs, crates/mempool_node/src/servers.rs, crates/tests-integration/src/integration_test_setup.rs
**Stack**:
- #1329
- #1328 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1328)
=> chore(mempool_node): remove config and name from get_server_future

crates/papyrus_storage/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1381)
=> chore: add test storage chain id subdir

crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/fee/resources.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/starknet_api/src/block.rs, crates/starknet_api/src/execution_resources.rs, crates/starknet_api/src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1281)
=> feat(blockifier): panic or saturate GasAmount arithmetic depending on 'natural' source of values

Cargo.lock, crates/tests-integration/Cargo.toml, crates/tests-integration/src/integration_test_setup.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1374)
=> chore(tests-integration): use node setup instead of manual server handles

crates/batcher/src/batcher.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1384)
=> feat: use a proper block builder factory in batcher creation

Cargo.lock, crates/blockifier_reexecution/Cargo.toml, crates/blockifier_reexecution/src/state_reader.rs, crates/blockifier_reexecution/src/state_reader/errors.rs, crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1302)
=> build(blockifier_reexecution): add reexecution errors

deployments/papyrus/helm/templates/grafana-alerts.yaml, deployments/papyrus/helm/templates/grafana-dashboard.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1347)
=> fix: papyrus grafana dashboard

crates/batcher/src/batcher.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1389)
=> chore: bug fix use empty bouncer config on create batcher

crates/mempool_node/src/config/node_config.rs
=> chore(mempool_node): rename cli command

crates/batcher/src/batcher.rs, crates/batcher/src/block_builder.rs, crates/batcher/src/block_builder_test.rs, crates/batcher/src/lib.rs, crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/fee/receipt.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/929)
=> feat(batcher): implement build_block() for block_builder

crates/batcher_types/src/communication.rs, crates/consensus_manager_types/src/communication.rs, crates/gateway_types/src/communication.rs, crates/mempool_infra/src/component_definitions.rs, crates/mempool_node/src/communication.rs, crates/mempool_p2p_types/src/communication.rs, crates/mempool_types/src/communication.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1286)
=> refactor: drop impl from component names

config/mempool/default_config.json, crates/mempool_infra/src/component_definitions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1343)
=> refactor: fix server socket description

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1390)
=> test(mempool): move fee escalation tests to EoF

crates/mempool/src/mempool_test.rs, crates/mempool/src/test_utils.rs
Irrelevant for the test flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1396)
=> test(mempool): remove nonce and address from positive fee escalation test

crates/blockifier_reexecution/src/state_reader/errors.rs, crates/blockifier_reexecution/src/state_reader/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1297)
=> build(blockifier_reexecution): convert starknet_api txs to blockifier txs

crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs, crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1344)
=> build(blockifier_reexecution): consecutive test state readers struct and fixtures

Cargo.lock, crates/blockifier_reexecution/Cargo.toml, crates/blockifier_reexecution/src/state_reader.rs, crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs, crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs, crates/blockifier_reexecution/src/state_reader/serde_utils.rs, crates/blockifier_reexecution/src/state_reader/test_state_reader.rs, crates/blockifier_reexecution/src/state_reader/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1266)
=> build(blockifier_reexecution): deserialize getstateupdate rpc request

crates/blockifier_reexecution/src/state_reader/serde_utils.rs, crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1398)
=> fix(blockifier_reexecution): remove double error redirect

crates/mempool/src/mempool_test.rs
This PR removes the test for updating the gas threshold, as it involved using two APIs in a single test.
New tests utilizing TransactionQueueContent have been added in [this](https://reviewable.io/reviews/starkware-libs/sequencer/1356) PR.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1403)
=> test(mempool): remove get txs while updating gas threshold tests

crates/papyrus_rpc/src/v0_8/api/api_impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1358)
=> feat: report error when a call is reverted

crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/batcher/src/communication.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs, crates/batcher_types/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1153)
=> feat(batcher): decision reached

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/context.rs, crates/blockifier/src/execution/contract_address_test.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/809)
=> feat(blockifier): set sierra gas limits based on resource bounds

crates/mempool/src/mempool.rs
Better describes the checks done inside, which are nonce-related only. Pass minimal necessary arguments, no need for whole transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1416)
=> refactor(mempool): rename and refactor Mempool::validate_input

crates/mempool_node/src/config/config_test.rs
=> refactor: clean config test

crates/mempool/src/mempool.rs
First, all data structure alignment is done, then committed transactions are deleted from pool.
Note deletion (and nonces alignement) loop is by definition mutually exclusive of the non-included addresses one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1420)
=> refactor(mempool): cluster alignment logic in commit_block

crates/sequencing/papyrus_consensus/src/stream_handler.rs, crates/sequencing/papyrus_consensus/src/stream_handler_test.rs
This includes changing of some names of fields in the StreamHandler struct, to reflect the fact that soon we'll be adding an outbound flow as well. 
The current fields are renamed: 
`sender` -> `inbound_channel_sender`
`receiver` -> `inbound_receiver`
`stream_data` -> `inbound_stream_data`
Also, I've changed the function `listen` -> `run` as it will soon be listening and broadcasting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1415)
=> feat: rename StreamHandler inbound fields

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/test_utils/contracts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1377)
=> chore(blockifier): share EntryPoint code between native and casm

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1426)
=> ci: fix typo and description

config/mempool/default_config.json, config/papyrus/default_config.json, crates/mempool_node/src/config/component_execution_config.rs, crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap, crates/sequencing/papyrus_consensus/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1373)
=> feat(consensus): consensus default config enables single node execution

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1194)
=> feat(consensus): add validate proposal flow to sequencer context

.github/workflows/main.yml, scripts/run_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1433)
=> feat(ci): run codecov only on modified packages, not dependencies

crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/batcher/src/proposal_manager.rs, crates/batcher/src/proposal_manager_test.rs, crates/batcher_types/src/batcher_types.rs, crates/batcher_types/src/errors.rs, crates/starknet_api/src/core.rs, crates/starknet_api/src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1359)
=> feat(batcher): send proposal commitment when proposal is done

crates/sequencing/papyrus_consensus/src/types.rs, crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1195)
=> feat(consensus): add re proposal flow to sequencer context

config/mempool/default_config.json, crates/batcher/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1419)
=> chore(batcher): add BlockBuilderConfig to BatcherConfig

crates/gateway/src/gateway.rs
commit-id:f7e33efa
---
**Stack**:
- #1429
- #1427 ⬅
=> chore(gateway): remove redundant todo

crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/batcher/src/proposal_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1370)
=> feat(batcher): notify mempool on committed block

crates/mempool/src/mempool_test.rs, crates/mempool/src/transaction_queue_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1432)
=> chore(mempool): add gas price threshold to transaction queue content

Cargo.lock, crates/tests-integration/Cargo.toml, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1386)
=> test: add build proposal step to end_to_end test

crates/mempool/src/mempool.rs, crates/mempool/src/transaction_queue.rs
This is the only resource bound mempool logic uses, no need to overload this struct.
=> refactor(mempool): simplify TransactionReference to contain only max L2 gas price

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs, crates/sequencing/papyrus_consensus/src/state_machine.rs, crates/sequencing/papyrus_consensus/src/state_machine_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1430)
=> refactor(consensus): switch BlockHash with ProposalContentId

crates/mempool/src/mempool_test.rs
Will be used in additional tests, in a subsequent PR.
=> refactor(mempool): add test utils for fee escalation tests

crates/batcher/src/block_builder.rs, crates/batcher/src/block_builder_test.rs, crates/batcher/src/lib.rs, crates/batcher/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1410)
=> chore(batcher): reorder block builder file

crates/sequencing/papyrus_consensus/src/manager_test.rs, crates/sequencing/papyrus_consensus/src/single_height_consensus.rs, crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs, crates/sequencing/papyrus_consensus/src/test_utils.rs, crates/sequencing/papyrus_consensus/src/types.rs, crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1431)
=> refactor(consensus): merge propose into build_proposal and remove propose fn from context trait

crates/mempool_test_utils/src/starknet_api_test_utils.rs
Remove duplicated invoke_tx_args macro from mepool.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1371)
=> refactor(mempool): call invoke_tx_args macro from StarknetAPI

.github/workflows/trigger _workflow.yml, .github/workflows/upload_artifacts_workflow.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1409)
=> feat: add trigger workflow to run upload artifacts on post merge

crates/tests-integration/src/bin/run_test_tx_generator.rs, crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/src/integration_test_utils.rs, crates/tests-integration/tests/end_to_end_test.rs
commit-id:346ca5a3
---
**Stack**:
- #1487 ⬅
- #1486
- #1485
=> chore(tests-integration): rename rpc tx arg

Cargo.lock, crates/gateway/Cargo.toml, crates/gateway/src/errors.rs, crates/http_server/Cargo.toml, crates/http_server/src/errors.rs, crates/http_server/src/http_server.rs, crates/mempool_infra/src/component_server/definitions.rs, crates/mempool_infra/src/component_server/empty_component_server.rs, crates/mempool_infra/src/component_server/local_component_server.rs, crates/mempool_infra/src/errors.rs, crates/mempool_node/src/servers.rs
commit-id:805a40ee
---
**Stack**:
- #1513
- #1512
- #1502 ⬅
- #1501
- #1499
=> chore(mempool_node): improve server module visibilty constraints

crates/tests-integration/src/integration_test_config_utils.rs
=> chore(tests-integration): change dump macro to require trailing comma

Cargo.lock, crates/tests-integration/Cargo.toml, crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/src/integration_test_utils.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1407)
=> test: add get proposal content loop to end to end test

crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1408)
=> test: add decision reached step to end to end test

crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs, crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1346)
=> chore(blockifier_reexecution): full blockifier reexecution poc

crates/papyrus_config/src/config_test.rs, crates/papyrus_config/src/dumping.rs
**Stack**:
- #1553
- #1536
- #1535 ⬅
=> chore(config): add required pointers

crates/papyrus_config/src/dumping.rs
=> chore(config): add empty line in config dump

config/mempool/default_config.json, config/papyrus/default_config.json, crates/papyrus_network/src/discovery/flow_test.rs, crates/papyrus_network/src/discovery/mod.rs, crates/papyrus_network/src/e2e_broadcast_test.rs, crates/papyrus_network/src/lib.rs, crates/papyrus_network/src/mixed_behaviour.rs, crates/papyrus_network/src/network_manager/mod.rs, crates/papyrus_network/src/peer_manager/mod.rs, crates/papyrus_network/src/utils.rs, crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1397)
=> feat(network): add peer manager and discovery config to network config

crates/mempool_node/src/communication.rs
- feat(mempool): create mempool p2p channels
- feat(mempool): create mempool p2p propagator client
=> feat(mempool): create mempool p2p propagator client

config/mempool/default_config.json, crates/mempool_node/src/components.rs, crates/mempool_node/src/config/component_config.rs, crates/mempool_node/src/config/component_execution_config.rs, crates/mempool_node/src/servers.rs, crates/mempool_p2p/src/propagator/mod.rs, crates/mempool_p2p/src/runner/mod.rs
- feat(mempool_p2p): create mempool p2p components - test failures because of channels being dropped
- feat(mempool_p2p): create mempool p2p servers and start them
=> feat(mempool_p2p): create mempool p2p servers and start them

crates/mempool_test_utils/src/starknet_api_test_utils.rs
Similar PR to [this one](https://github.com/starkware-libs/sequencer/pull/1371), dealing with the `deploy_account_tx_args` macro.
=> refactor(mempool): call deploy_account_tx_args from StarknetAPI

config/mempool/default_config.json, crates/mempool_node/src/config/component_config.rs, crates/mempool_node/src/config/node_config.rs
commit-id:cce1bea9
---
**Stack**:
- #1598
- #1553
- #1536 ⬅
=> chore(sequencer_node): set chain_id as required pointer param

Cargo.lock, crates/monitoring_endpoint/Cargo.toml, crates/monitoring_endpoint/src/monitoring_endpoint.rs, crates/monitoring_endpoint/src/monitoring_endpoit_test.rs
=> feat: adding tests to monitoring endpoint

crates/mempool_node/Cargo.toml, crates/mempool_node/src/config/node_config.rs, crates/mempool_node/src/utils.rs
commit-id:b3fba545
---
**Stack**:
- #1692
- #1691
- #1690 ⬅
- #1689
=> chore(sequencer_node): add testing feature with arg generating fn

config/mempool/default_config.json, crates/mempool_node/src/config/component_config.rs, crates/mempool_node/src/config/config_test.rs, crates/mempool_node/src/config/node_config.rs, crates/tests-integration/src/integration_test_config_utils.rs
commit-id:a52a7e16
---
**Stack**:
- #1692
- #1691 ⬅
=> chore(sequencer_node): set chain_id as required param

crates/blockifier_reexecution/src/main.rs, crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs, crates/blockifier_reexecution/src/state_reader/test_state_reader.rs
=> chore(blockifier_reexecution): add contract class dumper to test_state_reader

Cargo.lock, crates/mempool_node/Cargo.toml, crates/mempool_node/src/config/config_test.rs, crates/mempool_node/src/config/mod.rs, crates/mempool_node/src/config/node_config.rs, crates/mempool_node/src/config/test_utils.rs
commit-id:b608a7d6
---
**Stack**:
- #1725
- #1710
- #1709 ⬅
- #1708
- #1707
=> chore(sequencer_node): add cli_args to test util + general cleanup

config/mempool/default_config.json, crates/mempool_node/src/config/node_config.rs, crates/mempool_node/src/config/test_utils.rs, crates/tests-integration/Cargo.toml, crates/tests-integration/src/bin/run_test_rpc_state_reader.rs, crates/tests-integration/src/integration_test_config_utils.rs, crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/src/integration_test_utils.rs
commit-id:4bb4e626
---
**Stack**:
- #1725 ⬅
- #1710
=> chore(sequencer_node): add fee token addresses as required target params

crates/mempool_node/src/test_utils/compilation.rs
=> chore(sequencer_node): quiet compilation

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1337)
=> test(blockifier): parametrize more tests in transactions_test by resource bounds types

crates/batcher/src/batcher.rs, crates/batcher/src/batcher_test.rs, crates/mempool/src/mempool.rs, crates/mempool/src/test_utils.rs, crates/mempool_types/src/mempool_types.rs
RENAME ONLY, no logic changes.
=> chore: rename commit args nonces

config/mempool/default_config.json, config/papyrus/default_config.json, crates/papyrus_network/src/discovery/discovery_test.rs, crates/papyrus_network/src/discovery/mod.rs, crates/papyrus_network/src/peer_manager/mod.rs, crates/papyrus_network/src/peer_manager/test.rs, crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- Revert "fix: fix dump to config (#1637)"
- fix: flatten duration serialization to seconds
=> fix: flatten duration serialization

crates/tests-integration/src/bin/run_test_rpc_state_reader.rs, crates/tests-integration/src/integration_test_config_utils.rs
commit-id:fb18a3b8
---
**Stack**:
- #1826
- #1825
- #1824 ⬅
- #1803
=> chore(tests-integration): return temp dir config paths

crates/blockifier/resources/versioned_constants_0_13_4.json, crates/blockifier/src/versioned_constants.rs, crates/papyrus_storage/src/serialization/serializers.rs, crates/papyrus_test_utils/src/lib.rs, crates/starknet_api/src/block.rs, crates/starknet_api/src/block_hash/block_hash_calculator.rs, crates/starknet_api/src/block_hash/block_hash_calculator_test.rs
=> chore(starknet_api, blockifier): make 0.13.3 an intermediate version equivalent to 0.13.2.1

crates/sequencer_node/src/clients.rs, crates/sequencer_node/src/communication.rs, crates/sequencer_node/src/components.rs, crates/sequencer_node/src/lib.rs, crates/sequencer_node/src/utils.rs
commit-id:7ca0f454
---
**Stack**:
- #1878
- #1877
- #1876
- #1874
- #1873 ⬅
=> chore: move client functions to dedicated module

crates/monitoring_endpoint/Cargo.toml, crates/monitoring_endpoint/src/config.rs, crates/monitoring_endpoint/src/lib.rs, crates/monitoring_endpoint/src/monitoring_endpoint.rs, crates/monitoring_endpoint/src/monitoring_endpoint_test.rs, crates/monitoring_endpoint/src/test_utils.rs
commit-id:873e4d65
---
**Stack**:
- #1864 ⬅
- #1863
- #1862
- #1861
- #1860
=> chore(monitoring): use constants

crates/monitoring_endpoint/Cargo.toml, crates/monitoring_endpoint/src/monitoring_endpoint_test.rs, crates/monitoring_endpoint/src/test_utils.rs
=> chore(monitoring): clean dependencies, add todos

crates/sequencer_node/src/test_utils/compilation.rs
=> test(sequencer_node): change to debug compilation for speedup

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/test_utils/declare.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier_reexecution/src/state_reader/errors.rs, crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs, crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_transaction.rs, crates/papyrus_execution/src/lib.rs
=> refactor(blockifier): switch use of blockifier classinfo by starknet_api classinfo

crates/gateway_types/src/communication.rs, crates/sequencer_node/src/clients.rs, crates/sequencer_node/src/components.rs, crates/sequencer_node/src/config/component_execution_config.rs, crates/sequencer_node/src/config/config_test.rs, crates/sequencer_node/src/servers.rs
commit-id:18e9836c
---
**Stack**:
- #1961
- #1960
- #1959
- #1958
- #1957
- #1956 ⬅
- #1933
- #1924
=> chore: derive clone for GatewayRequest and GatewayResponse

Cargo.lock, crates/gateway_types/Cargo.toml, crates/gateway_types/src/communication.rs, crates/mempool_p2p_types/src/communication.rs, crates/sequencer_node/src/clients.rs
commit-id:5e8aae1c
---
**Stack**:
- #1961 ⬅
- #1960
- #1959
- #1958
- #1957
=> feat: add support for remote client

crates/starknet_integration_tests/src/config_utils.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_sequencer_node/src/bin/sequencer_dump_config.rs, crates/starknet_sequencer_node/src/clients.rs, crates/starknet_sequencer_node/src/components.rs, crates/starknet_sequencer_node/src/config/component_config.rs, crates/starknet_sequencer_node/src/config/config_test.rs, crates/starknet_sequencer_node/src/config/mod.rs, crates/starknet_sequencer_node/src/config/node_config.rs, crates/starknet_sequencer_node/src/config/test_utils.rs, crates/starknet_sequencer_node/src/main.rs, crates/starknet_sequencer_node/src/servers.rs, crates/starknet_sequencer_node/src/utils.rs
commit-id:6d9caf9a
---
**Stack**:
- #2010 ⬅
- #2009
- #2008
=> chore(config): remove indirection p3

crates/starknet_mempool_p2p/src/runner/mod.rs
=> chore: remove unused create_mempool_p2p_runner_server function

crates/starknet_sequencer_node/src/communication.rs
=> refactor: organize members in sequencer_node/commincation

crates/starknet_mempool/src/mempool.rs
This is a prep. refactor for small diffs. in nonce abstraction feature.
Only code move.
=> chore(mempool): move a check in `commit_block` into a util

crates/starknet_mempool/src/mempool.rs
There is only one use left, no need for a method anymore. Only code move.
=> refactor(mempool): remove `align_to_account_state` method

Cargo.lock, crates/papyrus_protobuf/src/converters/mod.rs, crates/starknet_integration_tests/Cargo.toml, crates/starknet_integration_tests/src/utils.rs, crates/starknet_integration_tests/tests/end_to_end_integration_test.rs, crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs, crates/starknet_mempool_p2p/src/lib.rs
- chore: changing closure Fn requirements on integration test utils
- test(mempool_p2p): test received rpc transactions are being broadcasted
=> test(mempool_p2p): test received rpc transactions are being broadcasted

commitlint.config.js, crates/papyrus_state_reader/Cargo.toml
=> fix(papyrus_state_reader): fix dev dependencies

crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs, crates/blockifier/src/execution/syscalls/syscall_tests/send_message_to_l1.rs, crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs
=> fix(blockifier): fix gas amounts for native

crates/starknet_mempool_p2p/Cargo.toml, crates/starknet_mempool_p2p_types/Cargo.toml, workspace_tests/main.rs, workspace_tests/package_integrity_test.rs, workspace_tests/toml_utils.rs, workspace_tests/version_integrity_test.rs
=> chore(ci): enforce crate directory name match + version from workspace

crates/starknet_batcher/src/communication.rs, crates/starknet_gateway/src/communication.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_mempool/src/communication.rs, crates/starknet_mempool_p2p/src/propagator/mod.rs, crates/starknet_sequencer_infra/src/component_client/definitions.rs, crates/starknet_sequencer_node/src/clients.rs, crates/starknet_sequencer_node/src/components.rs, crates/starknet_sequencer_node/src/servers.rs
commit-id:45cc731f
---
**Stack**:
- #2047
- #2041 ⬅
- #2040
- #2035
- #2034
- #2033
- #2032
- #2030
=> chore: add create remote servers function

crates/starknet_integration_tests/src/integration_test_setup.rs
commit-id:e71902fe
---
**Stack**:
- #2071
- #2070
- #2056
- #2055 ⬅
=> chore(tests_integration): maintain batcher storage reader

config/sequencer/default_config.json, crates/starknet_batcher/src/config.rs
refactor(batcher): add batcher creation func to test
feat(batcher): add input channel size config for validate flow
=> refactor(batcher): add input channel size config

Cargo.lock, crates/starknet_batcher/Cargo.toml, crates/starknet_batcher_types/Cargo.toml, crates/starknet_batcher_types/src/communication.rs, crates/starknet_gateway/Cargo.toml, crates/starknet_mempool_types/Cargo.toml, crates/starknet_mempool_types/src/communication.rs
commit-id:d05770a1
---
**Stack**:
- #2159
- #2158 ⬅
- #2157
=> chore(batcher): add testing feature, use automock only as test

crates/starknet_state_sync/Cargo.toml, crates/starknet_state_sync/src/runner/mod.rs, crates/starknet_state_sync/src/runner/test.rs
- **feat(sync): state sync runner runs central sync in background**
- **test(sync): add test that checks StateSyncRunner runs sync future**
=> test(sync): add test that checks StateSyncRunner runs sync future

crates/papyrus_network/src/network_manager/test_utils.rs
- **feat(network): add create_two_connected_network_configs test utility function**
- **feat(network): rename variables**
=> feat(network): add create_two_connected_network_configs test utility function

crates/starknet_integration_tests/Cargo.toml, crates/starknet_integration_tests/src/state_reader.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_sequencer_infra/Cargo.toml, crates/starknet_sequencer_infra/src/lib.rs, crates/starknet_sequencer_infra/src/test_utils.rs
commit-id:011da994
---
**Stack**:
- #2248
- #2235 ⬅
- #2233
=> chore(infra): remove duplication of get_available_socket

Cargo.lock, crates/papyrus_base_layer/Cargo.toml, crates/papyrus_base_layer/src/base_layer_test.rs, crates/papyrus_base_layer/src/lib.rs, crates/papyrus_base_layer/src/test_utils.rs
This will be used in the L1 provider.
MOVE only, no logic changes.
=> chore(base_layer): add test-utils + move ganache

crates/papyrus_config/Cargo.toml, crates/papyrus_node/Cargo.toml, crates/starknet_monitoring_endpoint/Cargo.toml, docs/papyrus/CONTRIBUTING.md
commit-id:8659371e
---
**Stack**:
- #2318 ⬅
- #2316
=> chore: update papyrus doc

crates/starknet_integration_tests/tests/end_to_end_integration_test.rs
commit-id:4d0abfb5
---
**Stack**:
- #2329
- #2332
- #2328
- #2322 ⬅
=> chore(tests_integration): read nonce of latest block

Cargo.lock, crates/infra_utils/Cargo.toml, crates/infra_utils/src/lib.rs, crates/infra_utils/src/run_until.rs, crates/infra_utils/src/run_until_test.rs, crates/infra_utils/src/tracing.rs, crates/infra_utils/src/tracing_test.rs, crates/starknet_integration_tests/tests/end_to_end_integration_test.rs
commit-id:6520ae54
---
**Stack**:
- #2424 ⬅
- #2385
- #2384
- #2329
- #2332
- #2328
=> chore(infra_utils): rename logger struct

crates/starknet_sierra_compile/build.rs, crates/starknet_sierra_compile/src/command_line_compiler.rs, crates/starknet_sierra_compile/src/constants.rs, crates/starknet_sierra_compile/src/lib.rs, crates/starknet_sierra_compile/src/paths.rs
commit-id:cd6fba29
---
**Stack**:
- #2481 ⬅
- #2475
- #2474
=> chore(starknet_sierra_compile): avoid using OUT_DIR in run time

crates/starknet_sequencer_infra/src/component_client/remote_component_client.rs, crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs, crates/starknet_sequencer_infra/src/serde_utils.rs, crates/starknet_sequencer_infra/src/serde_utils_test.rs, crates/starknet_sequencer_infra/src/tests/remote_component_client_server_test.rs
commit-id:6fdc6c31
---
**Stack**:
- #2506
- #2463
- #2462
- #2461
- #2460 ⬅
=> chore: rename BincodeSerdeWrapper to SerdeWrapper

.github/workflows/main.yml
commit-id:9ebcfa97
---
**Stack**:
- #2509
- #2508
- #2507 ⬅
=> chore(ci): remove redundant RUSTFLAGS setting

crates/infra_utils/src/path.rs
commit-id:68c898a6
---
**Stack**:
- #2520
- #2513 ⬅
=> chore(infra_utils): delete deprecated todos

crates/sequencing/papyrus_consensus/src/manager.rs
Handling cached messages is now out of the main select loop.
=> refactor(consensus): create start_height function in the manager

crates/starknet_integration_tests/tests/end_to_end_flow_test.rs
This makes the errors on one of the e2e flow test more comprehensible.
=> fix(sequencing): imporve e2e flow test assertion messages

crates/infra_utils/src/path.rs, crates/starknet_sierra_compile/build.rs, crates/starknet_sierra_compile/src/command_line_compiler.rs
commit-id:d3f4e29f
---
**Stack**:
- #2654 ⬅
- #2653
=> chore(starknet_sierra_compile): path cleanups

config/sequencer/default_config.json
this was merged into main without the `test_default_config_file_is_up_to_date` triggering on the CI.
=> fix: fix json config

crates/sequencing/papyrus_consensus/src/manager.rs
minimize the code inside of macros
=> refactor(consensus): move code from select to handle_proposal

crates/infra_utils/src/lib.rs, crates/infra_utils/src/type_name.rs, crates/infra_utils/src/type_name_test.rs
=> chore(infra_utils): add short_module_name util

crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
Reorganize file by importance.
No logic changes, just a MOVE.
=> refactor(starknet_l1_provider): reorganize eth base layer

crates/starknet_sequencer_infra/src/test_utils.rs
**Stack**:
- #2796
- #2795
- #2794
- #2789
- #2788
- #2787
- #2786
- #2781
- #2780
- #2778 ⬅
=> chore(starknet_sequencer_infra): add available ports test util

Cargo.lock, crates/papyrus_config/Cargo.toml, crates/papyrus_config/src/loading.rs
=> feat: log the loaded configuration when the node starts running

crates/sequencing/papyrus_consensus/src/stream_handler.rs, crates/sequencing/papyrus_consensus/src/stream_handler_test.rs
Make sure the StreamHandler doesn't send a receiver until it gets message number 0.
=> fix(consensus): make sure StreamHandler sends receiver on message zero

.github/workflows/main_nightly.yml, scripts/run_tests.py
- nightly isn't a pr, and doesn't need changes-only
- gen coverage of everything.
=> fix(ci): fix coverage

crates/starknet_sequencer_node/src/config/component_config.rs, crates/starknet_sequencer_node/src/config/component_execution_config.rs
=> chore: add conditional compilation for SocketAddr import

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
This results in less block code.
Also moved this code to another function since validate_current_round_proposal was both large and complex.
=> fix(consensus): initiate block validation in spawned task

scripts/rust_fmt.sh
Note: this doesn't necessarily have to be checked-in here, I think this kind of thing can be inside the dev-tools wiki
=> feat: reinstate rustfmt script, detach from CI

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
This results in less blocking code.
Also moved this code to another function since both large and complex.
=> fix(consensus): initiate block building in spawned task

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/utils.rs
**Stack**:
- #2959
- #2945
- #2943 ⬅
=> chore: pass components config as an arg

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_sequencer_infra/src/test_utils.rs
**Stack**:
- #2960
- #2959
- #2965 ⬅
=> feat: add remote connection test

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
also includes some minor changes to the code.
=> refactor(consensus): inline the function

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs, crates/sequencing/papyrus_consensus/src/types.rs
update handle_state_machine_vote
=> chore(consensus): add error for state machine and shc disagreeing

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_integration_tests/tests/end_to_end_flow_test.rs, crates/starknet_sequencer_infra/src/test_utils.rs
commit-id:9b08c150
---
**Stack**:
- #2960
- #2959 ⬅
=> chore: rename create_config function

crates/starknet_integration_tests/src/end_to_end_integration.rs
=> chore: increase max attempts for waiting for storage to include block

crates/starknet_http_server/src/test_utils.rs, crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_integration_tests/tests/end_to_end_flow_test.rs, crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs, crates/starknet_sequencer_infra/src/test_utils.rs
=> chore: remove unnecessary async from create_http_server_config

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_sequencer_infra/src/test_utils.rs
=> chore: update sequencer configuration for the remote connection test

crates/papyrus_network/src/network_manager/test_utils.rs, crates/starknet_integration_tests/src/utils.rs
**Stack**:
- #2968
- #2967
- #2966 ⬅
=> chore(starknet_integration_tests): pass relevant ports to config gen fn

Cargo.lock, crates/infra_utils/Cargo.toml, crates/infra_utils/src/lib.rs, crates/infra_utils/src/tasks.rs, crates/infra_utils/src/tasks_test.rs
=> chore(infra_utils): add spawn_monitored_task

crates/sequencing/papyrus_consensus/src/manager.rs
there are also upcoming tracing changes to the other modules which will complement these changes
=> chore(consensus): update tracing in manager

crates/starknet_integration_tests/src/end_to_end_integration.rs
=> chore: add an additional node configured for remote connection mode

crates/starknet_integration_tests/src/config_utils.rs, crates/starknet_sequencer_node/Cargo.toml, crates/starknet_sequencer_node/src/config/test_utils.rs
=> chore(starknet_integration_tests): cleaner required params handling in test

.github/workflows/merge_queue_ci.yml, .github/workflows/papyrus_ci.yml
=> feat(ci): define merge queue workflow, and remove papyrus CI from merge queue

crates/starknet_integration_tests/src/config_utils.rs, crates/starknet_sequencer_node/src/config/test_utils.rs
**Stack**:
- #3063
- #3062
- #3061
- #3060 ⬅
=> chore(starknet_sequencer_node): move config_to_preset util

Cargo.lock, crates/papyrus_base_layer/Cargo.toml, crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
**Stack**:
- #3063
- #3062
- #3061 ⬅
=> chore(papyrus_base_layer): add config validation

crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/starknet_api/src/execution_resources.rs
=> feat(blockifier): convert L2 gas to L1 gas units when computing fee with no L2 bounds

crates/starknet_http_server/src/http_server.rs, crates/starknet_http_server/src/http_server_test.rs, crates/starknet_http_server/src/metrics.rs, crates/starknet_http_server/src/metrics_test.rs
**Stack**:
- #3076
- #3075
- #3074
- #3073 ⬅
=> refactor(starknet_http_server): move metrics test to own module

Cargo.lock, crates/papyrus_base_layer/Cargo.toml, crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs, crates/starknet_sequencer_node/src/config/test_utils.rs
**Stack**:
- #3063
- #3062 ⬅
- #3061
=> chore(starknet_sequencer_node): required params impl serialize config

crates/starknet_http_server/src/http_server.rs, crates/starknet_http_server/src/http_server_test.rs, crates/starknet_http_server/src/metrics.rs, crates/starknet_http_server/src/metrics_test.rs, crates/starknet_integration_tests/src/utils.rs
**Stack**:
- #3076
- #3075
- #3074 ⬅
- #3073
=> chore(starknet_integration_tests): remove deprecated fn

crates/starknet_http_server/src/http_server.rs, crates/starknet_http_server/src/http_server_test.rs, crates/starknet_http_server/src/metrics.rs, crates/starknet_http_server/src/metrics_test.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_integration_tests/tests/end_to_end_flow_test.rs, crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs, crates/starknet_monitoring_endpoint/src/test_utils.rs
**Stack**:
- #3076
- #3075 ⬅
- #3074
- #3073
=> refactor(starknet_monitoring_endpoint): rename client

.github/workflows/papyrus_ci.yml, .github/workflows/papyrus_nightly-tests.yml
=> chore(ci): remove release mode from papyrus ci

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/lib.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
**Stack**:
- #3116
- #3109
- #3108
- #3107
- #3106
- #3104
- #3103 ⬅
=> refactor: rename IntegrationTestSetup

.github/workflows/upload_artifacts_workflow.yml
=> feat(ci): push new artifacts along with native blockifier artifacts

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
**Stack**:
- #3116
- #3109
- #3108 ⬅
=> chore: move the await for aliveness to the run function

crates/starknet_l1_provider/src/lib.rs
Not necessary now that scraper is added
=> refactor(starknet_l1_provider): remove unused method

config/sequencer/default_config.json, crates/starknet_sequencer_node/src/config/component_execution_config.rs
=> chore(starknet_sequencer_node): remove remote client config from active component

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/sequencer_manager.rs, crates/starknet_integration_tests/src/utils.rs
**Stack**:
- #3174
- #3172
- #3171
- #3164 ⬅
=> chore(starknet_integration_tests): zip vector iteration

crates/starknet_l1_provider/src/l1_provider.rs, crates/starknet_l1_provider/src/lib.rs, crates/starknet_l1_provider/src/test_utils.rs, crates/starknet_l1_provider/src/transaction_manager.rs
Only extract + visibility change
=> refactor(starknet_l1_provider): extract transaction_manager into file

config/sequencer/default_config.json, crates/starknet_sequencer_node/src/clients.rs, crates/starknet_sequencer_node/src/config/component_execution_config.rs, crates/starknet_sequencer_node/src/config/config_test.rs
=> chore(starknet_sequencer_node): remove option from local server config

scripts/sequencer_integration_test.sh
=> chore: pre-run clean up of sequencer processes

crates/papyrus_p2p_sync/src/client/class_test.rs
Currently calling SierraContractClass/DeprecatedContractClass::get_test_instance() is
broken. this function now returns an actual random and different instance every
time.
=> fix(papyrus_p2p_sync): fix create_random_state_diff_chunk_with_class

crates/papyrus_proc_macros/src/lib.rs
=> feat: add handle_all_response_variants macro

crates/papyrus_network/src/network_manager/mod.rs
=> chore(papyrus_network): move log of sending response to nw and removeextra wording

crates/starknet_integration_tests/src/flow_test_setup.rs
=> feat(starknet_integration_tests): enable state sync in the flow test

crates/starknet_l1_provider/src/l1_provider.rs, crates/starknet_l1_provider/src/l1_provider_tests.rs, crates/starknet_l1_provider/src/test_utils.rs, crates/starknet_l1_provider/src/transaction_manager.rs
=> refactor(starknet_l1_provider): rename tx_manager fields

crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
switch to error_span so this information always shows up
add the round to the information printed
=> chore(consensus): update span for the context handling proposals

Cargo.lock, crates/starknet_l1_provider/Cargo.toml, crates/starknet_l1_provider/src/l1_scraper_tests.rs
Fixture also needs to run only on CI, which makes it less useful, removing.
=> fix(ci): fix scraper test on local

crates/sequencing/papyrus_consensus_orchestrator/src/fee_market/mod.rs, crates/sequencing/papyrus_consensus_orchestrator/src/fee_market/test.rs, crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs
=> refactor(consensus): use versioned constants in fee market, consensus context

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
**Stack**:
- #3471
- #3470
- #3469
- #3467
- #3462 ⬅
=> refactor(starknet_integration_tests): rename SequencerSetupManager

crates/starknet_integration_tests/src/sequencer_manager.rs
**Stack**:
- #3492
- #3491
- #3490
- #3489
- #3488
- #3487
- #3471
- #3470
- #3469 ⬅
=> chore(starknet_integration_tests): add batcher and http_server to ComposedComponentConfigs

crates/blockifier/src/bouncer.rs, crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs, crates/blockifier/src/concurrency/versioned_storage.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs, crates/blockifier_reexecution/src/main.rs, crates/native_blockifier/src/py_declare.rs, crates/native_blockifier/src/py_deploy_account.rs, crates/native_blockifier/src/py_invoke_function.rs, crates/native_blockifier/src/py_state_diff.rs, crates/native_blockifier/src/py_utils.rs, crates/native_blockifier/src/storage.rs, crates/papyrus_p2p_sync/src/client/test_utils.rs, crates/papyrus_p2p_sync/src/server/mod.rs, crates/starknet_mempool_p2p/src/lib.rs, crates/starknet_mempool_p2p/src/runner/test.rs
**Stack**:
- #3485
- #3484
- #3483
- #3482
- #3481
- #3480
- #3479
- #3478
- #3477
- #3476
- #3475 ⬅
=> chore: p2p add todo names

crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/sequencer_manager.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_sequencer_node/src/test_utils/node_runner.rs
commit-id:9f29233f
---
**Stack**:
- #3492
- #3491
- #3490
- #3489
- #3488 ⬅
- #3487
- #3471
- #3470
=> refactor(starknet_integration_tests): rename SequencerExecutionId

crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/sequencer_manager.rs, crates/starknet_integration_tests/src/utils.rs
=> chore(starknet_integration_tests): add batcher_storage_reader to the NodeSetup

crates/papyrus_protobuf/build.rs, crates/papyrus_protobuf/src/converters/rpc_transaction.rs, crates/papyrus_protobuf/src/proto/p2p/proto/common.proto, crates/papyrus_protobuf/src/proto/p2p/proto/mempool/mempool.md, crates/papyrus_protobuf/src/proto/p2p/proto/mempool/transaction.proto
=> refactor(papyrus_protobuf): replace rpc_transaction with mempool_transaction

crates/papyrus_protobuf/build.rs, crates/papyrus_protobuf/src/converters/rpc_transaction.rs, crates/papyrus_protobuf/src/proto/p2p/proto/class.proto, crates/papyrus_protobuf/src/proto/p2p/proto/common.proto, crates/papyrus_protobuf/src/proto/p2p/proto/event.proto, crates/papyrus_protobuf/src/proto/p2p/proto/header.proto, crates/papyrus_protobuf/src/proto/p2p/proto/mempool/mempool.md, crates/papyrus_protobuf/src/proto/p2p/proto/mempool/transaction.proto, crates/papyrus_protobuf/src/proto/p2p/proto/state.proto, crates/papyrus_protobuf/src/proto/p2p/proto/sync/class.proto, crates/papyrus_protobuf/src/proto/p2p/proto/sync/common.proto, crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto
=> refactor(papyrus_protobuf): align class.proto

Cargo.lock, crates/starknet_sequencer_node/src/components.rs, crates/starknet_sierra_multicompile/Cargo.toml, crates/starknet_sierra_multicompile/src/lib.rs
**Stack**:
- #3534
- #3530
- #3504 ⬅
=> feat(starknet_sequencer_node): adding compilation unit to component initialization

crates/mempool_test_utils/src/starknet_api_test_utils.rs, crates/starknet_mempool/src/communication.rs, crates/starknet_mempool/src/mempool.rs, crates/starknet_mempool/src/mempool_test.rs, crates/starknet_mempool/tests/flow_test.rs, crates/starknet_mempool_types/src/communication.rs
**Stack**:
- #3485
- #3484
- #3483
- #3482
- #3481
- #3480
- #3479
- #3478
- #3477
- #3476 ⬅
=> chore: mempool add todo names

crates/mempool_test_utils/src/starknet_api_test_utils.rs, crates/papyrus_network/src/discovery/mod.rs, crates/papyrus_network/src/lib.rs, crates/papyrus_network/src/mixed_behaviour.rs, crates/papyrus_network/src/network_manager/mod.rs, crates/papyrus_network/src/network_manager/swarm_trait.rs, crates/papyrus_network/src/network_manager/test_utils.rs, crates/papyrus_network/src/peer_manager/behaviour_impl.rs, crates/papyrus_network/src/peer_manager/mod.rs, crates/papyrus_network_types/src/test_utils.rs, crates/papyrus_protobuf/src/converters/class.rs, crates/papyrus_protobuf/src/converters/class_test.rs, crates/papyrus_protobuf/src/converters/common.rs, crates/papyrus_protobuf/src/converters/receipt.rs, crates/starknet_mempool/src/communication.rs, crates/starknet_mempool/src/mempool.rs, crates/starknet_mempool/src/mempool_test.rs, crates/starknet_mempool/tests/flow_test.rs, crates/starknet_mempool_types/src/communication.rs
commit-id:8dee2222
---
**Stack**:
- #3485
- #3484
- #3483
- #3482
- #3481
- #3480
- #3479
- #3478
- #3477 ⬅
=> chore: papyrus add todo names

crates/papyrus_protobuf/build.rs, crates/papyrus_protobuf/src/converters/header.rs, crates/papyrus_protobuf/src/proto/p2p/proto/sync/header.proto
- **refactor(papyrus_protobuf): move state.proto to sync folder**
- **refactor(papryus_protobuf): move event,proto to the sync folder**
- **refactor(papyrus_protobuf): align header.proto**
=> refactor(papyrus_protobuf): align header.proto

crates/starknet_api/src/rpc_transaction.rs, crates/starknet_class_manager_types/src/transaction_converter.rs
- **feat(starknet_class_manager_types): implement rpc to and from internal rpc converter**
- **feat(starknet_class_manager_types): implement internal rpc to executable converter**
=> feat(starknet_class_manager_types): implement internal rpc to executable converter

crates/starknet_sequencer_node/src/servers.rs
=> feat(starknet_sequencer_node): add sierra compiler to servers

crates/papyrus_protobuf/build.rs, crates/papyrus_protobuf/src/proto/p2p/proto/sync/receipt.proto, crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto
- **refactor(papyrus_protobuf): move state.proto to sync folder**
- **refactor(papryus_protobuf): move event,proto to the sync folder**
- **refactor(papyrus_protobuf): align header.proto**
- **refactor(papyrus_protobuf): partial alignment of receipt.proto**
=> refactor(papyrus_protobuf): partial alignment of receipt.proto

crates/papyrus_protobuf/build.rs, crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto, crates/papyrus_protobuf/src/proto/p2p/proto/mempool/transaction.proto, crates/papyrus_protobuf/src/proto/p2p/proto/sync/transaction.proto, crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto
- **refactor(papyrus_protobuf): move state.proto to sync folder**
- **refactor(papryus_protobuf): move event,proto to the sync folder**
- **refactor(papyrus_protobuf): align header.proto**
- **refactor(papyrus_protobuf): partial alignment of receipt.proto**
- **refactor(papyrus_protobuf): align transaction.proto files**
=> refactor(papyrus_protobuf): align transaction.proto files

Cargo.lock, crates/starknet_class_manager/Cargo.toml, crates/starknet_class_manager/src/class_storage.rs
- Add associated error type to encapsulate impl. errors
- Add a method to query executable class hash: for classes that already appear in storage
=> refactor(starknet_class_manager): changes to storage trait

crates/starknet_class_manager_types/src/transaction_converter.rs
- **refactor(starknet_class_manager_types): make class hash output of `add_class`**
- **feat(starknet_class_manager_types): implement rpc declare tx to internal rpc**
=> feat(starknet_class_manager_types): implement rpc declare tx to internal rpc

crates/starknet_integration_tests/src/sequencer_manager.rs
commit-id:f6cc5f27
---
**Stack**:
- #3524
- #3523
- #3522 ⬅
=> chore(starknet_integration_tests): add RunningNode struct

crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
=> chore(starknet_integration_tests): add run function to NodeSetup

crates/starknet_integration_tests/src/sequencer_manager.rs
**Stack**:
- #3624
- #3621
- #3620 ⬅
=> chore(starknet_integration_tests): add await_alive fn to the RunningNode struct

crates/starknet_batcher/src/batcher.rs, crates/starknet_batcher/src/batcher_test.rs, crates/starknet_batcher/src/metrics.rs, crates/starknet_http_server/src/metrics.rs, crates/starknet_sequencer_metrics/src/lib.rs, crates/starknet_sequencer_metrics/src/metric_definitions.rs
commit-id:c8fd670d
---
**Stack**:
- #3602
- #3601
- #3600
- #3599 ⬅
=> chore(starknet_sequencer_metrics): consolidate metric definitions

crates/starknet_integration_tests/src/sequencer_manager.rs
commit-id:1d50f9e6
---
**Stack**:
- #3624
- #3621 ⬅
=> refactor(starknet_integration_tests): convert nodes to HashMap

crates/starknet_integration_tests/src/integration_test_setup.rs
=> chore(starknet_integration_tests): remove completed TODO

crates/blockifier/src/concurrency/fee_utils_test.rs, crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/test_utils/initial_test_state.rs
**Stack**:
- #3657
- #3647
- #3646
- #3644
- #3643
- #3642 ⬅
=> feat(blockifier): refactor test_state to only get the necessary data

crates/starknet_batcher/src/batcher_test.rs, crates/starknet_http_server/src/metrics_test.rs, crates/starknet_sequencer_metrics/src/metric_definitions.rs, crates/starknet_sequencer_metrics/src/metric_definitions_test.rs, crates/starknet_sequencer_metrics/src/metrics.rs
commit-id:d730f7f3
---
**Stack**:
- #3602 ⬅
- #3601
- #3600
=> chore(starknet_sequencer_metrics): enforce unique metrics

crates/blockifier/resources/versioned_constants_0_13_0.json, crates/blockifier/resources/versioned_constants_0_13_1.json, crates/blockifier/resources/versioned_constants_0_13_1_1.json, crates/blockifier/resources/versioned_constants_0_13_2.json, crates/blockifier/resources/versioned_constants_0_13_2_1.json, crates/blockifier/resources/versioned_constants_0_13_3.json, crates/blockifier/resources/versioned_constants_0_13_4.json, crates/blockifier/resources/versioned_constants_0_14_0.json, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
=> feat(blockifier): version bound accounts: rename v1_bound_accounts to v1_bound_accounts_cairo0

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
commit-id:08f6d70d
---
**Stack**:
- #3671
- #3669 ⬅
- #3662
=> chore(starknet_integration_tests): add test_and_verify function

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
commit-id:325f3d89
---
**Stack**:
- #3707
- #3671 ⬅
=> feat(starknet_integration_tests): add late node to the integration test

scripts/named_todos.py
=> fix(ci): check named todos in existing file

config/sequencer/default_config.json, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_l1_provider/src/communication.rs, crates/starknet_l1_provider/src/l1_provider.rs, crates/starknet_l1_provider/src/l1_scraper.rs, crates/starknet_l1_provider/src/l1_scraper_tests.rs, crates/starknet_l1_provider/src/lib.rs, crates/starknet_l1_provider/src/test_utils.rs, crates/starknet_l1_provider_types/src/lib.rs, crates/starknet_sequencer_node/src/components.rs, crates/starknet_sequencer_node/src/main.rs, crates/starknet_sequencer_node/src/utils.rs
L2 provider side will be added separately.
=> chore(starknet_l1_provider): finish l1-scraper startup flow

crates/papyrus_rpc/src/v0_8/execution_test.rs
=> refactor(papyrus_rpc): rename variable in func

Cargo.lock, crates/starknet_class_manager/Cargo.toml, crates/starknet_class_manager/src/class_manager.rs, crates/starknet_class_manager/src/class_manager_test.rs, crates/starknet_class_manager/src/lib.rs
In order to allow infra. integration into node.
Implementation is coming up.
=> feat(starknet_class_manager): add empty class manager

crates/starknet_integration_tests/src/end_to_end_integration.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
=> refactor(starknet_integration_tests): refactor run function

crates/starknet_integration_tests/src/end_to_end_integration.rs
=> chore(starknet_integration_tests): run the late node after 10 blocks

crates/starknet_l1_provider/src/l1_provider_tests.rs, crates/starknet_l1_provider/src/l1_scraper_tests.rs, crates/starknet_l1_provider/src/test_utils.rs
=> chore(starknet_l1_provider): extract to test_utils for upcoming flowtest

crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs, crates/papyrus_base_layer/src/lib.rs
Will be used soon in l1 scraper
=> feat(papyrus_base_layer): add `latest_l1_block`

crates/starknet_consensus/src/stream_handler_test.rs
This is used by a later PR to send different kinds of content.
=> chore(consensus): make stream handler setup_test generic

crates/starknet_batcher/src/batcher_test.rs, crates/starknet_http_server/src/metrics_test.rs, crates/starknet_sequencer_metrics/src/metric_definitions_test.rs, crates/starknet_sequencer_metrics/src/metrics.rs
=> chore(starknet_monitoring_endpoint): remove presenter trait

scripts/run_tests.py
This reverts commit 1d9ae96c7a2047d66b156dc170bb7c68a79f85d9.
=> Revert "fix(ci): add `testing` to clippy checks (#3779)"

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/execution/native/contract_class.rs, crates/blockifier/src/execution/native/entry_point_execution.rs, crates/blockifier/src/execution/native/syscall_handler.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/syscall_base.rs, crates/blockifier/src/test_utils/contracts.rs
**Stack**:
- #3837
- #3836
- #3835
- #3834 ⬅
=> feat(blockifier): version bound accounts: use ExecutableCallEntryPoint in more places

crates/papyrus_protobuf/src/converters/rpc_transaction.rs, crates/papyrus_protobuf/src/proto/p2p/proto/mempool/transaction.proto
- **chore(consensus, papyrus_node): delete papyrus context**
- **refactor(papyrus_protobuf): change TransactionBatch to use ConsensusTransaction**
- **refactor(starknet_batcher): use InternalConsensusTransaction**
- **feat(starknet_consensus_orchestrator): use InternalConsensusTransaction in consensus**
- **refactor(papyrus_protobuf): fix MempoolTransaction types**
=> refactor(papyrus_protobuf): fix MempoolTransaction types

crates/blockifier/Cargo.toml, crates/blockifier/src/blockifier/config.rs, crates/native_blockifier/src/py_objects.rs, crates/starknet_sequencer_node/Cargo.toml, crates/starknet_sequencer_node/src/config/config_test.rs
Reverts starkware-libs/sequencer#3775
=> chore(blockifier): revert- sierra_compilation_config compile only w feature cairo_native

Cargo.lock, crates/papyrus_state_reader/Cargo.toml, crates/papyrus_state_reader/src/papyrus_state.rs, crates/starknet_batcher/src/reader_with_class_manager.rs
=> feat(blockifier): add class manager client to Papyrus state

crates/blockifier_reexecution/src/state_reader/test_state_reader.rs, crates/starknet_gateway/src/rpc_objects.rs, crates/starknet_gateway/src/rpc_state_reader_test.rs
Use StarknetAPI's `GasPricePerToken`, delete Gateway's `ResourcePrice`
=> refactor(starknet_gateway): remove code duplication of GasPricePerToken

crates/papyrus_rpc/src/v0_8/api/api_impl.rs, crates/papyrus_rpc/src/v0_8/api/test.rs, crates/papyrus_rpc/src/v0_8/block.rs
Use StarknetAPI's GasPricePerToken, delete Papyrus RPC's ResourcePrice
=> refactor(papyrus_rpc): remove code duplication of GasPricePerToken

crates/starknet_class_manager/src/class_storage.rs
We will have one write at a time.
=> feat(starknet_class_manager): put Papyrus writer of `FsClassStorage` behind mutex

.github/workflows/committer_and_os_cli_push.yml
=> feat(starknet_committer_and_os_cli): build artifacts on every merge to release branches

crates/blockifier/resources/versioned_constants_0_13_0.json, crates/blockifier/resources/versioned_constants_0_13_1.json, crates/blockifier/resources/versioned_constants_0_13_1_1.json, crates/blockifier/resources/versioned_constants_0_13_2.json, crates/blockifier/resources/versioned_constants_0_13_2_1.json, crates/blockifier/resources/versioned_constants_0_13_3.json, crates/blockifier/resources/versioned_constants_0_13_4.json, crates/blockifier/resources/versioned_constants_0_14_0.json, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
**Stack**:
- #3837
- #3836
- #3835 ⬅
=> feat(blockifier): version bound accounts: add v1_bound_accounts_cairo1 to versioned constants

crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
=> feat(blockifier): version bound accounts: add a failure test

Cargo.lock, crates/papyrus_state_reader/Cargo.toml, crates/papyrus_state_reader/src/papyrus_state.rs
As prep. for class manager integration
Only code move, no changes.
=> refactor(blockifier): add `read_casm` methods to `PapyrusState`

config/sequencer/default_config.json, crates/starknet_class_manager/src/class_manager.rs, crates/starknet_class_manager/src/class_manager_test.rs, crates/starknet_class_manager/src/class_storage.rs, crates/starknet_class_manager/src/class_storage_test.rs, crates/starknet_class_manager/src/config.rs, crates/starknet_integration_tests/src/state_reader.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_sequencer_node/src/config/node_config.rs, crates/starknet_sierra_multicompile/src/lib.rs
Added `FsClassStorageConfig` for this.
Also deleted some done/irrelevant TODOs while at it.
=> feat(starknet_class_manager): implement proper class manager instantiation

crates/starknet_integration_tests/src/bin/sequencer_node_end_to_end_integration_test.rs
=> chore(starknet_integration_tests): resolve port conflicts

crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/fee_utils_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
=> chore(blockifier): update state_diff after commit - fee added (for the concurrent case)

Cargo.lock, crates/starknet_batcher/src/batcher.rs, crates/starknet_batcher/src/batcher_test.rs, crates/starknet_batcher_types/src/errors.rs, crates/starknet_consensus_orchestrator/Cargo.toml, crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/starknet_consensus_orchestrator/src/sequencer_consensus_context_test.rs
This will result in Consensus receiving a None value, implying an invalid proposal
=> chore(starknet_consensus_orchestrator): batcher can return an error from initiating a proposal

crates/starknet_integration_tests/src/sequencer_manager.rs
commit-id:daf3715e
---
**Stack**:
- #4140
- #4078
- #4064
- #4062
- #4060 ⬅
=> refactor(starknet_integration_tests): rename path to db arg

.gitignore, config/sequencer/default_config.json, crates/starknet_batcher/Cargo.toml, crates/starknet_batcher/src/config.rs, crates/starknet_class_manager/src/config.rs, crates/starknet_state_sync/src/config.rs
**Stack**:
- #4149
- #4144
- #4143 ⬅
=> chore(starknet_sequencer_node): format default storage paths

crates/papyrus_config/src/loading.rs, crates/papyrus_config/src/validators.rs, crates/papyrus_storage/src/lib.rs
=> chore(papyrus_config): add logs to config loading

crates/starknet_class_manager/src/class_storage.rs
This will help better handle non-deprcated<>deprecated cases. Will also allow to easily delete deprecated casms from storage once Cairo0 contracts are deprecated.
=> fix(starknet_class_manager): write deprecated casms to different filename

crates/starknet_integration_tests/src/bin/sequencer_node_setup.rs, crates/starknet_integration_tests/src/integration_test_utils.rs, crates/starknet_integration_tests/src/node_setup.rs
commit-id:33046524
---
**Stack**:
- #4156
- #4155 ⬅
=> refactor(starknet_integration_tests): use set_panic_hook function

crates/starknet_os/src/hints/hint_implementation/stateless_compression.rs, crates/starknet_os/src/hints/vars.rs
feat(starknet_os): copy dictionary_from_bucket
feat(starknet_os): implement dictionary_from_bucket
=> feat(starknet_os): copy dictionary_from_bucket

crates/starknet_os/src/hints/hint_implementation/stateless_compression.rs, crates/starknet_os/src/hints/vars.rs
feat(starknet_os): implement hint get_prev_offset
feat(starknet_os): implement hint get_prev_offset
=> feat(starknet_os): implement hint get_prev_offset

crates/starknet_sequencer_infra/src/metrics.rs
=> feat(starknet_sequencer_infra): add ability to read metrics values to LocalServerMetrics

Cargo.lock, Monitoring/sequencer/dev_grafana.json, crates/starknet_sequencer_metrics/Cargo.toml, crates/starknet_sequencer_metrics/src/dashboard.rs, crates/starknet_sequencer_metrics/src/dashboard_definitions.rs, crates/starknet_sequencer_metrics/src/dashboard_definitions_test.rs
**Stack**:
- chore(starknet_sequencer_metrics): add dashboard dump test #4285 ⬅
- chore(starknet_sequencer_metrics): update dashboard serde #4284
=> chore(starknet_sequencer_metrics): add dashboard dump test

Cargo.lock, crates/starknet_sequencer_infra/Cargo.toml, crates/starknet_sequencer_infra/src/tests/mod.rs, crates/starknet_sequencer_infra/src/tests/server_metrics_test.rs
=> chore(starknet_sequencer_infra): add test for a local server metrics

crates/starknet_integration_tests/src/monitoring_utils.rs, crates/starknet_integration_tests/src/sequencer_manager.rs, crates/starknet_integration_tests/src/sequencer_simulator_utils.rs
- **feat(starknet_integration_tests): add ability to send invoke txs without verifying anything**
- **feat(starknet_integration_tests): add ability to wait until all running nodes received enough txs**
=> feat(starknet_integration_tests): add ability to wait until all running nodes received enough txs

crates/starknet_os/src/hints/hint_implementation/output.rs, crates/starknet_os/src/hints/vars.rs
feat(starknet_os): copy set_compressed_start hint implementation from moonsong's repo
feat(starknet_os): implement set compressed start hint
=> feat(starknet_os): implement set compressed start hint

Cargo.lock, crates/starknet_class_manager/Cargo.toml, crates/starknet_class_manager/src/class_manager.rs, crates/starknet_class_manager/src/class_storage.rs, crates/starknet_sierra_multicompile/Cargo.toml, crates/starknet_sierra_multicompile/src/lib.rs
Class manager API is logged in info level; class storage in debug.
=> feat(starknet_class_manager): add logs to class manager

crates/starknet_sequencer_infra/src/component_client/remote_component_client.rs, crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs
=> chore(starknet_sequencer_infra): add logs to remote client and server

crates/starknet_integration_tests/src/bin/dump_test_preset_configs/system_test_dump_single_node_config.rs, crates/starknet_integration_tests/src/consts.rs, crates/starknet_integration_tests/src/lib.rs
=> refactor(starknet_integration_tests): move SINGLE_NODE_CONFIG_PATH to consts

Cargo.lock, crates/starknet_integration_tests/Cargo.toml, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/utils.rs
This reverts commit 0ba36cedfcf2ff13365846ab5e321e440144ec8a.
=> Revert "test(starknet_integration_tests): pass l1_endpoint_url as a param for setup (#4287)"

crates/starknet_sequencer_dashboard/src/metric_definitions_test.rs, crates/starknet_sequencer_metrics/src/metric_definitions.rs
**Stack**:
- #4505
- #4494
- #4478 ⬅
=> chore(starknet_sequencer_metrics): changing macro to create mix metrics in the same scope

Cargo.lock, crates/starknet_sequencer_dashboard/src/metric_definitions_test.rs, crates/starknet_sequencer_metrics/Cargo.toml, crates/starknet_sequencer_metrics/src/metric_definitions.rs
**Stack**:
- #4507
- #4505
- #4494 ⬅
=> chore(starknet_sequencer_metrics): extend the test to take multile arrays as input

crates/starknet_integration_tests/src/bin/sequencer_node_setup.rs
=> chore(starknet_integration_tests): use IntegrationTestManager in node setup

crates/starknet_integration_tests/src/bin/sequencer_node_setup.rs
commit-id:c9142fc1
---
**Stack**:
- #4526
- #4522
- #4520 ⬅
=> chore(starknet_integration_tests): pass only base_dir as param to setup

crates/native_blockifier/src/state_readers/py_state_reader.rs
=> fix(native_blockifier): switch the order of major and minor in sierra version

Cargo.lock, crates/starknet_api/Cargo.toml, crates/starknet_api/src/rpc_transaction.rs, crates/starknet_gateway/src/metrics.rs, crates/starknet_sequencer_metrics/src/label_utils.rs
chore(starknet_gateway): generate label permutations
=> chore(starknet_gateway): generate label permutations

crates/starknet_os/src/hints/error.rs, crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class.rs, crates/starknet_os/src/hints/vars.rs
feat(starknet_os): copy load_deprecated_class hint implementation from moonsong's repo
feat(starknet_os): implement load deprecated class hint
=> feat(starknet_os): implement load deprecated class hint

crates/starknet_batcher/src/batcher.rs, crates/starknet_batcher/src/batcher_test.rs, crates/starknet_batcher/src/block_builder.rs, crates/starknet_batcher/src/block_builder_test.rs, crates/starknet_batcher/src/test_utils.rs
Only RENAME, no logic changes.
=> refactor(starknet_batcher): rename Block{ExecutionMetadata, TransactionExecutionData}

crates/starknet_os/src/vm_utils.rs
feat(starknet_os): fetch nested fields from base address
feat(starknet_os): insert value to a nested field from base address
=> feat(starknet_os): fetch nested fields from base address

crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
Previously we would panic if the batcher fails in the middle of building
=> fix(starknet_consensus_orchestrator): allow proposal to fail if the batcher returns an error

Cargo.lock, crates/starknet_batcher/Cargo.toml, crates/starknet_batcher/src/block_builder_test.rs
=> refactor(starknet_batcher): add pretty assertions

crates/starknet_l1_provider/src/l1_scraper.rs
This fixes a scenario that will only happne in tests in practice, in which the given finality is higher than number of blocks on L1.
We return an error since this is assumed to be a configuration error by the user; test code will have to align with this behavior.
=> fix(starknet_l1_provider): fix initialize high finality flow

crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class.rs, crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class/utils.rs, crates/starknet_os/src/hints/vars.rs, crates/starknet_os/src/vm_utils.rs
feat(starknet_os): implement load_entry_points_to_contract_class_struct for load_inner_class hint
=> feat(starknet_os): implement load_entry_points_to_contract_class_struct for load_inner_class hint

config/sequencer/presets/config-batcher.json
commit-id:4fc7ae79
---
**Stack**:
- #4668
- #4667 ⬅
=> chore(starknet_sequencer_node): remove unused config-batcher.json

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs
=> chore(blockifier): fix comment, delete class_hash getter from syscall handler

crates/starknet_consensus/src/stream_handler.rs, crates/starknet_consensus_manager/src/consensus_manager.rs
I find this to be a clearer division of responsibility and in follow up PRs this helps resolve some
types issues
=> refactor(consensus): get_channels returns StreamHandler not a tokio task running it

Cargo.lock, crates/papyrus_network/src/network_manager/mod.rs, crates/starknet_consensus/src/stream_handler.rs, crates/starknet_consensus/src/stream_handler_test.rs, crates/starknet_consensus_manager/Cargo.toml, crates/starknet_consensus_manager/src/consensus_manager.rs
This will allow us to simplify the test setup.
=> refactor(consensus): make the inbound receiver fully generic

crates/starknet_integration_tests/src/bin/sequencer_node_end_to_end_integration_tests/integration_test_revert_flow.rs, crates/starknet_integration_tests/src/integration_test_setup.rs, crates/starknet_integration_tests/src/sequencer_manager.rs
refactor(starknet_integration_tests): rename update_revert_config and fn input
refactor(starknet_integration_tests): extract modify_revert_config logic to functions
=> refactor(starknet_integration_tests): rename update_revert_config and fn input

crates/starknet_consensus_manager/src/consensus_manager.rs
Also change the observer height to also expect as this simplifies the code.
=> fix(consensus): disambiguate the errors when failing to get batcher height

Cargo.lock, crates/starknet_l1_gas_price/Cargo.toml, crates/starknet_l1_gas_price/src/l1_gas_price_provider.rs, crates/starknet_l1_gas_price/src/l1_gas_price_provider_test.rs, crates/starknet_l1_gas_price/src/l1_gas_price_scraper.rs, crates/starknet_l1_gas_price/src/l1_gas_price_scraper_test.rs, crates/starknet_l1_gas_price_types/Cargo.toml, crates/starknet_l1_gas_price_types/src/errors.rs, crates/starknet_l1_gas_price_types/src/lib.rs
Moves the L1GasPriceProviderClient trait to the new "types" crate.
=> chore(starknet_l1_gas_price_types): add provider trait to types

crates/starknet_l1_gas_price/src/price_oracle.rs
the impl Default is needed for the config system, thats right its required but still we need to put anything
=> chore(starknet_l1_gas_price): impl default for PriceOracleConfig

crates/starknet_l1_gas_price/src/l1_gas_price_provider.rs, crates/starknet_l1_gas_price/src/l1_gas_price_provider_test.rs, crates/starknet_l1_gas_price/src/l1_gas_price_scraper.rs
Allow the gas price provider and scraper's configs to be serialized.
=> feat(starknet_l1_gas_price): serialize the config for gas price scraper and provider

crates/starknet_class_manager/src/class_manager.rs, crates/starknet_class_manager_types/src/lib.rs
=> feat(starknet_class_manager): add class hash to compilation error

crates/papyrus_sync/src/lib.rs
- **fix(papyrus_sync): send casm to class manager before writing casm to storage**
- **fix(papyrus_sync): write all casms including backward compatible to storage**
=> fix(papyrus_sync): write all casms including backward compatible to storage

crates/starknet_class_manager/src/class_storage.rs
=> fix(starknet_class_manager): add another directory hierarchy in class storage

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/fee/fee_checks.rs
=> fix(blockifier): replace incorrect use of enforce_fee() with use of flag charge_fee

crates/starknet_consensus_orchestrator/src/sequencer_consensus_context_test.rs
* `returning` doesn't enforce the function call, so even though expect_validate_block wasn't called in case of proposer , the test still passed.
* for the validator case, the test passed but not as expected—batcher.validate_block was never called; the receiver passed to context.validate had no sender, causing a timeout.
* in the proposer case, two functions were expected to be called: eth_to_fri_rate and propose_block.
Let me know if you’d prefer to split this into 2 separate tests!
=> test(starknet_consensus_orchestrator): fix batcher_not_ready test

crates/starknet_l1_provider/src/test_utils.rs
The tests pass because they were correct :) (tried to fail them on
purpose and it worked)
=> fix(starknet_l1_provider): add missing assert to test-util

crates/starknet_batcher/src/batcher.rs, crates/starknet_batcher/src/batcher_test.rs, crates/starknet_mempool_types/src/communication.rs, crates/starknet_mempool_types/src/mempool_types.rs
=> fix(starknet_batcher): cleanup mempool staging at the beginning of propose

Cargo.lock, config/sequencer/default_config.json, config/sequencer/presets/consolidated_node/application_configs/node.json, config/sequencer/presets/system_test_presets/single_node/node_0/executable_0/node_config.json, crates/starknet_l1_gas_price/src/l1_gas_price_scraper.rs, crates/starknet_sequencer_infra/src/metrics.rs, crates/starknet_sequencer_node/Cargo.toml, crates/starknet_sequencer_node/src/clients.rs, crates/starknet_sequencer_node/src/communication.rs, crates/starknet_sequencer_node/src/components.rs, crates/starknet_sequencer_node/src/servers.rs, deployments/monitoring/local/docker-compose.yml
Adds L1 gas price provider/scraper into the node setup. 
Essentially I've added the gas price components in all the places where the L1 (message) provider/scraper existed.
=> feat(starknet_l1_provider): integrate gas price components in the node

.github/workflows/sequencer_docker-test.yml, Cargo.lock, config/sequencer/presets/consolidated_node/application_configs/node.json, config/sequencer/presets/system_test_presets/single_node/node_0/executable_0/node_config.json, crates/starknet_consensus_manager/src/consensus_manager.rs, crates/starknet_integration_tests/Cargo.toml, crates/starknet_integration_tests/src/bin/dummy_eth_to_strk_oracle.rs, crates/starknet_integration_tests/src/flow_test_setup.rs, crates/starknet_integration_tests/src/integration_test_manager.rs, crates/starknet_integration_tests/src/utils.rs, crates/starknet_integration_tests/tests/end_to_end_flow_test.rs, crates/starknet_l1_gas_price/src/eth_to_strk_oracle.rs, deployments/images/sequencer/dummy_eth_to_strk_oracle.Dockerfile, deployments/monitoring/deploy_local_stack.sh, deployments/monitoring/local/docker-compose.yml
I added implementation to fake HTTP eth_to_fri_oracle server, it's used in integration and flow tests
=> feat(starknet_integration_tests): impl fake eth->fri oracle server

crates/starknet_os/src/hints/hint_implementation/compiled_class/implementation.rs
=> feat(starknet_os): implement validate_compiled_class_facts_post_execution

crates/starknet_l1_provider/src/l1_scraper_tests.rs
Bugs fixed:
1. Catch up height change: there was an off-by-one bugfix that was never
applied here cause the test didn't run.
2. The sync_response error is just an odd regression, the lock-unwrap
was initially inside the `returning`, as it is now in the fix, but at
some point i moved it into the _clone var definition and thought it
was OK because the test didn't really run in the CI or locally.
=> fix(starknet_l1_provider): fix bootstrapper e2e

crates/apollo_protobuf/src/converters/header.rs, crates/apollo_storage/src/header.rs, crates/apollo_storage/src/serialization/serializers.rs, crates/apollo_storage/src/test_instances.rs, crates/apollo_test_utils/src/lib.rs, crates/starknet_api/src/block.rs, crates/starknet_api/src/block_hash/block_hash_calculator_test.rs, crates/starknet_client/src/reader/objects/block.rs, crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
This reverts commit 6f7752235c1b867cb1f7a3c29f89101d09fa5b56.
=> Revert "refactor(starknet_client): l2_gas_consumed type from u64 to GasAmount (#5180)"

crates/apollo_protobuf/src/converters/header.rs, crates/apollo_protobuf/src/proto/p2p/proto/sync/header.proto, crates/apollo_protobuf/src/protobuf/protoc_output.rs, crates/apollo_storage/src/header.rs, crates/apollo_storage/src/serialization/serializers.rs, crates/apollo_storage/src/test_instances.rs, crates/apollo_test_utils/src/lib.rs, crates/starknet_api/src/block.rs, crates/starknet_api/src/block_hash/block_hash_calculator_test.rs, crates/starknet_client/resources/reader/block_post_0_14_0.json, crates/starknet_client/src/reader/objects/block.rs, crates/starknet_consensus_orchestrator/src/sequencer_consensus_context.rs
This reverts commit c54d407e4f1c9c188a9106d3e4487824b5845bf7.
=> Revert "refactor(starknet_client): next_l2_gas_price type from u64 to GasPrice (#5177)"

crates/apollo_integration_tests/src/bin/sequencer_node_end_to_end_integration_tests/integration_test_positive_flow.rs, crates/apollo_integration_tests/src/bin/sequencer_node_end_to_end_integration_tests/integration_test_restart_flow.rs, crates/apollo_integration_tests/src/bin/sequencer_node_end_to_end_integration_tests/integration_test_revert_flow.rs, crates/apollo_integration_tests/src/bin/sequencer_simulator.rs, crates/apollo_integration_tests/src/integration_test_manager.rs, crates/apollo_integration_tests/src/utils.rs
Before adding declare which is before deploying
=> refactor(apollo_integration_tests): rename bootstrap to deploy and invoke

config/sequencer/default_config.json, crates/blockifier/src/blockifier/config.rs, crates/blockifier/src/state/native_class_manager.rs, crates/blockifier/src/state/native_class_manager_test.rs, crates/native_blockifier/src/py_objects.rs, crates/starknet_sierra_multicompile/src/command_line_compiler.rs, crates/starknet_sierra_multicompile/src/compile_test.rs, crates/starknet_sierra_multicompile/src/config.rs, crates/starknet_sierra_multicompile/src/lib.rs
=> chore(blockifier): move flag panic_on_compilation_failure to cairo_native_run_config

Cargo.lock, crates/apollo_integration_tests/src/flow_test_setup.rs, crates/apollo_integration_tests/src/integration_test_manager.rs, crates/papyrus_base_layer/Cargo.toml, crates/papyrus_base_layer/src/test_utils.rs
This should allow the integration tests to work with the gas price scraper as well.
=> feat(apollo_integration_tests): add fake txs to anvil in integration tests

crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs
Note: this is not sufficient and done by request. There are missing
abstractions, the file needs a thorough refactor
=> refactor(consensus): extract function

config/sequencer/default_config.json, crates/native_blockifier/src/py_objects.rs, crates/starknet_compile_to_native/src/compile_test.rs, crates/starknet_compile_to_native/src/compiler.rs, crates/starknet_compile_to_native/src/config.rs
=> chore(starknet_compile_to_native): compilation max_memory_usage to optional

crates/apollo_infra/src/component_client/definitions.rs, crates/apollo_infra/src/component_definitions.rs
=> chore(apollo_infra): add Partial{,Eq} to clientError

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/context.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transactions.rs
=> feat(blockifier): gas capping in validate now part of ValidatableTransaction

crates/apollo_l1_provider/src/l1_scraper_tests.rs, crates/papyrus_base_layer/src/lib.rs
Also add fake base layer for testing. Refactor this struct as neccessary
=> chore(apollo_l1_provider): add test for provider crash -> scraper crash

Cargo.lock, crates/starknet_os/Cargo.toml, crates/starknet_os/src/hints/hint_implementation/patricia/error.rs, crates/starknet_os/src/hints/hint_implementation/patricia/utils.rs, crates/starknet_os/src/hints/hint_implementation/patricia/utils_test.rs, crates/starknet_patricia/src/patricia_merkle_tree/types.rs
feat(starknet_os): implement build_update_tree function
test(starknet_os): test build_update_tree for patricia hints
=> feat(starknet_os): implement build_update_tree function

crates/starknet_os/src/hints/hint_implementation/patricia/utils.rs, crates/starknet_os/src/hints/hint_implementation/patricia/utils_test.rs
feat(starknet_os): implement decode_node function
test(starknet_os): decode_node for patricia hints
=> feat(starknet_os): implement decode_node function

crates/blockifier/src/concurrency/versioned_state_test.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils/dict_state_reader.rs, crates/blockifier/src/test_utils/initial_test_state.rs, crates/native_blockifier/src/py_test_utils.rs
=> refactor(blockifier): change dict_state_reader.class_hash_to_class to class_hash_to_cached_class

crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/test_utils/initial_test_state.rs
This reverts commit b018b0f17364a1bae15f6f479a965f32bdf9be6f.
=> revert(blockifier): modify feature_contract_data to have cached_class

crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/apollo_l1_gas_price/src/l1_gas_price_provider.rs, crates/apollo_l1_gas_price/src/l1_gas_price_scraper.rs
=> fix(consensus): switch to using the proposed eth_to_fri_rate when comparing l1 prices

Monitoring/sequencer/sequencer_node_dashboard.json, deployments/sequencer/deployment_config_schema.json, deployments/sequencer/main.py, deployments/sequencer/services/helpers.py
- **fix(deployment): fix schema validation**
- **chore(deployment): update grafana dashboard**
- **chore(deployment): generate grafana dasboard hash from cluster and namespace names**
=> feat(deployment): cdk8s less random hash for grafana dashboards

crates/blockifier/src/state/state_reader_and_contract_manager.rs
=> refactor(blockifier): state_reader_and_contract_manager impl get_cached_class

crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/test_utils/initial_test_state.rs
state_reader_and_contract_manager in transaction_executor_test
=> test(blockifier): replace dict_reader with state_reader_and_contract_manager in tx_executor_test

crates/starknet_committer_and_os_cli/src/os_cli/commands.rs, crates/starknet_committer_and_os_cli/src/os_cli/tests/python_tests.rs, crates/starknet_os/src/hint_processor/snos_hint_processor.rs, crates/starknet_os/src/io/os_input.rs, crates/starknet_os/src/runner.rs
=> refactor(starknet_os): split block inputs from state inputs

crates/starknet_os/src/hint_processor/execution_helper.rs, crates/starknet_os/src/hint_processor/snos_hint_processor.rs, crates/starknet_os/src/runner.rs, crates/starknet_os/src/test_utils/cairo_runner.rs
=> refactor(starknet_os): execution helper keeps a reference to block input

crates/apollo_state_reader/src/papyrus_state_test.rs, crates/blockifier/src/state/state_reader_and_contract_manager.rs, crates/blockifier/src/state/state_reader_and_contract_manager_test.rs, crates/blockifier/src/test_utils/initial_test_state.rs
=> chore(blockifier): move state reader's cairo native logic test to blockifier

crates/blockifier/src/blockifier_versioned_constants.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/versioned_constants_test.rs, crates/starknet_api/src/versioned_constants_logic.rs
chore(blockifier): remove dead serde code from VC area
fix(blockifier): fix serde error tests
=> chore(blockifier): remove dead serde code from VC area

crates/apollo_consensus/src/manager.rs
This is because if we receive a proposal, vote, or event (e.g. timeout), this resets the timer
and we could have been blocked from polling sync.
=> fix(apollo_consensus): switch from sleep to sleep_until for polling sync

crates/blockifier/src/concurrency/flow_test.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
**Stack**:
- #6490
- #6489
- #6487
- #6486 ⬅
=> feat(blockifier): refactor get_tx_status

crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/test_utils.rs
**Stack**:
- #6490
- #6489
- #6487 ⬅
=> feat(blockifier): remove default_scheduler macro

crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/secp.rs, crates/blockifier/src/execution/syscalls/vm_syscall_utils.rs
=> refactor(blockifier): read returns syscall base error

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/concurrency/flow_test.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
**Stack**:
- #6569
- #6564
- #6603
- #6563 ⬅
=> feat(blockifier): add OptionalVersionedState

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/worker_pool.rs
**Stack**:
- #6603 ⬅
- #6569
- #6564
=> feat(blockifier): add wait_for_completion and propagate panics properly

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/concurrency/worker_pool.rs
**Stack**:
- #6689
- #6569
- #6564 ⬅
=> feat(blockifier): allow passing external WorkerPool to TransactionExecutor

crates/apollo_batcher/src/batcher.rs, crates/apollo_batcher/src/block_builder.rs, crates/blockifier/src/blockifier/transaction_executor.rs
=> feat(blockifier): use a shared WorkerPool for all blocks

crates/blockifier/src/concurrency/flow_test.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
**Stack**:
- #6683
- #6682
- #6670
- #6654 ⬅
=> feat(blockifier): use AskForTask after failed validation

crates/blockifier/src/concurrency/flow_test.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
**Stack**:
- #6683
- #6682
- #6670 ⬅
=> feat(blockifier): move end-chunk logic from scheduler.rs to worker_logic.rs

crates/blockifier/src/concurrency/flow_test.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
**Stack**:
- #6720
- #6719
- #6718
- #6717
- #6683
- #6682 ⬅
=> feat(blockifier): don't re-execute inside the commit lock

.github/workflows/consolidated_system_test.yaml, deployments/dummy_recorder/main.py
=> feat(deployment): add dummy recorder deployment to the system test workflow

crates/apollo_l1_provider/src/test_utils.rs
Doesn't affect tests because this wasn't tested :(
Fixed here in order to make next commit compile.
=> fix(apollo_l1_provider): rejected wasn't added to test util builder

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/concurrency/utils.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
**Stack**:
- #6825
- #6824
- #6720
- #6719
- #6718
- #6717 ⬅
=> refactor(blockifier): use DashMap for execution_output

crates/blockifier/src/concurrency/worker_logic.rs
**Stack**:
- #6825
- #6824
- #6720
- #6719
- #6718 ⬅
=> refactor(blockifier): use DashMap for transactions and add n_transactions

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/concurrency/worker_pool.rs
**Stack**:
- #6825
- #6824
- #6720 ⬅
=> refactor(blockifier): stop wait_for_completion according to number of transactions

crates/apollo_batcher/src/batcher.rs, crates/blockifier/src/blockifier/concurrent_transaction_executor_test.rs, crates/blockifier/src/blockifier/config.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/concurrency/worker_pool.rs
**Stack**:
- #6916
- #6907
- #6906
- #6872
- #6871 ⬅
=> refactor(blockifier): add WorkerPoolConfig

crates/starknet_os/src/hint_processor/snos_syscall_executor.rs
[Python side](https://github.com/starkware-industries/starkware/blob/56b05931b9c7315493af12fc5114c6a317c44dd9/src/starkware/starknet/core/os/syscall_handler.py#L640)
=> feat(starknet_os): send_message_to_l1 'implementation'

crates/apollo_batcher/src/block_builder_test.rs
Preparation for changing the TransactionExecutorTrait API.
---
**Stack**:
- #6916
- #6907 ⬅
=> refactor(apollo_batcher): add ExpectationHelper to block_builder_test

crates/apollo_signature_manager_types/src/lib.rs
Only signing methods appear in trait, while verification ones will
appear as free functions -- to be called directly, not through a client.
=> refactor(apollo_signature_manager_types): align client trait to final design

crates/apollo_rpc/src/v0_8/api/test.rs, crates/native_blockifier/src/storage.rs, crates/starknet_api/src/block.rs
Change possible usages accordingly.
=> refactor(starknet_api): derive `Deref` for `BlockHash`

crates/apollo_batcher/src/block_builder_test.rs
**Stack**:
- #7032
- #7031
- #7030
- #7029 ⬅
=> test(apollo_batcher): refactor mock_tx_provider_limited_calls

crates/apollo_l1_provider/src/test_utils.rs, crates/apollo_l1_provider/src/transaction_manager.rs
Currently only migrating the committed buffer, since it's the easiest to migrate.
The idea is that the next steps will do the same for `rejected` and `uncommitted`,
which will add more metadata to the record, and finally add methods so
the `TransactionManager` can query the record based on behavior only, so
`is_validatable(), is_proposable(), etc.` and hide all the different
states from the manager.
Motivation: after this migration we'll add timelocks for new
transactions and cancellations, which will add even more different
states and state transitions per transaction. This new record type will
become the single source of truth for all information and decisions re
the current state.
=> refactor(apollo_l1_provider): start migration to `TransactionRecord`s

crates/apollo_l1_provider/src/transaction_manager.rs
Soon it will be impossible to edit record without using `with_record`
(in particular, you won't have `get_mut` on records).
Also fixed with_record to allow taking ownership of variables, otherwise
the `tx` passed into the closure would have had to be cloned.
=> fix(apollo_l1_provider): access record through `with_record` only

crates/apollo_l1_provider/src/l1_provider_tests.rs, crates/apollo_l1_provider/src/test_utils.rs, crates/apollo_l1_provider/src/transaction_manager.rs
The proposable txs (that can be returned from get_txs) will now be
lex-sorted by (created_at, tx_hash). Still unused, but will soon be used
for new transaction timelocks.
=> l1: add timestamp to the proposable txs index

crates/blockifier/src/execution/contract_class.rs
estimate_compiled_class_hash_migration_resources
=> feat(blockifier): add frame estimate_compiled_class_hash_migration_resources

Cargo.lock, crates/apollo_signature_manager/Cargo.toml, crates/apollo_signature_manager/src/lib.rs
`Deref` impl. is simple enough.
=> refactor(apollo_signature_manager): remove dep. of `derive_more`

crates/apollo_batcher/src/block_builder.rs, crates/apollo_batcher/src/block_builder_test.rs, crates/apollo_batcher/src/transaction_executor.rs, crates/blockifier/src/blockifier/concurrent_transaction_executor.rs, crates/blockifier/src/blockifier/concurrent_transaction_executor_test.rs
**Stack**:
- #7240
- #7215
- #7214
- #7213 ⬅
- #7209
=> blockifier: add n_txs_in_block parameter to close_block

crates/apollo_batcher/src/batcher.rs, crates/apollo_batcher/src/block_builder.rs, crates/apollo_batcher/src/block_builder_test.rs, crates/apollo_batcher/src/transaction_provider.rs, crates/apollo_batcher/src/transaction_provider_test.rs
**Stack**:
- #7266
- #7265
- #7252
- #7250
- #7240
- #7215 ⬅
- #7209
=> apollo_batcher: change validate-mode end block condition

crates/apollo_batcher/src/block_builder.rs
**Stack**:
- #7266
- #7265
- #7252
- #7250
- #7240 ⬅
- #7209
=> apollo_batcher: remove txs that were not included in the block from execution_data

crates/apollo_batcher/src/batcher.rs, crates/apollo_batcher/src/block_builder.rs, crates/apollo_batcher/src/block_builder_test.rs
The meaning of the flag is planned to change, and it will not simply mean "fail on error".
---
**Stack**:
- #7266
- #7265
- #7252 ⬅
- #7209
=> apollo_batcher: rename fail_on_err to is_validator

crates/apollo_batcher/src/block_builder.rs, crates/apollo_batcher/src/block_builder_test.rs
**Stack**:
- #7266
- #7265 ⬅
- #7209
=> apollo_batcher: support failed txs in validator

crates/apollo_batcher/src/block_builder.rs, crates/apollo_batcher/src/block_builder_test.rs, crates/apollo_batcher/src/test_utils.rs, crates/apollo_batcher/src/transaction_provider.rs, crates/apollo_batcher/src/transaction_provider_test.rs
**Stack**:
- #7325
- #7324
- #7266 ⬅
- #7209
=> apollo_batcher: remove NextTxs::End variant

Monitoring/sequencer/dev_grafana_alerts.json, crates/apollo_dashboard/src/alert_definitions.rs
- **apollo_dashboard: updates to alerts from meeting**
- **apollo_dashboard: use increase instead of rate**
- **apollo_dashboard: set pedning duration and evaluation interval for all alerts to 10s**
=> apollo_dashboard: set pedning duration and evaluation interval for all alerts to 10s

Monitoring/sequencer/dev_grafana_alerts.json, crates/apollo_dashboard/src/alert_definitions.rs
- **apollo_dashboard: set pedning duration and evaluation interval for all alerts to 10s**
- **apollo_dashboard: align once alerts to be 5 minutes**
=> apollo_dashboard: align once alerts to be 5 minutes

crates/apollo_batcher/src/batcher.rs, crates/apollo_batcher/src/batcher_test.rs, crates/apollo_batcher/src/transaction_provider.rs, crates/apollo_batcher/src/transaction_provider_test.rs, crates/apollo_batcher/src/utils.rs, crates/apollo_batcher_types/src/batcher_types.rs
=> apollo_batcher: pass final_n_executed_txs: consensus -> transaction provider

crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs, crates/papyrus_base_layer/src/lib.rs
Will be used to dynamically switch between infura/alchemy soon
=> papyrus_base_layer: add provider_url setter

crates/native_blockifier/src/py_objects.rs
bouncer config full_total_weights
=> chore(blockifier): add assert for unexpected keys received from py bouncer config full_total_weights

crates/apollo_l1_provider/src/l1_scraper_tests.rs
Will soon convert this test into an integration test, which has no
access to test_utils, and to `FakeL1ProviderClient` in particular, so
next we'll replace it with the mockall one, which requires asserting
before initializing the scraper.
Note: The reason why we'll convert the test to an integration test is
to prevent multiple Anvil instances running at once, which isn't
possible in unit tests which are parallelized.
=> l1: inline scraper test util

crates/blockifier/src/execution/entry_point_execution.rs
…ode so it can be reused in Starknet Foundry
=> blockifier: refactor some of the entry_point_execution.rs code for Starknet Foundry

crates/apollo_l1_provider/src/l1_scraper_tests.rs
Scraper initialization will soon be pushed down once we add
`mockall` l1 provider client.
Note that the chain_id is identical to the one used when initializing
the scraper.
=> l1: detach setup from scraper

crates/apollo_network/src/config_test.rs, crates/apollo_network/src/test_utils/mod.rs
1. Split each scenario to its own test
2. Simplify test set up by removing parts not tested
2. Add more test cases
=> apollo_network: Add tests for more validation cases.

Cargo.lock, crates/apollo_l1_provider/Cargo.toml, crates/apollo_l1_provider/src/l1_scraper_tests.rs
Using `Sequence` to enforce order between the expectations.
=> l1: switch from fake l1 provider client to mock

crates/apollo_l1_provider/src/l1_scraper.rs, crates/apollo_l1_provider/src/l1_scraper_tests.rs, crates/apollo_l1_provider/tests/scraper_end_to_end.rs
MOVE only, no logic changes except making `send_events_to_l1_provider`
pub.
=> l1: convert happy flow test into integration test

crates/starknet_os/src/hint_processor/snos_hint_processor.rs, crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class/implementation.rs, crates/starknet_os/src/hints/hint_implementation/deprecated_compiled_class/utils.rs, crates/starknet_os/src/io/os_input.rs
This reverts commit 6f632f76a1c4d5cc8150a14310ac88972623247d.
=> starknet_os: removed hinted class hash input (revert 6f632f7)

crates/apollo_batcher/src/batcher.rs, crates/apollo_batcher/src/block_builder.rs, crates/apollo_batcher/src/block_builder_test.rs, crates/apollo_batcher/src/test_utils.rs, crates/apollo_batcher_types/src/batcher_types.rs, crates/apollo_consensus_orchestrator/src/cende/central_objects.rs, crates/apollo_consensus_orchestrator/src/cende/central_objects_test.rs, crates/apollo_consensus_orchestrator/src/cende/mod.rs, crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/native_blockifier/src/py_block_executor.rs
=> blockifier: name change: to_migrate -> for_migration

crates/apollo_consensus_orchestrator/resources/central_blob.json, crates/apollo_consensus_orchestrator/src/cende/central_objects.rs, crates/apollo_consensus_orchestrator/src/cende/mod.rs
=> apollo_consensus_orchestrator: add migration class hashes to aerospike blob

crates/apollo_integration_tests/src/flow_test_setup.rs, crates/apollo_integration_tests/src/integration_test_manager.rs, crates/papyrus_base_layer/src/test_utils.rs
Easier to debug and to understand what these are, also explicit
dependency on `AnvilInstance`, which will soon be hidden.
=> l1: add consts to anvil pre-funded accounts

crates/papyrus_base_layer/src/anvil_base_layer.rs, crates/papyrus_base_layer/src/base_layer_test.rs, crates/papyrus_base_layer/tests/events_from_other_contracts.rs
It requires anvil, so should not be run as a unit test
=> l1: convert events_from_other_contracts test into integration test

crates/papyrus_base_layer/src/monitored_base_layer.rs
Because the current_node_url has infrequent writes, RwLock can improve performance
=> papyrus_base_layer: change current_node_url from Mutex to RwLock

crates/apollo_network/src/mixed_behaviour.rs
This reverts commit 42875b011172fc4ae05ea33e014d73d3bb63f6f7.
=> Revert "apollo_network: set gossipsub PeerScoreThresholds (#8405)"

Cargo.lock, crates/apollo_state_sync_metrics/Cargo.toml, crates/apollo_state_sync_metrics/src/metrics.rs
Optimize startup performance by replacing expensive get_block_transactions_count() calls with efficient get_block_transaction_hashes() cursor traversal. The optimization leverages LMDB's sequential read capabilities to improve metric reconstruction time while maintaining minimal memory overhead through temporary allocations.
=> apollo_state_sync_metrics: optimize processed transactions reconstruction

crates/apollo_gateway/src/stateful_transaction_validator.rs, crates/apollo_gateway/src/sync_state_reader.rs
=> apollo_gateway: Add a mechanism to measure how many times state reader methods are called and

crates/apollo_consensus_orchestrator/src/build_proposal.rs, crates/apollo_consensus_orchestrator/src/metrics.rs, crates/apollo_consensus_orchestrator/src/sequencer_consensus_context.rs, crates/apollo_consensus_orchestrator/src/validate_proposal.rs, crates/apollo_dashboard/resources/dev_grafana.json, crates/apollo_dashboard/src/panels/consensus.rs
=> apollo_dashboard: use strum discriminants for build/validate proposal failure metrics

crates/apollo_integration_tests/src/utils.rs, crates/apollo_integration_tests/tests/test_custom_cairo1_txs.rs
More invoke txs that added to the test_contract.cairo in previous PR.
=> apollo_integration_tests: add new compiled invoke txs tests (#7988)

crates/apollo_integration_tests/tests/test_custom_cairo0_txs.rs
=> apollo_integration_tests: add invoke_tx that use signature argument
