starkware-libs/sequencer

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/74)

test(mempool): open commit block tests

---

crates/mempool_infra/Cargo.toml

mempool_infra crate does not compile because it is missing dependencies features.
mempool_infra crate is now compiling successfully
-
-[x] No
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/71)

fix: add missing features to dependencies serde and hyper

---

.github/CODEOWNERS

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/66)

ci: remove code owner

---

.github/workflows/committer_ci.yml
crates/committer_cli/benches/bench_split_and_prepare_post.sh

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/51)

chore: fix committer_ci benchmarking phase

---

commitlint.config.js

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/86)

ci: add mempool_infra as an optional scope

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/72)

test(mempool): rename get_txs test to be more specific

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/80)

test(mempool): refactor MempoolState to have Partial and Full states

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/88)

feat(mempool): replenishing queue in get_txs

---

config/papyrus/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/run_consensus.py
crates/sequencing/papyrus_consensus/src/config.rs
crates/sequencing/papyrus_consensus/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/64)

chore(consensus): reuse db and prevent InsufficientPeers error

---

.github/workflows/blockifier_ci.yml
.github/workflows/merge_paths_ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/78)

chore: extract merge paths test to separate job

---

.github/workflows/committer_ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/73)

chore: fix committer CI triggers

---

scripts/run_tests.py

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/77)

fix: global file changes trigger specific package CIs

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/102)

test(mempool): implement default for MempoolState FullState

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/91)

feat(mempool): get txs return requested txs after replenishing queue

---

Cargo.lock
crates/mempool/src/communication.rs
crates/mempool_types/Cargo.toml
crates/mempool_types/src/communication.rs
crates/mempool_types/src/errors.rs
crates/mempool_types/src/mempool_types.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/115)

feat: add functionality to use remote mempool client/server

---

.github/workflows/papyrus_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/127)

chore(ci): allow warning during cargo doc

---

crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/starknet_api/src/crypto/patricia_hash.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/122)

chore: fix some clippy doc issues

---

.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_nightly-tests.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/123)

chore(ci): fix package selection

---

.github/workflows/papyrus_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/121)

chore(ci): fix papyrus ci triggers

---

.github/workflows/papyrus_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/135)

ci: add triggers for papyrus CI

---

.github/workflows/merge_paths_ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/116)

chore(ci): fix merge paths CI

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/125)

test(mempool): use mempool state default in tests

---

crates/gateway/src/stateful_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/131)

refactor(gateway): use mock to test skip_validate

---

.github/workflows/main.yml
.github/workflows/papyrus_ci.yml
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer_cli/src/parse_input/raw_input.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/106)

chore: move (workspace) doc test to main (workspace) CI

---

.github/workflows/committer_ci.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/107)

fix: restore ci

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/150)

chore(network): remove send query conversion fn

---

crates/papyrus_network/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/149)

fix(network): make streamhashmap not end

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/stream_builder.rs
crates/papyrus_p2p_sync/src/server/mod.rs
crates/papyrus_p2p_sync/src/server/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/142)

refactor(sync): combine server channels

---

crates/mempool_infra/src/component_client/definitions.rs
crates/mempool_infra/tests/component_server_client_http_test.rs
crates/mempool_infra/tests/component_server_client_test.rs
crates/mempool_types/src/communication.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/158)

chore: add a represantation of unxepected enum in client error

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/133)

refactor: committer create tree test

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/69)

refactor(consensus): make BlockHash optional

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/145)

feat(protobuf): add round to consensus messages

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/138)

chore(network): handle report receiver

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/55)

chore(network): fix confusing log of peer assignment

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_p2p_sync/src/server/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/56)

chore(sync): add p2p sync server logs

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/119)

fix: ascii art spacing

---

.github/workflows/blockifier_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/118)

chore(ci): remove duplicate Machete CI job

---

Cargo.lock
crates/papyrus_network/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/175)

fix: remove unused dependency in papyrus_network

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/94)

test(mempool): flow test with a happy flow scenario

---

crates/mempool_infra/src/component_server/definitions.rs
crates/mempool_infra/src/component_server/local_component_server.rs
crates/mempool_infra/tests/active_component_server_client_test.rs

feat: adding server for active components

---

commitlint.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/155)

chore(batcher): add batcher scope to commitlint config

---

crates/blockifier/src/state/cached_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/186)

fix(state): typo

---

commitlint.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/185)

chore(ci): add blockifier scope to commitlint

---

scripts/merge_branches.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/191)

chore(ci): add timestamp in forward-merge branch to prevent collisions

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/192)

chore(ci): fix commitlint PR title check for forward-merge

---

.github/workflows/papyrus_ci.yml
crates/papyrus_base_layer/src/base_layer_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/165)

chore(base_layer): relax ganache version requirement

---

Cargo.lock
crates/committer_cli/Cargo.toml
crates/committer_cli/src/tests/regression_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/144)

test: add threads to regression test

---

crates/mempool_infra/tests/common/mod.rs
crates/mempool_infra/tests/component_server_client_http_test.rs
crates/mempool_infra/tests/component_server_client_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/159)

chore(mempool_infra): move verify_test function to common

---

Cargo.lock
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_sync/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/163)

feat(sync): add metrics for p2p sync

---

crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/162)

chore(network): remove pub from network mods that dont need it

---

scripts/merge_status.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/211)

chore(ci): more informative merge_status.py output

---

crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/212)

fix: silence clippy

---

.github/workflows/blockifier_ci.yml
crates/native_blockifier/.cargo/config.toml
taplo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/193)

fix: add missing config.toml

---

config/mempool/default_config.json
crates/gateway/src/config.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs

There is code duplication in the struct Chain info.
- Use the blockifier chain info in the gateway's config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/99)

chore: use chain info in stateful validator config

---

crates/starknet_api/src/executable_transaction.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/111)

chore: rename sn-api internal tx struct

---

crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/146)

feat(consensus): use protobuf/SMEvent round

---

scripts/committer/generate_committer_flamegraph.sh

script for generating a flame-graph for the committer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/89)

chore: add flamegraph generation script for committer

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/147)

feat(consensus): send Proposal(None) to the SM instead of InvalidProposal error

---

crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/187)

test(consensus): handle repeated proposals and votes

---

commitlint.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/226)

chore: add starknet_api scope

---

crates/blockifier/src/transaction/account_transaction.rs

Code dedup.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/235)

chore: use version function for invoke account tx

---

.github/workflows/blockifier_ci.yml
build_native_blockifier_in_docker.sh
scripts/build_native_blockifier.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/215)

chore: fix native blockifier build

---

.github/workflows/papyrus_docker-publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/209)

chore: fix papyrus docker build

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/234)

chore: ignore pycache in gitignore

---

.github/workflows/blockifier_ci.yml
.github/workflows/papyrus_docker-publish.yml
.gitignore
build_native_blockifier_in_docker.sh
scripts/build_native_blockifier.sh
scripts/committer/generate_committer_flamegraph.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/241)

Merge main-v0.13.2 into main

---

Cargo.lock
crates/mempool_types/Cargo.toml
crates/mempool_types/src/communication.rs
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_proc_macros/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/206)

chore: add macro for communication request/response matching

---

crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/221)

refactor(consensus): add instrumentation when spawning tasks within consensus

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/225)

test(mempool): arrange mempool test file

---

crates/mempool_node/src/communication.rs
crates/mempool_types/src/communication.rs

refactor(mempool): rename local mempool client

---

crates/papyrus_network/src/discovery/kad_impl.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/57)

fix(network): kademlia removes blacklisted peers

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/172)

feat(mempool): reject tx of lower nonce in add_tx

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/253)

chore: add merge gate keeper

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/293)

chore(ci): add gatekeeper to main

---

crates/gateway/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/242)

refactor(mempool): remove unused sn-api utils

---

crates/mempool/src/lib.rs
crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/243)

refactor(mempool): use pub crate for transaction pool

---

crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/internal_test_utils.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer_cli/benches/committer_bench.rs
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/regression_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/140)

refactor: make external tests generic

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/87)

test(mempool): flow test a commit block closes a nonce gap

---

crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/249)

refactor(consensus): consensus takes a generic network receiver

---

crates/mempool_infra/tests/common/mod.rs
crates/mempool_infra/tests/component_server_client_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/292)

chore: remove deprecated TODO messages

---

crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/288)

refactor(consensus): fix linter warning from the simulation network receiver

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/228)

feat(consensus): handle invalid vote

---

Cargo.lock
crates/batcher_types/Cargo.toml
crates/batcher_types/src/batcher_types.rs
crates/batcher_types/src/communication.rs
crates/batcher_types/src/errors.rs
crates/batcher_types/src/lib.rs

commit-id:aa33dbd8
---
**Stack**:
- #204
- #201 ⬅

feat: add batcher_types communication

---

crates/batcher_types/Cargo.toml
crates/mempool_types/Cargo.toml

fix: rename incorrect features property

---

Cargo.lock
crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/gateway/src/utils.rs
crates/mempool_test_utils/Cargo.toml
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/rpc_transaction.rs
crates/tests-integration/src/state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/295)

chore: add calculate_sender_address to RPCTransaction

---

crates/papyrus_network/src/discovery/kad_impl.rs
crates/papyrus_test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/289)

fix(network): fix a couple minor lints in papyrus

---

Cargo.toml
crates/gateway/Cargo.toml
crates/mempool_node/Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/sequencing/papyrus_consensus/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/255)

chore(ci): move papyrus_config dep to root toml

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/310)

chore(ci): fix gatekeeper config

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/internal_test_utils.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/156)

refactor: tree hash function impl

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/block_committer/input.rs
crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/skeleton_forest.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/160)

refactor: committer node index

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/167)

refactor: remove async fun from create

---

crates/papyrus_protobuf/src/converters/consensus.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/282)

fix(consensus): handle nil quorum on different round and enable protobuf nil votes

---

crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/329)

refactor(consensus): additional lints found in the manager

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/101)

test(mempool): rename MempoolState to MempoolContent

---

crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_protobuf/src/converters/header_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/328)

fix(protobuf): fix conversion for header without commitments

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/stream_builder.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/244)

chore(network): implement logic for network channels

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/90)

test(mempool): flow test send tx twice

---

crates/mempool/src/mempool_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/108)

test(mempool): refactor add-tx util

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/338)

test(mempool): fix change mempool_state to mempool_content

---

.github/workflows/blockifier_ci.yml
build_native_blockifier_in_docker.sh
scripts/blockifier.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/214)

build: move build_native_blockifier.sh to build inside scripts

---

crates/papyrus_config/src/command.rs
crates/papyrus_config/src/config_test.rs
crates/papyrus_config/src/lib.rs
crates/papyrus_config/src/loading.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/301)

feat(config): handle positive, negative, and float in SerializationType

---

crates/mempool_infra/tests/component_server_client_http_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/346)

chore(mempool_infra): rename variable I forgot in previous commit

---

config/papyrus/default_config.json
crates/papyrus_config/src/command.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/README.md
crates/sequencing/papyrus_consensus/run_consensus.py
crates/sequencing/papyrus_consensus/src/config.rs
crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/285)

test(consensus): add the ability to run simulations with test receiver

---

.github/workflows/committer_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/352)

fix: revert specific ci change

---

Cargo.lock
Cargo.toml
crates/committer/Cargo.toml
crates/committer/src/block_committer/commit.rs
crates/committer/src/block_committer/input.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer_cli/Cargo.toml
crates/committer_cli/benches/committer_bench.rs
crates/committer_cli/src/commands.rs
crates/committer_cli/src/lib.rs
crates/committer_cli/src/main.rs
crates/committer_cli/src/parse_input/raw_input.rs
crates/committer_cli/src/parse_input/read_test.rs
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tracing_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/291)

chore: switch to tracing crate

---

crates/committer/src/block_committer/commit.rs
crates/committer_cli/src/commands.rs
crates/committer_cli/src/filled_tree_output/filled_forest.rs
crates/committer_cli/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/342)

chore: add logs

---

config/papyrus/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/papyrus_p2p_sync/src/client/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/298)

feat(sync): create transaction protocol

---

crates/papyrus_p2p_sync/src/server/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/358)

fix(sync): flush the channel in the p2p server before dropping it

---

Cargo.toml
crates/committer/Cargo.toml
crates/committer_cli/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/311)

refactor: use serde workspace

---

Cargo.toml
crates/committer_cli/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/315)

refactor: use clap workspace in committer cli

---

Cargo.lock
config/mempool/default_config.json
crates/mempool_infra/Cargo.toml
crates/mempool_infra/src/component_definitions.rs
crates/mempool_node/Cargo.toml
crates/mempool_node/src/config/config_test.rs
crates/mempool_node/src/config/mod.rs

feat: adding new parameters to the component execution config

---

Cargo.lock
Cargo.toml
crates/committer_cli/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/317)

refactor: use criterion workspace in committer

---

.github/workflows/blockifier_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/375)

chore(ci): post-merge native blockifier push debugging commit

---

.github/workflows/blockifier_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/376)

chore(ci): revert debugging commit and fix post-merge native push

---

Cargo.lock
config/papyrus/default_config.json
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/discovery/flow_test.rs
crates/papyrus_network/src/e2e_broadcast_test.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/mixed_behaviour.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_node/src/config/pointers.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/171)

fix(network): add chain id to Kademlia discovery protocol

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/359)

docs(network): explain the meaning of none in responses_receiver

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_p2p_sync/src/server/mod.rs
crates/papyrus_p2p_sync/src/server/test.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/388)

feat(network): impl network server channel struct

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/mod.rs

- revert(network): discovery cant be paused
- fix(network): change discovery config structure
- fix(network): discovery sleeps between queries
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/308)

fix(network): discovery sleeps between queries

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/mixed_behaviour.rs

- revert(network): discovery cant be paused
- fix(network): change discovery config structure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/307)

fix(network): change discovery config structure

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/mixed_behaviour.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/300)

revert(network): discovery runs indefinitely with a heartbeat

---

crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/309)

refactor(starknet_api): remove transaction version from hash calculation

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/400)

chore(ci): fix merge gatekeeper config

---

crates/mempool_infra/Cargo.toml

chore: fixing mempool_infra Cargo.toml

---

crates/mempool_node/src/lib.rs
crates/mempool_node/src/main.rs
crates/mempool_node/src/utils.rs
crates/tests-integration/src/integration_test_setup.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/382)

refactor: move node's main functionality into a public function

---

crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/395)

test(sync): in p2p sync client tests, simulate time has passed

---

Cargo.lock
Cargo.toml
crates/starknet_api/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/442)

chore: update sn api version (pre-release)

---

Cargo.lock
config/mempool/default_config.json
crates/gateway/src/config.rs
crates/gateway/src/gateway.rs
crates/gateway/src/lib.rs
crates/mempool_node/Cargo.toml
crates/mempool_node/src/components.rs
crates/mempool_node/src/config/mod.rs
crates/tests-integration/src/integration_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/374)

chore(gateway): move compiler config to gateway component

---

crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/396)

chore: small refactor deploy_account

---

crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/397)

chore: small refactor declare account transaction

---

crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/398)

chore: small refactor invoke account transaction

---

.github/workflows/papyrus_ci.yml
.gitignore
scripts/papyrus/p2p_sync_e2e_test/client_node_config.json
scripts/papyrus/p2p_sync_e2e_test/main.sh
scripts/papyrus/p2p_sync_e2e_test/server_node_config.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/423)

test(sync): add e2e test for p2p sync

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/443)

chore: update blockifier version (pre-release)

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/399)

chore: streamline tx_hash getter method

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/422)

chore(ci): reduce gatekeepr calles to gh api

---

Cargo.lock
crates/batcher/Cargo.toml
crates/batcher/src/batcher.rs
crates/batcher/src/communication.rs
crates/mempool_node/Cargo.toml
crates/mempool_node/src/communication.rs
crates/mempool_node/src/components.rs
crates/mempool_node/src/servers.rs

feat: adding batcher to main node function

---

config/papyrus/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/src/config.rs

This is prep for adding sync_topic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/406)

refactor(consensus): rename topic in config to network_topic

---

Cargo.lock
crates/consensus_manager/Cargo.toml
crates/consensus_manager/src/config.rs
crates/consensus_manager/src/lib.rs

feat: add config template to consensus manager

---

config/mempool/default_config.json
crates/gateway/src/config.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/355)

chore: rename max_raw_class_size to max_contract_class_object_size

---

crates/committer_cli/benches/committer_bench.rs
crates/starknet_patricia/src/patricia_merkle_tree/external_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/477)

chore: change bench to allow consuming leaf modifications

---

crates/starknet_committer/src/forest/filled_forest.rs
crates/starknet_patricia/src/patricia_merkle_tree/external_test_utils.rs
crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs
crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/starknet_patricia/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/459)

chore: rename create to create_with_existing_leaves and remove Arcs

---

commitlint.config.js
crates/starknet_api/scripts/rust_fmt.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/476)

refactor(infra): clean up scripts folder

---

Cargo.lock
crates/papyrus_proc_macros/Cargo.toml
crates/papyrus_proc_macros/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/457)

feat(): print the execution time in latency_histogram macro

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs
crates/mempool_types/src/mempool_types.rs

…did not change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/341)

refactor(mempool): transaction pool stores full transaction, API did not change

---

crates/mempool_infra/src/component_server/remote_component_server.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/488)

chore(mempool_infra): add documentation to remote component server

---

crates/mempool_infra/src/component_client/remote_component_client.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/489)

chore(mempool_infra): add documentation to remote component client

---

crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/state/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/487)

feat(storage): more logs and metrics for storage writes

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/475)

refactor(mempool): delete new function since it's not in use

---

config/papyrus/default_config.json
crates/papyrus_network/src/e2e_broadcast_test.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/467)

feat(network): hardcode the external address of the node

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/497)

fix(network): missing multiaddr import

---

crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/440)

refactor(mempool): rename priority queue in transaction queue

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/216)

test(mempool): test_add_tx_after_get_txs_fails_on_duplicate_nonce

---

crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/mempool/src/communication.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool_types/src/communication.rs
crates/mempool_types/src/mempool_types.rs
crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/mock_batcher.rs
crates/tests-integration/tests/end_to_end_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/356)

refactor(mempool): change thin tx to internal tx

---

crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs
crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/errors.rs
crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs
crates/starknet_patricia/src/patricia_merkle_tree/internal_test_utils.rs
crates/starknet_patricia/src/patricia_merkle_tree/node_data/errors.rs
crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/469)

chore(committer): change leaf to be created with associated types

---

Cargo.lock
crates/gateway/src/gateway_test.rs
crates/mempool/Cargo.toml
crates/mempool/src/mempool_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/mempool_types/src/mempool_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/377)

refactor(mempool): delete thin tx struct

---

crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/528)

fix(consensus): dont prevote when receiving proposal in diff round

---

crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/501)

refactor(consensus): move creating msg functions to test_utils

---

crates/starknet_committer/src/forest/filled_forest.rs
crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/530)

chore(committer): add struct for contract state leaf input

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/e2e_broadcast_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/535)

fix(network): increase timeout for discovery and broadcast

---

crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/533)

refactor(consensus): change proposer function signature

---

crates/mempool/src/mempool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/472)

refactor(mempool): align mempool with account nonce

---

crates/blockifier/src/execution/contract_class.rs
crates/starknet_api/src/contract_class.rs

Per @yair-starkware's suggestion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/524)

chore: streamline the starknet api contract class object

---

crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/node.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/539)

chore(committer): fix FilledNode doc

---

crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/papyrus_p2p_sync/src/client/transaction.rs
crates/papyrus_p2p_sync/src/server/mod.rs
crates/papyrus_p2p_sync/src/server/test.rs
crates/papyrus_protobuf/src/converters/transaction.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs
crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/493)

chore(sync): add transaction hash to protobuf

---

docs/papyrus/README.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/339)

docs: running papyrus using p2p sync

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/370)

feat(consensus): add timeout events to sm

---

crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/502)

feat(consensus): handle timeouts in shc and manager

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/542)

chore: move tx_hash getter near other getters in account tx

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/network_manager/test_utils.rs
crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/stream_builder.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/papyrus_p2p_sync/src/server/test.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/447)

refactor(network): create test utils

---

.github/workflows/blockifier_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/558)

chore(ci): validate user's permissions before uploading artifacts step

---

crates/papyrus_network/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/567)

chore: fix starknet_api dependency in papyrus_network

---

crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/550)

refactor(consensus): pass block felt instead of hash to creating msg fn

---

Cargo.lock
crates/batcher/Cargo.toml
crates/batcher/src/lib.rs
crates/batcher/src/proposals_manager.rs
crates/batcher/src/proposals_manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/417)

feat(batcher): proposals manager module

---

.github/workflows/committer_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/579)

chore(ci, committer): stop running regression and bench on push

---

crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/450)

refactor(network): extract bodies of match arms in network manager

---

crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/562)

feat(mempool): add contains function to transaction pool

---

crates/blockifier/src/execution/contract_class.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/578)

chore: update estimate_casm_hash_computation_resources

---

.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/committer_ci.yml
.github/workflows/main.yml
.github/workflows/merge_paths_ci.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_docker-publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/552)

feat(ci): cancel old CI jobs on PR updates

---

crates/papyrus_network/src/e2e_broadcast_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/585)

fix(network): increase sleep for e2e broadcast test

---

crates/mempool/src/mempool.rs
crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/570)

refactor(mempool): rename tx queue methods

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/590)

test(mempool): rename full content new function to with pool and queue

---

crates/sequencing/papyrus_consensus/run_consensus.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/532)

refactor(consensus): avoid passing default args when running the script

---

crates/gateway/src/gateway_test.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/gateway/src/stateless_transaction_validator_test.rs
crates/gateway/src/utils.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/src/integration_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/607)

chore: rename external_tx to rpc tx

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/560)

test(mempool): rename assert mempool content to assert pool and queue

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/network_manager/test_utils.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/564)

feat(network): create broadcasted message manager

---

crates/papyrus_p2p_sync/src/server/mod.rs
crates/papyrus_p2p_sync/src/server/test.rs
crates/papyrus_protobuf/src/converters/class.rs
crates/papyrus_protobuf/src/proto/p2p/proto/class.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/593)

chore(network): add classhash to class proto

---

.github/workflows/merge_paths_ci.yml
scripts/merge_branches.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/616)

chore(ci): verify GH client is installed in merge_branches.py

---

.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/committer_ci.yml
.github/workflows/main.yml
.github/workflows/merge_paths_ci.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_docker-publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/626)

fix(ci): malformed concurrency rule in the CI workflows

---

scripts/merge_branches.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/619)

chore(ci): store old git config conflictstyle in merge_branches.py

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/513)

feat(mempool): implement pool capacity in transaction pool

---

workspace_tests/toml_utils.rs
workspace_tests/version_integrity_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/577)

feat(ci): add no path dependencies test

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/591)

test(mempool): remove full content from mempool content

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/629)

refactor(mempool): remove underscore from tx_pool getter

---

crates/starknet_api/src/core.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/601)

feat(starknet_api): nonce try_decrement func

---

crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/rpc_transaction.rs
crates/starknet_api/src/rpc_transaction_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/580)

refactor(fee): remove resource mapping usage in rpc and adjust to use all resources

---

config/papyrus/default_config.json
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/635)

chore(network): rename hardcoded_external_multiaddr config arg with advertised_multiaddr

---

.github/workflows/main.yml
scripts/run_codecov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/633)

chore: run codecov only on changed crates

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/648)

test(mempool): remove genertic type from mempool content

---

crates/mempool/src/mempool.rs
crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/483)

feat(mempool): implement update gas price for tx queue

---

.github/actions/install_rust/action.yml
.github/workflows/main.yml
scripts/rust_fmt.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/402)

chore(ci): reduce jobs to reduce API / bootstrap load

---

crates/gateway/src/stateful_transaction_validator_test.rs
crates/gateway/src/stateless_transaction_validator_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

in mempool_test_utils rename:
external_invoke_tx -> rpc_invoke_tx 
etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/645)

chore: rename to rpc_type_tx in mempool test utils

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/563)

test(mempool): test get_txs while updating gas price

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/602)

feat(consensus): resend last vote

---

crates/mempool/src/lib.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/suspended_transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/634)

feat(mempool): add suspended transaction pool, no implementation

---

crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/603)

feat(consensus): filter votes

---

Cargo.lock
crates/batcher/Cargo.toml
crates/batcher/src/proposals_manager.rs
crates/batcher/src/proposals_manager_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/548)

feat(batcher): stream transactions outside while generating proposal

---

crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/650)

refactor(consensus): use Vec::new() and handle event instead of task

---

crates/gateway/src/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/674)

chore: squash gateway spec errors for code dedup

---

crates/gateway/src/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/675)

chore: alphabetize the error gateway error types

---

crates/starknet_sierra_compile/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/597)

feat: use the build script to download the cairo crate from the starkware release page

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/680)

refactor(blockifier): os resource range check builtin

---

crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/687)

fix(consensus): the state machine should retain messages in the queue if GetProposal is produced

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/696)

test(mempool): add_tx_input tx nonce and account nonce variant

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/697)

test(mempool): add with_pool_and_account_nonces to mempool content

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/700)

test(mempool): refactor with_account_nonces in mempool content

---

crates/starknet_api/src/rpc_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/668)

chore: add impl from rpc tx to snapi tx

---

.github/workflows/committer_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/684)

chore(ci): add starknet api trigger

---

crates/sequencing/papyrus_consensus/src/bin/run_consensus.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/713)

refactor(consensus): handle stagnation when consensus didn't start

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/682)

refactor(mempool): add default input tx

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/721)

refactor(mempool): rename mempool content methods

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs

…(malicious / unstable)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/587)

refactor(network): blacklist duration depends on reputation modifier (malicious / unstable)

---

crates/starknet_api/src/executable_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/686)

chore: define creator for executable transaction

---

crates/papyrus_network/src/mixed_behaviour.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs

- refactor(network): blacklist duration depends on reputation modifier (malicious / unstable)
- refactor(network): fix CR comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/724)

refactor(network): make PeerManager not generic

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/705)

chore(blockifier): added gas vector computation mode to StarknetResources::to_gas_vector

---

crates/batcher/src/fee_market.rs
crates/batcher/src/fee_market_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/205)

test(mempool): impl tests for calculate gas price method

---

crates/sequencing/papyrus_consensus/src/bin/run_consensus.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/736)

fix(consensus): ensure logs_dir creation for run_consensus

---

commitlint.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/744)

chore: commitlint scopes cleanup

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/534)

feat(mempool): implement account nonces

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/755)

refactor(mempool): reorder account nonces tests

---

crates/starknet_api/src/test_utils/declare.rs
crates/starknet_api/src/test_utils/deploy_account.rs
crates/starknet_api/src/test_utils/invoke.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/672)

chore: create executable tx creator for testing

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/native_blockifier/src/py_state_diff.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/671)

build(fee): add l2 gas costs to versioned constants

---

Cargo.lock
Cargo.toml
crates/mempool_p2p/Cargo.toml
crates/mempool_p2p/src/lib.rs
crates/mempool_p2p/src/receiver/mod.rs
crates/mempool_p2p/src/sender/mod.rs
crates/mempool_types/src/communication.rs
crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/479)

feat(mempool): add basic p2p agent interface with unimplemented code

---

crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin_utils/mod.rs
docs/papyrus/README.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/704)

feat(network): add dns transport

---

crates/papyrus_protobuf/build.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/papyrus_protobuf/src/converters/rpc_transaction.rs
crates/papyrus_protobuf/src/converters/rpc_transaction_test.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs
crates/papyrus_protobuf/src/lib.rs
crates/papyrus_protobuf/src/mempool.rs
crates/papyrus_protobuf/src/proto/p2p/proto/rpc_transaction.proto
crates/papyrus_test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/631)

feat(protobuf): create rpctransaction proto file and converters

---

crates/blockifier/src/concurrency/worker_logic.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/775)

chore(concurrency): small refactor

---

crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/667)

feat(sync): add class channel without usage

---

crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/670)

refactor(blockifier):  refactor transaction fee error

---

Cargo.lock
Cargo.toml
crates/starknet_api/src/crypto/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/769)

chore(starknet_api): upgrade starknet-rs (starknet-crypto)

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/contract_class_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/730)

feat(blockifier): add compiler version to V1ContractClass

---

crates/blockifier/src/transaction/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/791)

fix(blockifier): error typo

---

crates/starknet_api/src/test_utils/declare.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/779)

chore: align test util executable_declare_tx with account tx counterpart

---

crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/integration_test_utils.rs

chore: rename testing http gateway client

---

crates/starknet_committer/Cargo.toml

fix: remove license file duplication

---

crates/blockifier/resources/versioned_constants_13_0.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/802)

fix(blockifier): add deny_unknown_fields to versioned constants

---

crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/807)

fix(consensus): test network receiver uses BroadcastClientTrait<ConsensusMessage>

---

crates/gateway_types/src/gateway_types.rs
crates/http_server/src/http_server.rs

feat: make message metadata optional

---

crates/committer_cli/benches/committer_bench.rs
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/regression_tests.rs
crates/starknet_committer/src/forest/original_skeleton_forest.rs
crates/starknet_committer/src/patricia_merkle_tree/tree.rs
crates/starknet_patricia/src/patricia_merkle_tree/external_test_utils.rs
crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/starknet_patricia/src/patricia_merkle_tree/internal_test_utils.rs
crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs
crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/config.rs
crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/starknet_patricia/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs
crates/starknet_patricia/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/754)

refactor(committer): refactor original skeleton tree config

---

crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/utils.rs
crates/mempool/src/mempool.rs
crates/papyrus_protobuf/src/converters/rpc_transaction_test.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs
crates/starknet_api/src/executable_transaction.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/819)

chore(starknet_api): derive copy trait for resource bounds struct

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/808)

chore: add a test for panic in __execute__

---

crates/mempool/src/suspended_transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/663)

feat(mempool): add contains func to suspended tx pool

---

crates/mempool/src/suspended_transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/662)

feat(mempool): add insert func to suspended tx pool

---

crates/mempool/src/suspended_transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/784)

feat(mempool): add remove funct to suspended tx pool

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/836)

chore(mempool): derive copy for transaction reference struct

---

Cargo.lock
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/mempool/src/communication.rs
crates/mempool_types/Cargo.toml
crates/mempool_types/src/communication.rs
crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/746)

refactor(mempool): provide optional broadcasted message metadata in mempool add_tx

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/e2e_broadcast_test.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/network_manager/test_utils.rs
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/794)

refactor(network): flatten broadcast topic channels

---

crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/transfers_generator.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/748)

test: move nonce manager to starknet api test utils

---

crates/starknet_api/src/block.rs
crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_hash/block_hash_calculator_test.rs
crates/starknet_api/src/crypto/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/683)

feat(block_hash): add l2 gas to the block hash

---

Cargo.lock
config/mempool/default_config.json
crates/consensus_manager/Cargo.toml
crates/consensus_manager/src/consensus_manager.rs
crates/mempool_node/src/config/mod.rs

commit-id:b917af79
---
**Stack**:
- #831
- #830 ⬅

chore: remove deprecated 'active component' option

---

crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_hash/block_hash_calculator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/814)

feat(block_hash): starknet version for block hash

---

crates/starknet_api/src/block_hash/block_hash_calculator_test.rs

[Context](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v65yHCuMIIWUWr48W)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/844)

refactor(starknet_api): test that changing any field changes the hash

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/block.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/papyrus_rpc/src/v0_7/block.rs
crates/papyrus_storage/src/header_test.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/src/block.rs
crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_test.rs
crates/starknet_client/src/reader/objects/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/838)

refactor(starknet_api): represent starknet version as vec of ints

---

Cargo.lock
Cargo.toml
crates/mempool_p2p/src/sender/mod.rs
crates/mempool_p2p_types/Cargo.toml
crates/mempool_p2p_types/src/communication.rs
crates/mempool_p2p_types/src/errors.rs
crates/mempool_p2p_types/src/lib.rs
crates/mempool_p2p_types/src/mempool_p2p_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/820)

refactor(mempool): split mempool_p2p crate to types and business logic crates

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/832)

chore(mempool): implement mempool content builder

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/868)

feat(blockifier): move resource hex represenation definition

---

crates/committer_cli/src/tests/utils/objects.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_protobuf/src/converters/receipt.rs
crates/papyrus_protobuf/src/proto/p2p/proto/receipt.proto
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_test_utils/src/lib.rs
crates/starknet_api/src/block_hash/test_utils.rs
crates/starknet_api/src/execution_resources.rs
crates/starknet_client/src/reader/objects/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/786)

refactor(starknet_api): add l2 gas to gas vector

---

crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/839)

chore(mempool): derive copy trait for pending and priority structs

---

crates/blockifier/src/fee/fee_checks.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/881)

fix(blockifier): update fee check error message

---

crates/papyrus_node/src/main.rs
crates/papyrus_node/src/main_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/865)

refactor(node): create papyrus resources for generating top level tasks

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/882)

refactor(mempool): add a commit_block test util

---

crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/867)

refactor(node): miscellaneous clippy suggestions

---

config/mempool/default_config.json
crates/mempool_node/src/config/mod.rs

chore: rename component type names

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/853)

chore: fix versioned constants

---

crates/mempool/src/mempool_test.rs
crates/mempool_node/src/config/config_test.rs
crates/papyrus_storage/src/mmap_file/mmap_file_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/883)

test: use assert_eq!(X, Ok(())) where possible for better error message

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/transaction/objects_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/887)

chore(blockifier): move test struct to test file

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/892)

fix(blockifier): remove unsupported syscall: library_call_l1_handler

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/891)

test: remove unused add_tx_input! macro rules

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/resources/versioned_constants_13_0.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/850)

chore: add enable revert flag to versioned constants

---

.github/workflows/security-scan.yml

adding semgrep scans
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/845)

chore(ci): create security-scan.yml

---

Cargo.lock
Cargo.toml
commitlint.config.js
crates/l1-provider/Cargo.toml
crates/l1-provider/src/errors.rs
crates/l1-provider/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/897)

feat: add l1-provider crate + main API

---

crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_rpc/src/pending.rs
crates/papyrus_rpc/src/v0_8/api/api_impl.rs
crates/starknet_client/src/reader/objects/pending_data.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/643)

chore(execution): add l2_gas_price to PendingData

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/consensus_test.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/909)

refactor: rename chunk_id->message_id

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/917)

chore(mempool): tidy-up tests some more

---

crates/mempool/src/mempool_test.rs

Also, remove type annotation, which is now clear from method name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/924)

refactor(mempool): add MempoolContentBuilder::build_into_mempool method

---

crates/mempool/src/mempool_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_api/src/test_utils/deploy_account.rs
crates/starknet_api/src/test_utils/invoke.rs

Replacing the PR: 789# because:
1. It diverged a bit after a merge conflict.
2. @MohammadNassar1 is going on vacation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/922)

test: use the executable_invoke_tx_creator in mempool test

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/914)

refactor(mempool): use tx!() in additional locations

---

Cargo.lock
crates/batcher/src/communication.rs
crates/batcher_types/Cargo.toml
crates/batcher_types/src/batcher_types.rs
crates/batcher_types/src/communication.rs
crates/batcher_types/src/errors.rs
crates/consensus_manager_types/Cargo.toml
crates/consensus_manager_types/src/consensus_manager_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/751)

feat(batcher): batcher client trait

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/consensus_test.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto
crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/777)

feat(consensus): add valid_round to proposal

---

crates/sequencing/papyrus_consensus/src/manager.rs
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/734)

feat(consensus): remove ConsensusBlock trait

---

crates/l1-provider/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/947)

feat(l1-provider): initial get_txs impl

---

crates/starknet_api/src/block_hash/transaction_commitment.rs
crates/starknet_api/src/block_hash/transaction_commitment_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/953)

feat(starknet_api): none signature to an empty list

---

crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/954)

refactor(blockifier): test fail validate

---

crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/955)

refactor(blockifier): remove constant in fail validate test

---

scripts/publish_crates.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/893)

feat: add publish crates script

---

scripts/publish_crates.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/894)

feat: implement non-published verification

---

crates/mempool/src/transaction_queue.rs
crates/mempool/src/transaction_queue_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/967)

test(mempool): add TransactionQueueContent[Builder]

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscall_tests/deploy.rs
crates/blockifier/src/state/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/970)

refactor(blockifier): unavailable contract address error

---

crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/735)

feat(consensus): add active_proposals to context

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/926)

feat(consensus): shc handle sm proposal

---

.github/actions/install_rust/action.yml
.github/workflows/committer_ci.yml
.github/workflows/main.yml
.github/workflows/papyrus_nightly-tests.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/949)

chore(ci): tune boostraping cache

---

.github/actions/bootstrap/action.yml
.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/blockifier_post-merge.yml
.github/workflows/committer_ci.yml
.github/workflows/main.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_nightly-tests-call.yml
.github/workflows/papyrus_nightly-tests.yml
.github/workflows/verify-deps.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/941)

chore(infra): add bootstrap flow to the ci

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/resources/versioned_constants_13_0.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/versioned_constants.rs
crates/native_blockifier/src/py_state_diff.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/815)

fix(blockifier): l1 to l2 gas price ratio

---

scripts/merge_branches.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/984)

fix(ci): fix merge_branches.py, no changed_files dir

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/resources/versioned_constants_13_0.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/971)

feat(blockifier): versioned constants builtin names no longer strings

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue_test_utils.rs

…tent[Builder]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/977)

refactor(mempool): use TransactionQueueContent[Builder] in MempoolContent[Builder]

---

crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/988)

refactor(consensus): remove ConsensusContext::Block

---

crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/992)

fix(blockifier): remove duplicated function

---

crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1001)

chore(blockifier): rename messages cost functions

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1000)

test(mempool): remove pool capacity test; tested indirectly

---

scripts/run_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/782)

chore(ci): refactor run_tests.py

---

crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde.rs
crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1003)

fix(committer): deserialize contract state without nonce

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions.rs
crates/gateway/src/stateful_transaction_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/983)

chore: remove clone of casm class on conversion in stateful validator

---

crates/mempool_infra/src/component_server/local_component_server.rs

**Stack**:
- #976
- #975
- #974
- #933 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/933)

chore(mempool_infra): unify local server structs

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1013)

test(mempool): tidy-up test_get_txs_returns_by_priority_order

---

crates/tests-integration/src/state_reader.rs

There is only a single usage and the value is always BALANCE.
Might be useful to make this configurable at some point, but right now the LOC overhead isn't justified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1017)

refactor(tests-integration): remove balance arg

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1019)

refactor(mempool): add get_txs_and_assert_expected test util

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1022)

refactor(mempool): rename MempoolContent[Builder] methods queue -> priority_queue

---

crates/native_blockifier/src/storage.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/state_reader_test.rs
crates/papyrus_execution/src/test_utils.rs
crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/server/test.rs
crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_rpc/src/rpc_test.rs
crates/papyrus_rpc/src/v0_8/api/api_impl.rs
crates/papyrus_rpc/src/v0_8/api/test.rs
crates/papyrus_rpc/src/v0_8/block.rs
crates/papyrus_rpc/src/v0_8/execution_test.rs
crates/papyrus_storage/src/body/events_test.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/header_test.rs
crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central_sync_test.rs
crates/papyrus_sync/src/sync_test.rs
crates/papyrus_test_utils/src/lib.rs
crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs
crates/starknet_api/src/block.rs
crates/starknet_client/src/reader/objects/block.rs
crates/tests-integration/src/state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/931)

refactor: blockHeaderWithoutHash under BlockHeader

---

crates/blockifier/src/transaction/execution_flavors_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/995)

refactor(blockifier): check gas and fee in pre validate test

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1023)

test(mempool): some more tidying-up

---

crates/papyrus_protobuf/build.rs
docs/papyrus/README.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/884)

fix(protobuf): allow using a local installation of Protoc instead of using protoc_prebuilt

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/944)

refactor(blockifier): update transaction cost in versioned constants

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1040)

refactor(tests-integration): rename

---

Cargo.lock
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs
crates/blockifier/src/transaction/constants.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/papyrus_common/src/lib.rs
crates/papyrus_common/src/transaction_hash.rs
crates/papyrus_common/src/transaction_hash_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_node/examples/get_transaction_hash.rs
crates/papyrus_rpc/tests/gateway_integration_test.rs
crates/starknet_api/Cargo.toml
crates/starknet_api/src/transaction.rs
crates/starknet_api/src/transaction_hash.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/915)

refactor(common,starknet_api): align tx hash logic to papyrus_common

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/objects_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1024)

chore(blockifier): add EventSummary to ExecutionSummary

---

crates/blockifier/src/fee/receipt.rs
crates/blockifier/src/transaction/objects.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1020)

refactor(blockifier): move ugly code to native blockifier

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1043)

chore(blockifier): use serde explicitly in tx serde

---

crates/blockifier/src/bouncer.rs
crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/objects_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1005)

refactor(blockifier): move event and message summary to ExecutionSummary

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/fee/receipt_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1011)

chore(blockifier): remove unnecessary message utils

---

crates/blockifier/src/bouncer.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1018)

refactor(blockifier): define ArchivalDataResources struct

---

Cargo.lock
Cargo.toml
crates/blockifier_regression_test/Cargo.toml
crates/blockifier_regression_test/src/lib.rs
crates/blockifier_regression_test/src/test_state_reader.rs
crates/gateway/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/945)

build: regression test crate

---

crates/blockifier/src/blockifier/stateful_validator_test.rs
crates/blockifier/src/concurrency/fee_utils_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/execution/stack_trace_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/912)

chore(blockifier): renamed max_resource_bounds -> max_l1_resource_bounds

---

config/papyrus/default_config.json
crates/blockifier/resources/versioned_constants.json
crates/blockifier/resources/versioned_constants_13_0.json
crates/blockifier/resources/versioned_constants_13_1.json
crates/blockifier/resources/versioned_constants_13_1_1.json
crates/blockifier/resources/versioned_constants_13_2.json
crates/blockifier/resources/versioned_constants_13_2_1.json
crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_rpc/resources/test_config.json
crates/papyrus_rpc/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/958)

feat(blockifier): rename initial_gas_cost to default_initial_gas_cost

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1049)

refactor(blockifier): remove ugly call info iterator

---

crates/blockifier/src/bouncer.rs
crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1054)

chore(blockifier): define and use MessageResources

---

crates/blockifier/src/bouncer.rs
crates/blockifier/src/bouncer_test.rs
crates/blockifier/src/fee/receipt.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1055)

chore(blockifier): define ComputationResources and use it

---

crates/blockifier_regression_test/Cargo.toml

fix: remove license file duplication in blockifier_regression_test

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1047)

refactor(mempool): remove u8 from mempool tests

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/771)

chore(blockifier): check max gas amount covers minimal estimated gas amount

---

crates/blockifier/src/blockifier/stateful_validator.rs
crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/entry_point_execution.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/receipt.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1069)

chore(blockifier): remove unnecessary Result return types

---

crates/blockifier/src/abi/abi_utils_test.rs
crates/blockifier/src/blockifier/stateful_validator_test.rs
crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/concurrency/scheduler_test.rs
crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/execution/stack_trace.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/transfers_generator.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/error_format_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/objects_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/papyrus_execution/src/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1072)

refactor(blockifier): rename transaction -> tx

---

crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs
crates/mempool_types/src/mempool_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1076)

refactor(mempool): rename AccountState sender_address field to address

---

crates/blockifier/src/transaction/account_transaction.rs
crates/starknet_api/src/executable_transaction.rs
crates/starknet_api/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/698)

refactor(blockifier): add getters for exclusive v3 txs fields

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/699)

refactor(blockifier): handle common getters with optional fields

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

Final design didn't need all of these states, it's basically just a
protection wrapper around `FeatureContract`, which will be ensure that
the tx generator's internal account abstraction has a consistent
address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1051)

refactor(tests-integration): simplify accounts

---

crates/blockifier/src/versioned_constants.rs
crates/native_blockifier/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1042)

feat(native_blockifier): expose the starknet version (for VC) to python

---

crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_hash/state_diff_hash.rs
crates/starknet_api/src/core.rs
crates/starknet_api/src/core_test.rs
crates/starknet_api/src/transaction_hash.rs
crates/starknet_api/src/transaction_hash_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1037)

chore: move the function ascii_as_felt to starknet core

---

Cargo.lock
Cargo.toml
crates/mempool_p2p_types/Cargo.toml
crates/mempool_p2p_types/src/communication.rs
crates/mempool_types/Cargo.toml
crates/mempool_types/src/communication.rs
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test_utils.rs
crates/papyrus_network_types/Cargo.toml
crates/papyrus_network_types/src/lib.rs
crates/papyrus_network_types/src/network_types.rs
crates/papyrus_network_types/src/test_utils.rs
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/manager_test.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs
crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1032)

refactor(network): move BroadcastedMessageManager to separate crate and add OpaquePeerId

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_execution.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/928)

feat(blockifier): add TrackingResource to CallInfo and use to update gas

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1078)

test(mempool): remove already covered test

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1079)

test(mempool): check transaction removal from pool in get_txs in a single dedicated test

---

crates/batcher_types/src/batcher_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1083)

refactor(batcher): rename ProposalContentId to ProposalCommitment

---

crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1060)

chore(blockifier): define and use StateResources

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1081)

refactor(mempool): with_account_nonces to use &str,u8

---

crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1087)

chore(blockifier): move function definition out of macro

---

Cargo.lock
crates/batcher/src/batcher.rs
crates/consensus_manager/Cargo.toml
crates/consensus_manager/src/consensus_manager.rs
crates/gateway/src/gateway.rs
crates/http_server/Cargo.toml
crates/http_server/src/http_server.rs
crates/mempool/src/communication.rs
crates/mempool_infra/src/component_server/empty_component_server.rs
crates/mempool_infra/src/component_server/local_component_server.rs
crates/mempool_infra/src/component_server/remote_component_server.rs
crates/mempool_infra/src/errors.rs
crates/mempool_infra/src/lib.rs
crates/mempool_infra/src/starters.rs
crates/mempool_infra/tests/active_local_component_client_server_test.rs
crates/mempool_infra/tests/common/mod.rs
crates/mempool_p2p/src/receiver/mod.rs

commit-id:f037fa74
---
**Stack**:
- #1058
- #1057
- #1056
- #1027
- #1026 ⬅
- #976

chore(mempool_infra): rename generic parameter in empty server

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1091)

test(mempool): add more tx!() macro usages

---

Cargo.lock
crates/consensus_manager/Cargo.toml
crates/consensus_manager/src/communication.rs
crates/gateway/src/communication.rs
crates/mempool/src/communication.rs
crates/mempool_infra/src/component_server/definitions.rs
crates/mempool_infra/src/component_server/empty_component_server.rs
crates/mempool_infra/src/component_server/local_component_server.rs
crates/mempool_infra/src/component_server/remote_component_server.rs
crates/mempool_infra/src/starters.rs
crates/mempool_infra/tests/active_local_component_client_server_test.rs
crates/mempool_infra/tests/local_component_client_server_test.rs
crates/mempool_infra/tests/remote_component_client_server_test.rs
crates/mempool_node/src/communication.rs
crates/mempool_node/src/servers.rs
crates/tests-integration/src/integration_test_setup.rs

commit-id:e8a80c55
---
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100
- #1099
- #1098
- #1097
- #1096
- #1090
- #1089
- #1088
- #1058
- #1057 ⬅
- #1056
- #1027

chore(mempool_node): separate server struct

---

crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_hash/block_hash_calculator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1077)

feat(starknet_api): chain version to the gas prices

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1068)

test(mempool): remove nop commit_block-s from two queues tests

---

Cargo.lock
crates/mempool_test_utils/Cargo.toml
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/src/state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1065)

feat(tests-integration): ban invokes with nonce=0

---

Cargo.lock
crates/mempool_test_utils/Cargo.toml
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/integration_test_utils.rs
crates/tests-integration/src/state_reader.rs
crates/tests-integration/tests/end_to_end_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1067)

fix(tests-integration): reenable e2e test

---

crates/mempool_node/src/communication.rs
crates/mempool_node/src/components.rs
crates/mempool_node/src/servers.rs
crates/mempool_node/src/utils.rs

commit-id:9866f163
---
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100
- #1099
- #1098 ⬅
- #1097

chore(mempool_node): rename client struct

---

crates/mempool_node/src/components.rs
crates/mempool_node/src/servers.rs

commit-id:217f2684
---
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100
- #1099 ⬅

chore(mempool_node): rename component struct

---

crates/mempool_infra/src/lib.rs
crates/mempool_infra/src/test_utils.rs
crates/mempool_infra/src/tests/remote_component_client_server_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1108)

chore: remove port consts from remote_component test

---

crates/mempool_node/src/bin/mempool_dump_config.rs
crates/mempool_node/src/communication.rs
crates/mempool_node/src/components.rs
crates/mempool_node/src/config/config_test.rs
crates/mempool_node/src/config/mod.rs
crates/mempool_node/src/main.rs
crates/mempool_node/src/servers.rs
crates/mempool_node/src/utils.rs
crates/tests-integration/src/integration_test_utils.rs

commit-id:e9d31884
---
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100 ⬅

chore(mempool_node): rename config

---

config/mempool/default_config.json
crates/consensus_manager/src/communication.rs
crates/http_server/src/communication.rs
crates/mempool_infra/src/component_server/empty_component_server.rs
crates/mempool_infra/src/tests/active_local_component_client_server_test.rs
crates/mempool_node/src/components.rs
crates/mempool_node/src/config/config_test.rs
crates/mempool_node/src/config/mod.rs
crates/mempool_node/src/main.rs
crates/mempool_node/src/servers.rs
crates/mempool_node/src/utils.rs
crates/tests-integration/src/integration_test_setup.rs

commit-id:ae43aa09
---
**Stack**:
- #1111
- #1110 ⬅
- #1109
- #1103
- #1102
- #1101

chore(mempool_node): add missing http config

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/src/state_reader.rs

** RENAME AND DOCS ONLY **
Rename:
- FeatureAccount -> Contract, this was an incorrect name, since we use this abstraction for both non-accounts and accounts. This is basically an enhancement of FeatureContract, allowing to construct it from a deploy account tx, as well as through the literal constructor.
- `account: Contract` -> `contract: Contract`.
Also added docs to clarify this issue.
Note: we still unfortunately expose `ThinStateDiffBuilder#fund()` for non-account contracts, which is only protected via an assert, but AFAICS mending this requires touchups inside FeatureContract itself, which is out of scope here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequen …

refactor(mempool_test_utils): rename contract

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1130)

chore(infra): remove redundent cargo check

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1138)

fix(blockifier): remove unused import

---

crates/blockifier/resources/versioned_constants_0_13_3.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1128)

chore: update resources in versioned_constants.json

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1143)

test(mempool): rename state_changes -> nonces

---

commitlint.config.js
crates/mempool/src/communication.rs
crates/mempool_types/src/communication.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1146)

feat(mempool_types): add commit_block to mempool communication types

---

.github/workflows/blockifier_ci.yml
.github/workflows/upload_artifacts_workflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1140)

chore: trigger blockifier ci on upload artifacts changes

---

crates/blockifier_regression_test/resources/raw_rpc_json_objects/transactions.json
crates/blockifier_regression_test/src/state_reader/raw_rpc_json_test.rs
crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs
crates/blockifier_regression_test/src/state_reader/test_state_reader.rs
crates/blockifier_regression_test/src/state_reader/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1021)

build: blockifier regression test serde rpc tx to starknet api tx

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1145)

refactor(blockifier): remove match and move try_into

---

.github/workflows/blockifier_compiled_cairo.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1133)

feat(ci): no cairo recompile in post-merge

---

.github/workflows/merge_paths_ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1135)

feat(ci): no merge-paths test in post-merge

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_rpc/resources/V0_8/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_8/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1007)

chore(execution): rename l1 gas in FeeEstimation

---

.github/workflows/upload_artifacts_workflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1184)

chore: update commit sha in upload artifacts workflow

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1161)

test(mempool): convert partial commit block test into a proper flow test

---

Cargo.lock
crates/mempool/Cargo.toml
crates/mempool/src/lib.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1182)

refactor(mempool): move test utils to a separate file

---

config/mempool/default_config.json
crates/mempool_infra/src/component_client/remote_component_client.rs
crates/mempool_infra/src/component_definitions.rs
crates/mempool_infra/src/tests/remote_component_client_server_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1120)

chore: add communication config struct

---

crates/committer_cli/src/tests/utils/objects.rs
crates/starknet_api/src/block_hash/block_hash_calculator.rs
crates/starknet_api/src/block_hash/block_hash_calculator_test.rs
crates/starknet_api/src/block_hash/transaction_commitment.rs
crates/starknet_api/src/block_hash/transaction_commitment_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1181)

chore(starknet_api): transaction signature is not Option

---

.github/workflows/papyrus_benchmark.yaml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_docker-publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1171)

fix: cosmetic changes in Docker and yaml files

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1200)

refactor(mempool): implement single [Mempool,TransactionQueue]Content::assert_eq

---

crates/blockifier/resources/versioned_constants_0_13_0.json
crates/blockifier/resources/versioned_constants_0_13_1.json
crates/blockifier/resources/versioned_constants_0_13_1_1.json
crates/blockifier/resources/versioned_constants_0_13_2.json
crates/blockifier/resources/versioned_constants_0_13_2_1.json
crates/blockifier/resources/versioned_constants_0_13_3.json
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/978)

chore: add ERROR_ENTRYPOINT_FAILED to version_constants

---

config/mempool/default_config.json
crates/mempool_infra/src/component_client/remote_component_client.rs
crates/mempool_infra/src/component_definitions.rs
crates/mempool_infra/src/tests/remote_component_client_server_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1121)

feat: add configuration for idle timeout and max idle connections

---

crates/blockifier/src/fee/fee_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1186)

test(blockifier): saturation + regression test for get_fee_by_gas_vector

---

config/mempool/default_config.json
crates/mempool_infra/src/component_client/remote_component_client.rs
crates/mempool_infra/src/component_definitions.rs
crates/mempool_infra/src/tests/remote_component_client_server_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1211)

fix(mempool_infra): change idle_timeout type from duarion to u64

---

crates/mempool_infra/src/component_client/local_component_client.rs
crates/mempool_infra/src/component_definitions.rs
crates/mempool_infra/src/component_server/definitions.rs
crates/mempool_infra/src/component_server/empty_component_server.rs
crates/mempool_infra/src/component_server/local_component_server.rs

commit-id:fafff049
---
**Stack**:
- #1209
- #1208 ⬅

chore(mempool_infra): add tracing

---

crates/blockifier/src/blockifier/transaction_executor_test.rs
crates/blockifier/src/bouncer.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/fee/receipt_test.rs
crates/blockifier/src/fee/resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs
crates/native_blockifier/src/py_block_executor.rs
crates/papyrus_execution/src/objects.rs
crates/starknet_api/src/execution_resources.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1172)

refactor(blockifier,starknet_api): add GasAmount (u128) type and use in blockifier's GasVector

---

.github/workflows/upload_artifacts_workflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1213)

chore: change checkout ref

---

.github/workflows/blockifier_ci.yml
.github/workflows/blockifier_compiled_cairo.yml
.github/workflows/committer_ci.yml
.github/workflows/main.yml
.github/workflows/merge_paths_ci.yml
.github/workflows/papyrus_ci.yml
.github/workflows/papyrus_docker-publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1156)

fix(ci): concurrency group per-job

---

crates/mempool/src/mempool_test.rs

Will move to `/tests/flow_test.rs` next PR, for an easy diff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1217)

test(mempool): convert a test into a proper flow test

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1220)

refactor(mempool): tidy-up a test

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/sequencer/1214)

feat(mempool): commit block acts as account nonce source of truth
